### ISSUE TITLE
Both Spotify ipas are not good(trash) (imo)

### ISSUE THREAD

**Issue by gototheskinny** [swaggyP36000/TrollStore-IPAs#1]
[This version (8.5.60) is FAR BETTER than those](https://reddit.com/r/sideloaded/comments/wjwgv0/latest_spotilife_v18_sposify_v8552_working_lyrics/)

I suggest you to release this on this repo as a stable or "best" Spotify experience version. Try this version you'll see what I mean.

**Comment by swaggyP36000** [comment]
The versions I have work fine and include all the Spotilife essentials. The other reason why I didn't initially include this version is that lower versions of Spotify won't see the Spotify Rewind stats in December

What iOS version are you on? I can include it as an optional version to try

**Comment by gototheskinny** [comment]
> The versions I have work fine and include all the Spotilife essentials. The other reason why I didn't initially include this version is that lower versions of Spotify won't see the Spotify Rewind stats in December
> 
> 
> 
> What iOS version are you on? I can include it as an optional version to try

iphone 12 with ios 15.0. The versions that you've released are not showing Playlists as it should be(but the version that I recommended is working flawless) it lacks highest quality option as well.. I'm not expecting this feature on every ipa tho. I think people would appreciate this version a lot more. I don't know about the rewind feature it's not deal breaker for me.

**Comment by swaggyP36000** [comment]
With iOS 15.x and up, newer versions of Spotify/Spotilife are known to have issues, and features are hit-and-miss. I am on iOS 14.4, so I can confirm that the ones currently on this repo will work on iOS 14.x

I will include this version you've recommended as an optional alternative for iOS 15.x and up

**Comment by gototheskinny** [comment]
> With iOS 15.x and up, newer versions of Spotify/Spotilife are known to have issues, and features are hit-and-miss. I am on iOS 14.4, so I can confirm that the ones currently on this repo will work on iOS 14.x
> 
> 
> 
> I will include this version you've recommended as an optional alternative for iOS 15.x and up

Oh I didn't know that. It makes sense I guess ios 14 is jailbroken and ios 15 is problematic when it comes to jailbreaks obviously. But I'm just guessing almost %90~ of the ios users are on ios15+ so this would be great for almost everyone.

**Comment by swaggyP36000** [comment]
I have added the IPA for it under today's release. Hopefully it will be helpful to iOS 15.x (and above) users

**Comment by gototheskinny** [comment]
> I have added the IPA for it under today's release. Hopefully it will be helpful to iOS 15.x (and above) users

Thank you!
