### ISSUE TITLE
Monopoly ipa doesn’t work

### ISSUE THREAD

**Issue by Blockr22** [swaggyP36000/TrollStore-IPAs#10]
Signed with SideStore, its stuck at black screen after initial loading.
Can someone plz fix it for SideStore ?

**Comment by swaggyP36000** [comment]
I will make a note in the app description regarding this. For me, it is playable when installed via TrollStore

**Comment by Blockr22** [comment]
Kk, thnx. Maybe someone fix it for SideStore then.
