### ISSUE TITLE
Displayed repo on TrollApps

### ISSUE THREAD

**Issue by EscapeAltDelete** [swaggyP36000/TrollStore-IPAs#102]
![image](https://github.com/swaggyP36000/TrollStore-IPAs/assets/96600150/a28a1326-d896-4e66-8f2d-1c963cb205bc)

![image](https://github.com/swaggyP36000/TrollStore-IPAs/assets/96600150/7180d2c5-4110-4bf6-b210-e6b1ecb29174)

**Comment by ArianaMinajj** [comment]
Hello, 

Read TrollApps description.
