### ISSUE TITLE
Repo Not Displaying in GBox/ESign

### ISSUE THREAD

**Issue by thomasza92** [swaggyP36000/TrollStore-IPAs#103]
Adding the repo via JSON link to GBox as a source no longer displaying correctly on GBox. Used to work fine, was able to add apps less than a week ago.

GBox v4.6
iOS 17.1.2
iPhone 12 Pro Max

How Repo is Displaying Currently:
![image](https://github.com/swaggyP36000/TrollStore-IPAs/assets/127898797/d88314df-dc0a-4a3e-9433-84a3c3e711e1)

How it Looked Before (default GBox source as example):
![image](https://github.com/swaggyP36000/TrollStore-IPAs/assets/127898797/fc993482-54ca-49ad-801f-6ea4ec492459)

Tried clearing cache / reinstalling GBox to no avail.

Noticed the TrollStore 2 update - is JSON somehow formatted differently now as part of this update? 

Love this repo, really great work - hope to continue to use it!

**Comment by ArianaMinajj** [comment]
Hi there,

There's no explicit support/doc stating that adding this repo would function correctly in GBox. 

As such, it's challenging to provide assistance for this specific issue. I'd also like to ask why you're not using ESign instead? It could potentially offer a more seamless experience..

**Comment by thomasza92** [comment]
> Hi there,
> 
> There's no explicit support/doc stating that adding this repo would function correctly in GBox. 
> 
> As such, it's challenging to provide assistance for this specific issue. I'd also like to ask why you're not using ESign instead? It could potentially offer a more seamless experience..

I'll try ESign out. I'm assuming the latest push that changed indent formatting is what caused the issue.

Thanks.

**Comment by ArianaMinajj** [comment]
Wait I'm so sorry I just realized that hieuddo made some changes which seem to be the cause of the issue you're facing. I will make sure to keep you updated on the situation!

**Comment by ArianaMinajj** [comment]
They've made some changes so that apps don't display separately for each version on **[TrollApps 2](https://github.com/TheResonanceTeam/TrollApps/releases/download/2.1/org.resonance.store_TrollApps_2.1.ipa)**, which I now strongly advise you to download!

**Comment by thomasza92** [comment]
> They've made some changes so that apps don't display separately for each version on **[TrollApps 2](https://github.com/TheResonanceTeam/TrollApps/releases/download/2.1/org.resonance.store_TrollApps_2.1.ipa)**, which I now strongly advise you to download!

I see, thanks. Does it still display correctly in ESign? I'd love to use TrollStore 2 but I've already made the mistake of updating past the point of no return I'm afraid. I imagine GBox / Esign will perhaps fix this sometime in the future if it becomes common formatting? In the interim I may fork this repo and rollback the commit so I can still use on GBox.

**Comment by ArianaMinajj** [comment]
Oddly enough, the most recent ipas I've updated aren't appearing, but it still shows the others as it did before their update in Esign.

**Comment by thomasza92** [comment]
> Oddly enough, the most recent ipas I've updated aren't appearing, but it still shows the others as it did before their update in Esign.

Perhaps you all would consider a branch that slowly rolls out any formatting changes as they are fixed in the other signing apps? 🥺

**Comment by ArianaMinajj** [comment]
The repo has been updated for full compatibility with Trollapps. Consequently, I'm in the process of enhancing the json. 

Given the increased efficiency that Trollapps offers now, I might need to reject your request because it surpasses the utility of any signing apps. (including ESing)

**Comment by ArianaMinajj** [comment]
**No longer supported on ESign/Gbox.**
