### ISSUE TITLE
Add source to SideStore does not work

### ISSUE THREAD

**Issue by alexdonh** [swaggyP36000/TrollStore-IPAs#105]
![IMG_0176](https://github.com/swaggyP36000/TrollStore-IPAs/assets/10590429/181ffb57-3fe1-477f-a772-683beb958185)

**Comment by ArianaMinajj** [comment]
Hi there, 

I accidentally left SideStore in the description. The recent update makes the repository compatible only with TrollApps and AltStore, as far as I know.

**Comment by alexdonh** [comment]
well if thats the case then... anyways, SideStore is in fact a fork of AltStore perhaps interoperability isnt that hard...

from what i interpreted, it looks like there may be some versions in the source json file that have the downloadURL absent.. worth having a check?

**Comment by n0rpie** [comment]
This never got fixed right?
