### ISSUE TITLE
[Request] Consider Adding YTLitePlus

### ISSUE THREAD

**Issue by ProvokedGamer** [swaggyP36000/TrollStore-IPAs#107]
YTLitePlus uses YTLite as a base instead of uYou and adds extra stuff like ReturnYoutubeDislike and iSponsorBlock. It's for people who want something that's less cluttered with tabs or added overlay like a uYou tab or added stuff on top of the player, etc.

It's made by this guy: https://github.com/Balackburn/YTLitePlus

**Comment by ArianaMinajj** [comment]
Hi there,

I wasn't previously aware of YTLitePlus and I've now added it into the repo. Your contribution is appreciated!
