### ISSUE TITLE
Spotilife - spotify connect seeking disabled

### ISSUE THREAD

**Issue by Vetrix68** [swaggyP36000/TrollStore-IPAs#110]
Does anyone else experience the seeking bar being disabled if using Spotify Connect?

**Comment by Vetrix68** [comment]
Sure, iPhone 12, iOS 16.6.1 but it also happened on 15.2 if I used new releases. I currently use Spotilife 8.8.12 and everything works, but if I update to any new one, the seeking bar is grayed out.

**Comment by ArianaMinajj** [comment]
As I previously asked, can you please provide me your Trollstore version?

**Comment by ArianaMinajj** [comment]
A user *(not in this repo)* encountered the exact same problem, and they resolved it by installing through TS. Have you given "Spotify Deluxe" a shot? It's also using the latest Spotify version.

**Comment by Vetrix68** [comment]
I will try that later today and post an update

**Comment by ArianaMinajj** [comment]
It's been 24 hours. Could you please provide me with an update?

**Comment by Vetrix68** [comment]
Sorry, deluxe changes nothing. It goes gray as soon as I connect to Denon using Spotify Connect.![image](https://github.com/swaggyP36000/TrollStore-IPAs/assets/75122363/1d5ae527-ada0-4523-b130-d193b9b66e54)

**Comment by ArianaMinajj** [comment]
Could possibly be linked to the Spotilife tweak being outdated or due to your iOS version.. *(premium is fully functional on iOS 15-15.5)*

I'm not certain if it's a bug nor can I provide a definitive solution but I would recommend staying on 8.8.12

**Comment by Vetrix68** [comment]
It is probably outdated with the latest Spotify versions. The same behavior occurred on 15.2.

**Comment by ArianaMinajj** [comment]
Sorry I overlooked the fact that you had mentioned that earlier and I think this might be a premium feature similar to Spotify Jam, which can't be unlocked or used..?

Regardless, I'm afraid there doesn't seem to be a solution to this issue at present..

**Comment by 3rdQuasar** [comment]
Try it with a new account
