### ISSUE TITLE
[Request] Working whatsapp ipa For Ipad

### ISSUE THREAD

**Issue by Genxster1998** [swaggyP36000/TrollStore-IPAs#115]
If only you could get hand on whatsapp ipa for ipad (beta builds) . watusi is not working , i tried like 5 rev. , it can not login at all. Also watusi is just too much ad filled app. I don't have such taste. 
PS: just tested original decrypted ipa for iphone , it is not supported there too , although it does have ipad ui in there , but just stuck at loading messaging alert box , and login failed.So no app for ipad users at all. The pathetic testflight remains always closed. Neither a user of thousands there to post a decrypted test build ipa(they are decrypted already ig).
Thanks & Regards.

**Comment by ArianaMinajj** [comment]
Hello,

Unfortunately, I'm unable to assist you with that request, as WhatsApp/Watusi is not compatible with iPads, unless you have the TestFlight versions, which I don't have access to.

Although you didn't mention your specific iPadOS and TrollStore versions, I still have linked two IPA files that may be compatible with iPadOS. I kindly request you to test both of them:

- **[WhatsApp for iPad](https://gofile.io/d/t1muOp)**

If neither of these options works for you, I regret to inform you that I will have to close this issue, as currently I believe there is no way to obtain WhatsApp for iPad unless you are part of the beta user program..

**Comment by Genxster1998** [comment]
Thanks for quick reply, I am using TS2 and ipados 16.1.1 and it's really astonishing for me to know , nobody has access to test flight builds who can upload it .I requested in several forums . Nobody has it, I wonder who are filling roles of testing there.
Thanks again for quick reply.

**Comment by ArianaMinajj** [comment]
I'm sorry to hear that. Have you tried the IPA files that I uploaded?

**Comment by Genxster1998** [comment]
> I'm sorry to hear that. Have you tried the IPA files that I uploaded?

Yeah , it kinda works but i hate ads in a daily messenger app. Will look into similar stock ipa version or is it have some tweaks ?

**Comment by ArianaMinajj** [comment]
I'm unsure if it includes an tweak that supports iPad since I'm unable to test it cause I don't have one and that version crash on start for me.

Consequently, even though it might not fully meet your expectations, I'll mark this issue as resolved. (for now)

**Comment by BerlinSnoop** [comment]
I am using the given WA beta IPA on my iPad 12.9 gen2 with IOS 17.0 and PaleRa1n. Yes, Watusi is installed as a tweak (at least using Sileo) and normally it gives you advertising if you don't pay a license.

**Comment by ArianaMinajj** [comment]
You're welcome! Could you tell me which of the two files I uploaded was used? Also, could you share the installation process you followed?

**Comment by Genxster1998** [comment]
I have used the smaller sized ipa from your link using TS2. @BerlinSnoop can you share decrypted official  WhatsApp beta ipa . The Given link by @ArianaMinajj is already watusi modified ipa.

**Comment by BerlinSnoop** [comment]
@Genxster1998  I am sorry. I have no other beta. I have used too the same smaller ipa given by @ArianaMinajj and I am using always the watusi tweak (I have not recocnized that the IPA contains too the watusi tweak).

**Comment by BerlinSnoop** [comment]
> You're welcome! Could you tell me which of the two files I uploaded was used? Also, could you share the installation process you followed?

The smaller IPA

**Comment by ArianaMinajj** [comment]
Then I'll upload the smaller-sized version in the repo. Hope this version will work for everyone..

**Comment by BerlinSnoop** [comment]
Sorry again. I have doublechecked the Ipas size in Trollstore. I have used the 165mb version (*ipad_2).

**Comment by ArianaMinajj** [comment]
Do you think you could give the smaller-sized ipa a try? Thanks in advance!

**Comment by BerlinSnoop** [comment]
Ok, I will try it. But let me some time. I have to handle the watusi settings.

**Comment by ArianaMinajj** [comment]
Update?

**Comment by Genxster1998** [comment]
> Update?

I have tested both beta build ipas .One which is smaller in size is Watusi Modified IPA another is uncompressed stock unmodified ipa. Both are working fine . Once i recompressed official ipa , size came down to approx 65MBs. Thanks again. please look into if you get newer version . this one looks like to be 2months old build.

**Comment by ArianaMinajj** [comment]
Thanks, I'll upload a newer version here if I find one

**Comment by maluueu** [comment]
Can you please upload the beta build again? Thank you

**Comment by ArianaMinajj** [comment]
> Can you please upload the beta build again? Thank you

Hello, I have updated the download link with the same file I uploaded previously.

**Comment by maluueu** [comment]
> > Can you please upload the beta build again? Thank you
> 
> Hello, I have updated the download link with the same file I uploaded previously.

I cannot thank you enough <3
Do you by chance, also have the original untouched beta IPA? This one contains Watusi. Nevertheless, thank you very much :)

**Comment by ArianaMinajj** [comment]
**[This](https://gofile.io/d/E06k25)** one is untouched I believe, can you give it a try?

**Comment by Genxster1998** [comment]
The Last one version shared here is expired today. @ArianaMinajj can you get me a new one pls.

**Comment by ArianaMinajj** [comment]
Sure, here's another **[link](https://gofile.io/d/HEq93M)**

**Comment by maluueu** [comment]
@ArianaMinajj is this the most recent TestFlight IPA you have?

**Comment by ArianaMinajj** [comment]
Yes but this is not from me, it's sourced from this **[telegram channel](https://t.me/AppleTesters)**. You may find it beneficial to follow for any future updates.

**Comment by Genxster1998** [comment]
@ArianaMinajj  I was talking about WhatsApp version not Link . This version is expired and need to be updated.
Btw Thanks for replying though!

**Comment by Genxster1998** [comment]
@maluueu Any update on this. This forced version stop receiving updates 2 months ago.
Regards

**Comment by maluueu** [comment]
> @maluueu Any update on this. This forced version stopped receiving updates 2 months ago. Regards

Sadly no. I don't have any update. Stopped working for me too. I don't event remember how I removed the Test flight flag from the IPA.
