### ISSUE TITLE
All VPN apps not installing VPN profile

### ISSUE THREAD

**Issue by upup666** [swaggyP36000/TrollStore-IPAs#119]
I tried VPN ero and some other VPN, I Installing them through Sideloadly, and when Im openning them, they not installing VPN profile like apps from the appstore.

How to use it correctly?

**Comment by ArianaMinajj** [comment]
Hello,

In order to install a VPN profile you need the right cert. entitlement or TrollStore.

**Comment by upup666** [comment]
> Hello,
> 
> In order to install a VPN profile you need the right cert. entitlement or TrollStore.

I have a developer cert, it wont work?

**Comment by ArianaMinajj** [comment]
It is important to determine if your current certificate supports VPN. To get a quick understanding of the contents of yours, you can visit the following **[website](https://check-p12.applep12.com)**. *That link may not be functional*
