### ISSUE TITLE
[Question] Esign and others

### ISSUE THREAD

**Issue by ctrlcmdshft** [swaggyP36000/TrollStore-IPAs#121]
Will you be bringing back support for esign and the others, newer devices/os version can't use trollstore

**Comment by ctrlcmdshft** [comment]
To me doesn't make sense dropping esign support as trollstore is great for older devices and lower iOS versions. Esp since most signing services still recommend esign or gbox

**Comment by thexYeti** [comment]
@ArianaMinajj  is esign still unsupported? 

i’m only asking because trollapps often gives me an error and finding a specific ipa in github directly can be a pain

**Comment by ArianaMinajj** [comment]
Hello,

ESign support was re-implemented two months ago.. I'm unsure how you missed that?

**Comment by thexYeti** [comment]
sorry, i am unsure now too. it seems there was still somehow the old repo buffered in my esign. 
it works very well now after re-adding. 

thanks for your answer and sorry for tagging you unnecessarily

**Comment by ctrlcmdshft** [comment]
I want to thank you for adding back ESign support

**Comment by ArianaMinajj** [comment]
I appreciate that, the credit really goes to the other members of the repository. I also use Esign so I agree, it's quite convenient.
