### ISSUE TITLE
Cannot install TikTokLRDCracked with Sideloadly

### ISSUE THREAD

**Issue by upup666** [swaggyP36000/TrollStore-IPAs#125]
Having this issue via Sideloadly

There was an issue during installation: 0: APIInternalError (Error Domain=IXErrorDomain Code=2 "Failed to create app extension placeholder for /var/mobile/tmp/ExtractedApps/temp.Qkdzpb/Payload/TikTok.app/PlugIns/AwemeNotificationService.appex" UserInfo={NSLocalizedFailureReason=Failed to create promise., NSLocalizedDescription=Failed to create app extension placeholder for /var/mobile/tmp/ExtractedApps/temp.Qkdzpb/Payload/TikTok.app/PlugIns/AwemeNotificationService.appex, FunctionName=+[IXPlaceholder _placeholderForBundle:client:withParent:installType:metadata:placeholderType:mayBeDeltaPackage:error:], SourceFileLine=859, NSUnderlyingError=0xab0e203c0 {Error Domain=IXErrorDomain Code=13 "Failed to get bundle ID from /var/mobile/tmp/ExtractedApps/temp.Qkdzpb/Payload/TikTok.app/PlugIns/AwemeNotificationService.appex" UserInfo={NSLocalizedDescription=Failed to get bundle ID from /var/mobile/tmp/ExtractedApps/temp.Qkdzpb/Payload/TikTok.app/PlugIns/AwemeNotificationService.appex, FunctionName=+[IXPlaceholder _placeholderForBundle:client:withParent:installType:metadata:placeholderType:mayBeDeltaPackage:error:], SourceFileLine=676, NSLocalizedFailureReason=Missing bundle ID.}}})

**Comment by ArianaMinajj** [comment]
Hello, I'm experiencing the same issue with noir and I haven't found any solution online. It seems to be a well-known problem and the TikTok ipa is exclusive to TrollStore anyway.

Go ahead and give it a try with ESign and see what happens!

**Comment by upup666** [comment]
Tried Esign still not working
