### ISSUE TITLE
TikTokLRDCracked not working, installed through Esign and Sideloadly

### ISSUE THREAD

**Issue by upup666** [swaggyP36000/TrollStore-IPAs#126]
New Updated TikTokLRDCracked - (TikTok base version updated to v32.8.0) not working through Esign or Sideloadly.

**Comment by ArianaMinajj** [comment]
Are you able to read??? You've opened the same issue twice despite me informing you that this IPA is exclusive to TrollStore, pretty much like all the others.. 

If there's another incorrect issue submitted from you next time, I will close it immediately.
