### ISSUE TITLE
[Request] Instagram Nyx + BH

### ISSUE THREAD

**Issue by adhip94** [swaggyP36000/TrollStore-IPAs#127]
Can we have an Instagram IPA which has both Nyx and InstaBH as well?

**Comment by ArianaMinajj** [comment]
Hello,

Sure thing! I will upload this in the next release within a few minutes.

**Comment by GrPK** [comment]
Can you please update it to 317 as well? Thanks!

**Comment by adhip94** [comment]
@ArianaMinajj could you ipload instanyxbh with the latest instgaram and nyx versions? Also could you keep updating this everytime you do an instagram release?

**Comment by sarwarsoran04-coder** [comment]
aa
