### ISSUE TITLE
All the tweaked instagram don't show notifications and manual 'seen' doesn't work 

### ISSUE THREAD

**Issue by zzziggyy** [swaggyP36000/TrollStore-IPAs#131]
I tried tens of versions of tweaked instagram - bh, rocket, lrd, cracked, etc in different builds.. but they all don't have notifications as well as in messages, once you open an unread dm, it's automatically seen, regardless the anonymous option being on..
Am I the only one experiencing this?

**Comment by ArianaMinajj** [comment]
Hello,

This is a known issue with no potential solution, as notifications randomly appear and disappear on my end.

Temporary fix for that is to rebuild icon cache with TrollStore.

I suggest using InstarocketBH for the manual seen option, as the BH option appears to be more reliable than the one from Rocket, which seems to not be working.

**Comment by zzziggyy** [comment]
I've been using Rocket for a very long time and have been very satisfied with it.. Up until I decided to try the other ones because of a bug that was annoying me.. and since then all of the other builds started acting up (incl. rocket)

**Comment by ArianaMinajj** [comment]
Could you please give what I've mentioned above a try?

**Comment by zzziggyy** [comment]
Yeah, yeah.. I have tried rebuilding icon cache and allowing notifications when prompted after first open, multiple times before writing this..

**Comment by ArianaMinajj** [comment]
Did that work? Do message notifications appear? 

If not, attempt installing Instagram from the AppStore and check if notifications are functioning. If they are working, force install rocket through TrollStore; if they are not working, you will need Filza.

**Comment by zzziggyy** [comment]
Actually was thinking of this! About to try it now. About Filza - never got to use it and am completely in the dark there

**Comment by ArianaMinajj** [comment]
Please keep me updated! The Filza method can be quite unreliable and irreversible if you don't know what you're doing so it might be best to consider moving on from it.

**Comment by zzziggyy** [comment]
That's why I mentioned it, because I don't feel confident using it. Just tried the force install method - both with rocket and bh; didn't work unfortunately

**Comment by ArianaMinajj** [comment]
The manual seen on BH tweak is working. However, the notification issue remains unresolved as I've mentioned previously.  *(I am unable to fix that)*

I will keep you updated on any potential solutions or workaround methods in the future!

**Comment by zzziggyy** [comment]
Thanks a lot! Appreciate it

**Comment by rznkn** [comment]
Looked into notifications in my custom MessengerLSN and InstaRocketLRD adventures, and the proper way to fix this is through setting app entitlements via trollsign. Original Instagram app entitlements [here](https://throwbin.in/ris0hx). 

Some IPAs however do not have the PlugIns "InstagramNotificationExtension" and "InstagramNotificationContentExtension", which entitlements can't fix. To fix this, you need to extract dylibs and bundles, and inject them to a fresh IPA.
