### ISSUE TITLE
Plus for Instagram cracked

### ISSUE THREAD

**Issue by F1orian** [swaggyP36000/TrollStore-IPAs#134]
Would you be able to provide this?
The Authentication Server for Plus for instagram recently went down and since then the Tweak is unusable even with a license.

In the Version with Rocket, Rocket interfered quite a bit with the settings from Plus...

**Comment by ArianaMinajj** [comment]
Hello,

Sorry but I’m not sure to understand? Would you like the latest version of Instagram with rocket cracked and Plus?

**Comment by F1orian** [comment]
Hello,I would like the latest compatible Version with just Plus cracked, as I prefer that tweak over Rocket and the two tweaks interfere in the combined IPAAm 11.01.2024 um 17:30 schrieb Ariana ***@***.***>:﻿
Hello,
Sorry but I’m not sure to understand? Would you like the latest version of Instagram with rocket cracked and Plus?

**Comment by ArianaMinajj** [comment]
Certainly, I will see what I can do about it!

**Comment by ArianaMinajj** [comment]
I made an ipa for you as requested: InstaPlus (Cracked)

**[InstagramPlus-v313.0.2-2.5.0.ipa](https://gofile.io/d/uzUCeN)**

Note that this is absolutely unusable and unstable.. At this point, I can only suggest using another modified Instagram version from the repository.

**Comment by ArianaMinajj** [comment]
Oh I’m sorry! I wasn't aware of that.. I'll surely take care of it!

**Comment by ArianaMinajj** [comment]
I've created the same IPA on Instagram version 245.0, but it's even worse when I tested it.

**[InstagramPlus-v245.0-2.5.0.ipa](https://gofile.io/d/IcoW0b)**

**Comment by ArianaMinajj** [comment]
You can also try **[that version](https://ipalibrary.me/instagram-plus/)** *(crash on my end)*

**Comment by F1orian** [comment]
Thanks! But it strangely also doesn't work on my end. The app starts and the tweak loads, but changes from the tweak don't apply at all...
