### ISSUE TITLE
DolphinIOS with JIT enabler

### ISSUE THREAD

**Issue by c12n** [swaggyP36000/TrollStore-IPAs#136]
Can you upload dolphinios with jit enabler in it for ts?

**Comment by ArianaMinajj** [comment]
Hello, 

I'm not sure how to do that but I'll see what I can do!

**Comment by c12n** [comment]
Inject this into dolphinios 

https://github.com/Rednick16/TrollStoreJitEnabler

**Comment by ArianaMinajj** [comment]
Here’s the ipa you requested, please let me know if that works fine!

**[DolphiniOS-TrollStoreJitEnabler-3.2.1-213.ipa](https://gofile.io/d/WK7aX1)**

**Comment by c12n** [comment]
Getting an error on iOS 17.0 

Error application is sandboxed 

My device is on 17.0 and didn't use delayota and it's a14

**Comment by ArianaMinajj** [comment]
Could you please try the two versions above?
