### ISSUE TITLE
InstagramLRDCracked: License popup

### ISSUE THREAD

**Issue by SakethKanchi** [swaggyP36000/TrollStore-IPAs#137]
Instagram LRD Cracked started showing this pop up. 

![image](https://github.com/swaggyP36000/TrollStore-IPAs/assets/70198692/fdff18f0-8a5b-4dde-af5b-84a6986af60f)

**Comment by ArianaMinajj** [comment]
Hello,

Can you please send me the ipa you installed so I can reproduce?

**Comment by SakethKanchi** [comment]
> Hello,
> 
> Can you please send me the ipa you installed so I can reproduce?

https://github.com/swaggyP36000/TrollStore-IPAs/releases/download/01-07-2024/InstagramLRDCracked-2.5-312.0.1.ipa

**Comment by SakethKanchi** [comment]
Try adding a second account. I think the issue popped up after doing that.

**Comment by ArianaMinajj** [comment]
Could you test this IPA and add a second account? Does the license popup still show up?

**[Insta LRD 2.5-312.01](https://gofile.io/d/BYdXZQ)**

**Comment by SakethKanchi** [comment]
> Could you test this IPA and add a second account? Does the license popup still show up?
> 
> **[Insta LRD 2.5-312.0.1](https://gofile.io/d/BYdXZQ)**

This ipa seems to be working fine

**Comment by ArianaMinajj** [comment]
I encountered the same problem when I reproduced, which is strange because I remember testing that ipa before posting it and the crack worked..

I will post this one tomorrow and if the crack causes any issues again I’m afraid I’ll have to remove it.

**Comment by SakethKanchi** [comment]
![image](https://github.com/swaggyP36000/TrollStore-IPAs/assets/70198692/ce84b75d-f5a1-480e-ac00-3090c51becce)

The error is back again.

**Comment by ArianaMinajj** [comment]
I'll delete it.

**Comment by SakethKanchi** [comment]
> I'll delete it.

Wait wait. I haven't updated it since the last time. I'll try out the latest update and then come back to this issue if i get it again.

**Comment by ArianaMinajj** [comment]
Are you using TrollStore? Everything is working perfectly for me so I'm not sure what's going on your end?

**Comment by SakethKanchi** [comment]
> Are you using TrollStore? Everything is working perfectly for me so I'm not sure what's going on your end?

Yeah I'm using trollstore. And i've tried the LRD+BH or LRD+Nyx or LRD+Rocket. They are working fine. 
Device Details:
- iOS 17 iPhone 14 PM
- TrollStore 2.01.12

**Comment by ArianaMinajj** [comment]
Thank you, I will definitely be deleting this version as it has caused the same issue twice.

**Comment by SakethKanchi** [comment]
> Thank you, I will definitely be deleting this version as it has caused the same issue twice.

I don't think it's the ipa's fault. I think it is the problem of my device. If the same issue arises for other people then you can delete the ipa. Thanks for the ipa tho really helped me out a lot
