### ISSUE TITLE
duolingo crack working

### ISSUE THREAD

**Issue by vjrmy** [swaggyP36000/TrollStore-IPAs#138]
the newest version of duolingo cracked that working https://t.me/dvccrackapp/431

**Comment by ArianaMinajj** [comment]
Hello,

I've tested this IPA and not only are none of the premium features working *(cannot click on any of them)*, but its injected dynamic libraries are a complete mess. Therefore, I won't be posting that.

**Comment by vjrmy** [comment]
really? i’ve tested on iphone 6s v15.7.8 trollstore. its worked, i sign in using email and on telegram it say to sign in using gmail

**Comment by ArianaMinajj** [comment]
I tried it on iOS 17.0 using TrollStore 2.0.11

The cracked Duolingo version that always works for me is the one provided by iOSGods which necessitates the use of Sideloadly. *(I removed it from the repo)*

Should that IPA file be effective for others, they're welcome to download it from the link you've posted! I have doubts about the reliability of that Telegram channel. Additionally, their branding is all over the Duolingo app, which I find intrusive. 

Thank you for your contribution anyway!

**Comment by DimaSheiko** [comment]
> I tried it on iOS 17.0 using TrollStore 2.0.11
> 
> The cracked Duolingo version that always works for me is the one provided by iOSGods which necessitates the use of Sideloadly. _(I removed it from the repo)_
> 
> Should that IPA file be effective for others, they're welcome to download it from the link you've posted! I have doubts about the reliability of that Telegram channel. Additionally, their branding is all over the Duolingo app, which I find intrusive.
> 
> Thank you for your contribution anyway!

Hi, I would like to know if it is possible to install Duolingo from iosgods with the esign app. I have ios 17.3 and I don't have Sideloadly

**Comment by ArianaMinajj** [comment]
> > I tried it on iOS 17.0 using TrollStore 2.0.11
> 
> > 
> 
> > The cracked Duolingo version that always works for me is the one provided by iOSGods which necessitates the use of Sideloadly. _(I removed it from the repo)_
> 
> > 
> 
> > Should that IPA file be effective for others, they're welcome to download it from the link you've posted! I have doubts about the reliability of that Telegram channel. Additionally, their branding is all over the Duolingo app, which I find intrusive.
> 
> > 
> 
> > Thank you for your contribution anyway!
> 
> 
> 
> Hi, I would like to know if it is possible to install Duolingo from iosgods with the esign app. I have ios 17.3 and I don't have Sideloadly

Hello,

The iOSGod Duolingo version is currently only compatible with Sideloadly, but feel free to try signing with ESign to see if it works.
