### ISSUE TITLE
Is YTKillerPlus Cracked safe to use?

### ISSUE THREAD

**Issue by f1r3lohaz** [swaggyP36000/TrollStore-IPAs#140]
Is YTKillerPlus safe to use? Saw the crack version but it kinda contains some weird containers(iCloid.jko.jko2) and also have accessible keychain to com.apple.token which makes me feel unsafe lol.

**Comment by ArianaMinajj** [comment]
Hello,

I share your concern regarding YTKillerPlus, Instagram LRD, and TikTok LRD Cracked versions. *(They are from the same uploader)*

It's noticeable that all three have the same containers and accessible keychain, which is indeed questionable. I've reached out on Reddit twice and this [telegram channel](https://t.me/iOS_Randy420) *(I asked the exact same question before you opened that issue)* for clarification, even directly to the uploader of these IPAs, and received consistent feedback that these characteristics are a result of signing the app with ESign. 

Furthermore, I've run multiple tests on these files and haven't found anything overtly suspicious?

For reference, you might find this discussion helpful: **[How can I update a TS ipa myself?](https://www.reddit.com/r/jailbreak/comments/18l38uv/question_how_can_i_update_a_trollstore_ipa_myself/) + [Is it safe to install an IPA that has com.apple.token listed under keychain groups?](https://www.reddit.com/r/Trollstore/comments/zl30n2/is_it_safe_to_install_an_ipa_that_has/)**

**Comment by ArianaMinajj** [comment]
It is actually generated by ESign, as I've tested it. You will notice the keychain before installation with TS.

Feel free to try it out for yourself!
