### ISSUE TITLE
Wrong InstagramNyx version scheme

### ISSUE THREAD

**Issue by Schrotty74** [swaggyP36000/TrollStore-IPAs#142]
This version have not 1.2.0. Its show 1.1.8. Mease fix it.

![IMG_0757](https://github.com/swaggyP36000/TrollStore-IPAs/assets/25227541/7229e558-f28c-4947-8613-cab9c23fa547)
![IMG_0756](https://github.com/swaggyP36000/TrollStore-IPAs/assets/25227541/5c80a057-51ae-4bc8-9326-114d9e5d5f38)

**Comment by ArianaMinajj** [comment]
Hello,

I apologize for the inconvenience, I will fix it as soon as possible!
