### ISSUE TITLE
vendetta not working extension

### ISSUE THREAD

**Issue by vjrmy** [swaggyP36000/TrollStore-IPAs#143]
app installed successful but extension like safari to discord not working on ios 15.8 using trollstore 2.0.11
![9C64E0FA-0E2A-4895-B30F-9F5F30D4E3AB](https://github.com/swaggyP36000/TrollStore-IPAs/assets/88963059/2dc4883b-91b8-44d5-9027-73d03ca48137)

**Comment by ArianaMinajj** [comment]
Hello,

The warning message you're seeing is unrelated to vendetta extensions.

There's a known compatibility issue with Safari extensions when using TrollStore which has already been addressed **[here](https://github.com/swaggyP36000/TrollStore-IPAs/issues/68)**.

If this causes you concern, it may be best to revert to the previous version of vendetta.
