### ISSUE TITLE
[Request] InstaRocketLRD

### ISSUE THREAD

**Issue by UrbrotherinLaw** [swaggyP36000/TrollStore-IPAs#145]
Can you provide us with InstagramLRDCracked injected with RocketCracked . Thank you so much
Also there’s a bug that make instagramLRD freeze’s for 10sec after opening the app maybe a fix for that also?

**Comment by ArianaMinajj** [comment]
Hello,

I will make an IPA for you tomorrow with both LRD and rocket so you can tell me if that combination works or not.

The freezing bug is a known issue and has already been mentioned and there's not fix for that, sorry.

**Comment by rznkn** [comment]
I've been looking at this myself, it seems injecting the decrypted LRD IPA from #137 with extracted RocketCracked dylibs and bundles is feasible, but I can't get the app entitlements to properly work -- safari does not open Instagram, and the share sheet says 'you're not logged in to instagram'. other than that, it works. 

try this one: [Instagram lrd-2.5, rocket-19k](https://gofile.io/d/DSGvM8)

**Comment by ArianaMinajj** [comment]
Thank you for this, although it seems that there's an issue with your ipa where LRD isn’t cracked. *(The license pop-up appear, using TrollStore.)*

The "cracked" InstagramLRD is highly unstable in the first place; I'm seriously considering removing it from the repository.

**Comment by UrbrotherinLaw** [comment]
> I've been looking at this myself, it seems injecting the decrypted LRD IPA from #137 with extracted RocketCracked dylibs and bundles is feasible, but I can't get the app entitlements to properly work -- safari does not open Instagram, and the share sheet says 'you're not logged in to instagram'. other than that, it works. I've given up on the app entitlements as I believe LRD is being activated by a developer certificate, which is erased when I try to fix app entitlements.
> 
> I believe the freezing issue is LRD checking for a license -- which the crack provides.
> 
> try this one: [Instagram lrd-2.5, rocket-19k](https://gofile.io/d/DSGvM8)

![IMG_6871](https://github.com/swaggyP36000/TrollStore-IPAs/assets/156973288/ad909366-e1c3-40e2-ab9b-c67f4c20f59d)

**Comment by UrbrotherinLaw** [comment]
> Thank you for this, although it seems that there's an issue with your ipa where LRD isn’t cracked. _(The license pop-up appear, using TrollStore.)_
> 
> The "cracked" InstagramLRD is highly unstable in the first place; I'm seriously considering removing it from the repository.

Don’t remove it it’s very stable and i think the first 10sec freeze it’s just checking for license but it’s not an issue at all . I just hope you can accomplish this LRDcracked injected with RocketCracked thank you

**Comment by ArianaMinajj** [comment]
Thank you so much!

This is working, I plan to upload your file to the repository tomorrow. Your contribution is greatly appreciated!

**Comment by UrbrotherinLaw** [comment]
Thank you . It worked 👍🏻 please mention that when this 2 tweaks injected the feature in Rocket that let you tap and hold profile picture to Zoom no longer works

**Comment by ArianaMinajj** [comment]
hello @rznkn, do you think you could take a look at **[this request](https://github.com/swaggyP36000/TrollStore-IPAs/issues/147)**?

**Comment by rznkn** [comment]
> May I request an Instagram with Nyx (stable not beta) and LRD injected?

[InstagramLRDNyx-312.0.1-2.5-1.1.8](https://gofile.io/d/nr5pcq)
_Can't test functionality as I don't have a license._

**Comment by ArianaMinajj** [comment]
I will upload it as soon as possible!

Thank you again @rznkn for your time and contribution. It means a lot!

**Comment by ProgramRudra** [comment]
@rznkn Can i get your InstaRocketKillerLRD ipa. I want to install a instagram ipa with Rocket cracked, LRD cracked and Killer Cracked. only problem is that I cant open settings after making my ipa.

**Comment by rznkn** [comment]
> @rznkn Can i get your InstaRocketKillerLRD ipa. I want to install a instagram ipa with Rocket cracked, LRD cracked and Killer Cracked. only problem is that I cant open settings after making my ipa.

Sorry, no iNKillerPlus cracked. I have a license.

**Comment by SakethKanchi** [comment]
Is the NyxCracked?

**Comment by rznkn** [comment]
> Is the NyxCracked?

No. No Nyx Cracked.

**Comment by UrbrotherinLaw** [comment]
> I've been looking at this myself, it seems injecting the decrypted LRD IPA from #137 with extracted RocketCracked dylibs and bundles is feasible, but I can't get the app entitlements to properly work -- safari does not open Instagram, and the share sheet says 'you're not logged in to instagram'. other than that, it works. I've given up on the app entitlements as I believe LRD is being activated by a developer certificate, which is erased when I try to fix app entitlements.
> 
> I believe the freezing issue is LRD checking for a license -- which the crack provides.
> 
> try this one: [Instagram lrd-2.5, rocket-19k](https://gofile.io/d/DSGvM8)

Hey, sorry can i ask how do you crack tweaks like LRD 
How do you edit or decompile dylib files ?

**Comment by UrbrotherinLaw** [comment]
> I've been looking at this myself, it seems injecting the decrypted LRD IPA from #137 with extracted RocketCracked dylibs and bundles is feasible, but I can't get the app entitlements to properly work -- safari does not open Instagram, and the share sheet says 'you're not logged in to instagram'. other than that, it works. I've given up on the app entitlements as I believe LRD is being activated by a developer certificate, which is erased when I try to fix app entitlements.
> 
> I believe the freezing issue is LRD checking for a license -- which the crack provides.
> 
> try this one: [Instagram lrd-2.5, rocket-19k](https://gofile.io/d/DSGvM8)

Can you show me how do you do that? Cracking tweaks and injecting what tools do you use ?
