### ISSUE TITLE
[Request] (FaceLab / FaceApp / Web Video Cast) Cracked

### ISSUE THREAD

**Issue by UrbrotherinLaw** [swaggyP36000/TrollStore-IPAs#146]
Please can you provide a cracked tweaks for this apps

FaceApp : 
https://apps.apple.com/ma/app/faceapp-perfect-face-editor/id1180884341

FaceLab : 
https://apps.apple.com/ma/app/facelab-face-editor-ai-photo/id1530776865

Web Video Cast : 
https://apps.apple.com/ma/app/web-video-cast-browser-to-tv/id1400866497

**Comment by ArianaMinajj** [comment]
Hello,

I'll look into this promptly and keep you updated. Your patience in this process is appreciated.

**Comment by ArianaMinajj** [comment]
Edit: Only FaceApp can be cracked with **[desfazara.faceapp.ios.adbk](https://gofile.io/d/A8Y8Sg)** using **[AppsManager](https://github.com/swaggyP36000/TrollStore-IPAs/releases/download/12-01-2023/AppsManager-1.8.4.ipa)**. *(Restore appdata using
this adbk, the file is recognised by AppsManager.)*

**Comment by UrbrotherinLaw** [comment]
> Update: Only FaceApp can be cracked with **[desfazara.faceapp.ios.adbk](https://gofile.io/d/A8Y8Sg)** using **[AppsManager](https://github.com/swaggyP36000/TrollStore-IPAs/releases/download/12-01-2023/AppsManager-1.8.4.ipa)**.
> 
> _(Restore appdata using this adbk, the file is recognised by AppsManager)_

I restore it by AppsManager but still shows no Pro 
How i can do it i installed latest version in App store
Any tutorial how to make it work

**Comment by ArianaMinajj** [comment]
You may want to join the **[iOS Tutorials + App Cracks](https://t.me/iOS_Randy420)** telegram channel where the adbk file originates from. 

There's already a tutorial mentioned there and since I'm not the original creator of that file, you can ask for support there!
