### ISSUE TITLE
[Request] InstaLRDBH

### ISSUE THREAD

**Issue by ImPusher** [swaggyP36000/TrollStore-IPAs#147]
Could you upload Instagram with LRD Cracked + BH? Thanks

**Comment by ArianaMinajj** [comment]
Hello,

I've tried to inject both LRD/BH but no matter what I do it keeps crashing on launch and I'm not sure why..

You may need to seek assistance from somewhere else or wait for another person to handle that request as I'm currently unable to do it, sorry!

**Comment by ImPusher** [comment]
Alright, thx anyways

**Comment by ArianaMinajj** [comment]
I'll keep you updated

**Comment by rznkn** [comment]
Done. Do note that some features of BH do not properly work anymore, as it is designed for 290.1. [InstagramLRDBH-312.0.1-2.5-0.0.1](https://gofile.io/d/kwX511) 

P.S. While making this, I also accidentally made InstagramRocketLRDBH-312.0.1-3.8.19-2.5-0.0.1 [(lmao)](https://gofile.io/d/1ACWAE)

**Comment by ArianaMinajj** [comment]
Thank you so much !!

**Comment by ImPusher** [comment]
Thanks buddy!
