### ISSUE TITLE
Rocket's "Manually Mark Messages Seen" feature is not working

### ISSUE THREAD

**Issue by gniarchos** [swaggyP36000/TrollStore-IPAs#148]
In the latest version of Rocket the mark messages as seen doesn't work. Is there any fix?

**Comment by ArianaMinajj** [comment]
Hello!

This is a known issue, I highly recommend you to use [InstaRocketBH](https://github.com/swaggyP36000/TrollStore-IPAs/releases?q=InstaRocketBH&expanded=true) where the feature is working from BH.
