### ISSUE TITLE
Spotilife Premium Broken

### ISSUE THREAD

**Issue by Infinitay** [swaggyP36000/TrollStore-IPAs#149]
Is anyone else having issues with premium not working on the two latest versions of Spotilife available on this repo?

I've tried both `Spotilife-8.8.96` and `Spotilife-8.8.92`. Initially I was on v8.8.92 but I noticed premium was no longer working and the button appeared on the bottom menu. I install v8.8.96 and the premium button was gone from the menu, but it didn't seem like I had premium because when I played music, it didn't let me skip and it played a suggested song. Furthermore, it seems like #110 was never fixed either because I noticed when using Spotify on my Desktop to play my music onto my phone, it was failing to connect to my phone and kept telling me to restart.

**Comment by ArianaMinajj** [comment]
Hello,

This is a known issue affecting all versions of Spotify beyond 8.6.94.

It seems that Spotify has implemented some changes on the server side to patch premium tweaks in earlier versions. 

**The repository explicitly notes that the only version currently working is Sposilife.**

**Comment by Infinitay** [comment]
Oh I missed it on the README. Thank you for clarifying.

**Comment by Infinitay** [comment]
I downloaded `Sposilife-8.6.42` from https://github.com/swaggyP36000/TrollStore-IPAs/releases/tag/01-02-2024 but the app instantly crashes for me.

iOS 17.0.3 A17, Altstore (installed without app extensions)
