### ISSUE TITLE
SharkForMessenger crashed on opening

### ISSUE THREAD

**Issue by ghmoena** [swaggyP36000/TrollStore-IPAs#15]
Iphone 7p 15.7.1
I tried every version of messenger in this githuub but have the same result which is crashed on opening, not even login screen.

**Comment by swaggyP36000** [comment]
Latest seems to be crashing on TrollStore, so it will definitely be pulled from this repo. The one before that should work tho, I tested that one myself before uploading. They definitely shouldnt _all_ be crashing for you

**Comment by swaggyP36000** [comment]
Note has been added. Hopefully you can get it to work some other way
