### ISSUE TITLE
InstaNyxLRD - LRD not cracked (wrong description) 

### ISSUE THREAD

**Issue by rznkn** [swaggyP36000/TrollStore-IPAs#151]
LRD is not cracked in this tweaked IPA, as the requestor in #145 has both licenses. Also, I used 312.0.1 as it is the last version supported with Nyx Stable 1.1.8. (might've contributed to why you thought it was cracked lol)

**Comment by ArianaMinajj** [comment]
Hello,

Thank you for the clarification, I will change that!

**Comment by rznkn** [comment]
Noticed the commit you made, BundleId.csv now shows the wrong name and doesn't show in TrollApps. InstaLRDNyx, not InstaNyxLRD (Seems i've confused you with the title of this issue. My mistake, sorry bout that!) 

Thanks for maintaining though! :)

**Comment by ArianaMinajj** [comment]
The was fixed 3 hours ago, please restart TrollApps to view the changes.
