### ISSUE TITLE
[Request] Procreate Dreams

### ISSUE THREAD

**Issue by Pranobt** [swaggyP36000/TrollStore-IPAs#154]
Can you please add Procreate Dreams IPA for ipad?

**Comment by ArianaMinajj** [comment]
Hello,

Could you please try **[this ipa](https://gofile.io/d/QaDh8U)** and let me know if it works for you?

**Comment by Pranobt** [comment]
Thank you I will check and update you.

**Comment by Pranobt** [comment]
Working thank you so much

**Comment by ArianaMinajj** [comment]
I will not upload this application because of its platform support, for the latest updates, please check the original **[source](https://iphonecake.com/app_1595520602_.html)**.
