### ISSUE TITLE
[Request] AdGuard Pro

### ISSUE THREAD

**Issue by oatmealcookiec** [swaggyP36000/TrollStore-IPAs#156]
Hi, big thanks for you work.
Can you add AdGuard Pro Adblocker apps?
or tell me a good application for blocking ads, I haven’t found a better adguard
Sincerely.

**Comment by ArianaMinajj** [comment]
Hello,

This is not compatible with TrollStore. For more information, please refer to this **[issue](https://github.com/swaggyP36000/TrollStore-IPAs/issues/68).**

I highly recommend using **[Ghostery](https://apps.apple.com/fr/app/ghostery-privacy-ad-blocker/id1436953057?As an alternative, I have been personally using this for a long time and find it extremely beneficial!

**Comment by ArianaMinajj** [comment]
Hello,

I was mistaken about AdGuard; I apologize for any confusion. After testing I've discovered that it actually work with TrollStore and is now available on the repo. Please check its description for more information. 

Thank you for your understanding and patience.
