### ISSUE TITLE
YouTubeElite 18.02.3 sign error

### ISSUE THREAD

**Issue by andre1808** [swaggyP36000/TrollStore-IPAs#16]
Hi there.
I can't install YouTubeElite 18.02.3 using AltStore. It's running into a sign error - unfortunately I didn't capture it, but it was quite a long error message.

I also find the sources to be quite shady. The telegram channel does not even list an 18.02.3 yet (which afaik used to be the main source?). Going back to uyou+ I guess.

Thanks for your effort!

**Comment by swaggyP36000** [comment]
Unfortunately, signing errors don't have anything to do with the app. Not much to be done about that. You can always try using SideStore, Sideloadly, Scarlet, etc

As for the sources, you can see that every source that I have gotten the IPA from is listed in the Maintainers section in the app description. Elite v18.02.3 is not from the telegram channel.
