### ISSUE TITLE
[Request] Wallcraft Wallpapers

### ISSUE THREAD

**Issue by oatmealcookiec** [swaggyP36000/TrollStore-IPAs#161]
Can you add WallCraft Wallpapers please?

**Comment by ArianaMinajj** [comment]
Hello,

I have just uploaded it!

**Comment by oatmealcookiec** [comment]
Thank. You amazing.

**Comment by DimaSheiko** [comment]
> Hello,
> 
> I have just uploaded it!

You are so fast! Thanks
