### ISSUE TITLE
Why InstagramNYXBH with 1.2.0 NYX was rolledback?

### ISSUE THREAD

**Issue by GrPK** [swaggyP36000/TrollStore-IPAs#162]
As title said. Sorry to open an issue for a question (maybe you have a better discussion channel?)

I wanted to try that clear cache feature in 1.2.0

**Comment by ArianaMinajj** [comment]
Hello,

Instagram base version is prioritised over the Tweak. You may have to wait a few days to receive the most recent Instagram update and Nyx.

I haven't created a discussion channel for this repository due to time constraints.
