### ISSUE TITLE
Quizlet plus not working

### ISSUE THREAD

**Issue by GiggleMonster** [swaggyP36000/TrollStore-IPAs#163]
Quizlet plus doesn’t seem to be working on iPhone 11 iOS 15.6.

![24C7B7B6-D5BC-4352-8E16-7E6DA4074C6B](https://github.com/swaggyP36000/TrollStore-IPAs/assets/104379629/f26bc3eb-5453-436d-b9bf-5fe19433960e)

**Comment by ArianaMinajj** [comment]
Hello,

Could you please provide me with the link to that test so I can reproduce?

**Comment by GiggleMonster** [comment]
> Hello,
> 
> Could you please provide me with the link to that test so I can reproduce?
> 
> Edit: There is a known issue with the tweak where some features remain locked.
> 
> I will update the description to reflect this. Apologies for any inconvenience caused!

If the Quizlet Plus solutions are locked, which features aren't locked?
