### ISSUE TITLE
[Request] Lightroom Premium

### ISSUE THREAD

**Issue by ssivia** [swaggyP36000/TrollStore-IPAs#164]
Can you please add lightroom premium 
Thanks in advance

**Comment by ArianaMinajj** [comment]
Hello,

I have just uploaded it!

**Comment by airaxpro** [comment]
Can we have also the iPad version? (because normal Lightroom will immediately give a pop up reminding to install the Lightroom for iPad and it wouldn’t let proceed) thanks

**Comment by ArianaMinajj** [comment]
Unfortunately, I cannot find the iPad version anywhere.

Note that you have the option to inject Satella into the decrypted iPad version *(if you have one)* and test it out for yourself!

**Comment by KenjiUrban** [comment]
Guys how to I activate the premium features?
