### ISSUE TITLE
Lightroom Premium Usage

### ISSUE THREAD

**Issue by leonardodafishy** [swaggyP36000/TrollStore-IPAs#165]
How do I enable Lightroom's pro features? I've enabled every setting on the Satella thingy, but whenever I try pressing some pro feature's buttons, it always says "Something went wrong".

**Comment by ArianaMinajj** [comment]
Hello,

There's no need for you to activate anything on Satella. Simply select a subscription to unlock Premium. 

If that doesn't work for you, I won't be able to provide support.

**Comment by leonardodafishy** [comment]
> Hello,
> 
> There's no need for you to activate anything on Satella. Simply select a subscription to unlock Premium. 
> 
> If that doesn't work for you, I won't be able to provide support.
> 

Does it need jailbreak?

**Comment by ArianaMinajj** [comment]
TrollStore, that is the primary purpose of this repository. *This might work with ESign too*
