### ISSUE TITLE
Sideloading InstaRocketBH to mac does not work

### ISSUE THREAD

**Issue by LetsUpdate** [swaggyP36000/TrollStore-IPAs#167]
I used Sideloady to install InstaRocketBH to my m1 mac, but it does not open!

**Crash Summary:**

<details>
 <summary>Incident Information</summary>
 
**Incident Identifier:** B26B7C0C-12BD-4A13-9DF6-3F4B3FA18E2D

**CrashReporter Key:** 0EB2C310-DCB5-60E1-BE08-1F42487F51D4

**Hardware Model:** MacBookAir10,1

**Process:** Instagram [29839]

**OS Version:** macOS 14.3 (23D56)

**Date/Time:** 2024-01-28 21:02:37.6513 +0100
</details>

<details>
 <summary>Exception Information</summary>
 
**Exception Type:** EXC_CRASH (SIGABRT)

**Exception Codes:** 0x0000000000000000, 0x0000000000000000

**Termination Reason:** DYLD 1 Library missing
</details>

**Crash Details**

The crash occurred due to a missing library: `/System/Library/PrivateFrameworks/Preferences.framework/Preferences`. The Instagram app tried to reference this library but couldn't find it. The referenced library is expected to be at different paths, but it's not found.

<details>
 <summary>Additional System Information</summary>
 
**Model:** MacBookAir10,1

**Graphics:** Apple M1

**Display:** 2560 x 1600 Retina

**Memory:** 8 GB

**Network:** Wi-Fi (AirPort, en0)

**USB and Thunderbolt devices information.**
</details>

**Note:** The crash seems to be related to the Instagram app's attempt to load the Preferences framework, which is missing. 

Original Crash Report: 
[crashreport.txt](https://github.com/swaggyP36000/TrollStore-IPAs/files/14077609/crashreport.txt)

**Comment by ArianaMinajj** [comment]
Hello,

I'm really confused as to why you're attempting to install an iOS app on a MacOS device. How does that make sense? Am I missing something?

**Comment by LetsUpdate** [comment]
> Hello,
> 
> I'm really confused as to why you're attempting to install an iOS app on a MacOS device. How does that make sense? Am I missing something?

M1 mac's support IOS apps natively 

It was initially possible, but Apple declared, "You can't do that from the next update." However, some features are only available through the app, and I want to use them. Unfortunately, I don't want to install Instagram on my phone because it's too much of a distraction, and I can't resist the temptation.
