### ISSUE TITLE
BHTikTokPlus-33.2.0-2.3 no longer sideloadable with AltStore

### ISSUE THREAD

**Issue by alexdonh** [swaggyP36000/TrollStore-IPAs#174]
I've been able to sideload BHTikTokPlus without problems (only had to repack the ipa with removal of `TikTokBackgroundAssetExtension.appex`). Until today. 

The error I got is:

```
Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.pHeFOF/extracted/App.app/Frameworks/CydiaSubstrate.framework : 0xe8008016 (The executable was signed with invalid entitlements.)
```

which didnt happen in previous versions.

Any thoughts on this?

**Comment by ArianaMinajj** [comment]
Hello,

Please wait for the latest version to be reuploaded. In the meantime, revert to version 33.1.0

**Comment by ArianaMinajj** [comment]
Can you try sideloading this **[ipa](https://gofile.io/d/yte1Rd)**? 

Please note that if that ipa doesn't work for you, there's not much else I can do.

**Comment by alexdonh** [comment]
Not working for me. Even the new one here https://github.com/swaggyP36000/TrollStore-IPAs/releases/tag/02-01-2024
does not work too.

Its a different error message this time

```
Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.Fem5JH/extracted/App.app/Frameworks/libvcn.framework : 0xe8008016 (The executable was signed with invalid entitlements.)
```

**Comment by asdfzxcvbn** [comment]
strage that it ever worked at all with altstore, AltSign doesnt support tiktok's entitlements according to some devs

**Comment by alexdonh** [comment]
> strange that it ever worked at all with altstore, AltSign doesnt support tiktok's entitlements according to some devs

quite the contrary.. i had managed to install BHTikTok by just removing Payload/Extensions/BackgroundAssetExtension.appex and repack the ipa. 

Unfortunately the trick no longer works.

Apparently AltSign doesnt support apple ExtensionKit so not only TikTok but also any other apps using ExtensionKit

**Comment by alexdonh** [comment]
Just wanted to update [this latest update](https://github.com/swaggyP36000/TrollStore-IPAs/releases/tag/02-06-2024) works again! was able to install using AltStore and all works just fine!

**Comment by asdfzxcvbn** [comment]
> Just wanted to update [this latest update](https://github.com/swaggyP36000/TrollStore-IPAs/releases/tag/02-06-2024) works again! was able to install using AltStore and all works just fine!

hmm.. i dont remember changing anything, but great! i did change my decryption method, maybe that had something to do with it? strange

**Comment by swaggyP36000** [comment]
> Just wanted to update [this latest update](https://github.com/swaggyP36000/TrollStore-IPAs/releases/tag/02-06-2024) works again! was able to install using AltStore and all works just fine!

This is a thing with DLTikTok. Unless there's a feature you badly need on either the tweak or in the app, stick to a version that you know works for you. Once you update and you realize the license file is broken, it's a pain in the ass to get it to work again.

**Comment by alexdonh** [comment]
@asdfzxcvbn @ArianaMinajj  it happens again on [latest update](https://github.com/swaggyP36000/TrollStore-IPAs/releases/tag/02-09-2024)

```
Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.oqsnLN/extracted/App.app/Frameworks/CydiaSubstrate.framework : 0xe8008016 (The executable was signed with invalid entitlements.)
```

**Comment by ArianaMinajj** [comment]
Can you please stop pinging me?

**Comment by alexdonh** [comment]
> Can you please stop pinging me?

my apologies i wasnt aware you have nothing to do with any of this.

**Comment by asdfzxcvbn** [comment]
> @asdfzxcvbn it happens again on [latest update](https://github.com/swaggyP36000/TrollStore-IPAs/releases/tag/02-09-2024)
> 
> ```
> Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.oqsnLN/extracted/App.app/Frameworks/CydiaSubstrate.framework : 0xe8008016 (The executable was signed with invalid entitlements.)
> ```

the latest update isnt my IPA, however i'll update it now

if you want the file, then join my telegram (linked in the README)
