### ISSUE TITLE
Issue about Shark for Messenger

### ISSUE THREAD

**Issue by kaloyster** [swaggyP36000/TrollStore-IPAs#18]
No matter what version I use or install, it always crashes. No exceptions.

Choicy enabled or not, it crashes. I really don't know what to do anymore.

Facebook Wolf works though. But for now I'm stuck at 387 version of Messenger just to use Messenger No Ads from Sileo.

**Comment by swaggyP36000** [comment]
Known issue for this to be hit and miss. I upload the ones that work for me personally, but it seems there's no guarantee that it will work for others and I'm not quite sure why
