### ISSUE TITLE
License issue on DLTikTok v33.2.1

### ISSUE THREAD

**Issue by beakwood** [swaggyP36000/TrollStore-IPAs#184]
DLTikTok is showing unlicensed when clicking on DLTiktok in settings. 

I am using serotonin and bootstrap a12+

Is this the reason it's not working?

I do have a license for DLEasy, and it works.

**Comment by ArianaMinajj** [comment]
Hello,

The specific issue could be related to your environment, but I cannot confirm it for certain.

Note that DLTikTok does not support TS natively in the first place, however I have kept it updated as requested due to feedback of it working for some users.

**Comment by swaggyP36000** [comment]
Even I have tried poking around with the license files, etc and can't come up with an answer. And i doubt the dev will just tell you the method to his magic

If you have trouble with DLTikTok, I can suggest using BHTikTok, which effectively does the same things but is free
