### ISSUE TITLE
Remini not working 

### ISSUE THREAD

**Issue by GrmJJ** [swaggyP36000/TrollStore-IPAs#185]
I downloaded Remini and it crashes at first as the description says, when I reopen it, it works fine. The problem is, when I click on continue to set the app and choose preferences it shows a message saying that my device is not connected to Internet. So the app does not crash, but I cannot skip the first screen where you set the app. Does anyone have a solution? I’m new to installing apps like this.

**Comment by ArianaMinajj** [comment]
Hello,

This is a known issue with Remini where the only "fix" for that is to force install the TrollStore version over the one from the AppStore.
