### ISSUE TITLE
can't install the normal snapchat from appstore 

### ISSUE THREAD

**Issue by AGoodNub** [swaggyP36000/TrollStore-IPAs#187]
so I read in the Filza description that you need to delete certain files but I can't seem to find them can I get some help regarding that? and what should I do in the future to not run into this issue? what can I change in trollstore apps to not get this ever again?

**Comment by ArianaMinajj** [comment]
Hello,

Thank you for reaching out with your issue and sorry for the delay! Here's what worked for me:

1. **Reinstall the Problematic App via TrollStore**

2. **Check the Metadata Identifier**: After reinstalling use either TS itself or Filza to identify the app's MetadataIdentifier. *(Needed to locate and remove the correct files)*

3. **Uninstall the App**

4. **Locate and Delete Specific Folders Using Filza**:
   - Navigate to `/var/mobile/Containers/Data/Application` using Filza.
   - Manually scroll through the folders. You're looking for folders that contain the same MetadataIdentifier noted from step 2!! *(Avoid using the search function as it might not reveal all relevant folders)* Delete them.

5. **Reinstall the app from the App Store**

*(If this solution doesn't work, the issue likely stems from **remaining files or folders that were not deleted and I will not offer further support.**)*

*(If you're not comfortable or familiar with using Filza and navigating system files, **please avoid attempting this solution.** **Deleting the wrong files or folders can lead to irreversible damage to your device and I am not responsible**.)*

**Comment by swaggyP36000** [comment]
This seems to be more of a TrollStore issue, not an app issue. Please go to Opa334's trollstore repo and make this issue there.

**Comment by AGoodNub** [comment]
@ArianaMinajj i did that and it kinda worked so ayyy thank you very much and @swaggyP36000 yea it seems that way I will do that.
