### ISSUE TITLE
[Request] LumaFusion

### ISSUE THREAD

**Issue by geeksbolus** [swaggyP36000/TrollStore-IPAs#188]
Can we request for an ipa of LumaFusion? Thanks in advance! :)

**Comment by ArianaMinajj** [comment]
Hello,

**[Here's](https://gofile.io/d/dWPPJu)** the latest version. Please note that I won't be uploading this application since AppCake is already managing **[its updates](https://www.iphonecake.com/app_1062022008_.html)**.
