### ISSUE TITLE
[Request] Alarmy - Alarm Clock & Sleep 

### ISSUE THREAD

**Issue by eggwosh** [swaggyP36000/TrollStore-IPAs#189]
Can I get this app injected with Satella? 

https://apps.apple.com/us/app/alarmy-alarm-clock-sleep/id1163786766

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app and I'll upload it tomorrow!

You can grab the latest version **[here](https://gofile.io/d/3eamOj)** if you do not want to wait.

**Comment by 3rdQuasar** [comment]
have a problem to update YouTubemusic in TrollApps it always says older there is a way to fix?

**Comment by Umesh7616** [comment]
Can i get truecaller premium plzz🙏
