### ISSUE TITLE
Tiktok lrd latest version is not working

### ISSUE THREAD

**Issue by gototheskinny** [swaggyP36000/TrollStore-IPAs#19]
Title

**Comment by swaggyP36000** [comment]
Where does the crash occur?

**Comment by gototheskinny** [comment]
> Where does the crash occur?

When u launch the app for the first time fresh install w/trollstore

**Comment by swaggyP36000** [comment]
This is a known issue. Ideally you'll want to have any other TikTok IPA installed and signed into, then install the LRD IPA over it

Also keep in mind that the settings/download buttons are in the same place as before, just invisible

**Comment by leo04real** [comment]
It's working perfectly fine for me.
