### ISSUE TITLE
[Request] AIDente

### ISSUE THREAD

**Issue by lich4** [swaggyP36000/TrollStore-IPAs#190]
I want to submit my new app for TrollStore,  AlDente charge limiter for iOS
https://github.com/lich4/AlDente

**Comment by swaggyP36000** [comment]
See ReadMe. Tell us a bit about the app so we can include a description

And what everyday use case it has. Normally the apps featured here has some niche/needed feature. What sets yours apart?

Things like that!

**Comment by lich4** [comment]
This app is similar to Mac version AlDente, used to prevent long-time overcharge, which will cause damage to the battery, one can specify the max capacity to stop charging, and min capacity to start charging, and max temparature to stop charging. Once set, the daemon will monitor capacity in background.

**Comment by swaggyP36000** [comment]
This does include English localization right?

**Comment by lich4** [comment]
> This does include English localization right?

Yes, now support Chinese and English, default languge idepend on system launguage is Chinese or not

**Comment by ArianaMinajj** [comment]
Hello,

I have just uploaded it!

**Comment by lich4** [comment]
Thanks

**Comment by thexYeti** [comment]
Love your app @lich4 
I’ve tested it on iOS 17 with trollstore and it works well

**Comment by lich4** [comment]
Hi, My app name changed to ChargeLimiter due to some reason, and now update to version v1.3, please update for me. Thanks.
https://github.com/lich4/ChargeLimiter

**Comment by lich4** [comment]
Hi, ChargeLimiter now update to version v1.4, please update for me. Thanks.
https://github.com/lich4/ChargeLimiter

**Comment by lich4** [comment]
Hi, ChargeLimiter now update to version v1.4.1, please update for me. Thanks.
https://github.com/lich4/ChargeLimiter

**Comment by ArianaMinajj** [comment]
**Please refrain from spamming the same message without checking the repo: App was updated to the most recent version 3 days ago, kindly review before sending further messages, thank you!**
