### ISSUE TITLE
Credits "missing"

### ISSUE THREAD

**Issue by bubbashatz** [swaggyP36000/TrollStore-IPAs#194]
I found several Snapchats the I created and there is no credit to the original cracker Robsmods

**Comment by ArianaMinajj** [comment]
Hello,

It seems you haven't provided much detail so I'm assuming you're referring to Snapchat Wicked Cracked?? 

I gave credit to AppDB since I was uncertain if it was appropriate? I'll change that as soon as possible! Sorry for any inconvenience caused.

**Comment by bubbashatz** [comment]
Yes I’m sorry the the Snapchat ultimate that Hase wicked and Falcon cracked should have the credit to Robsmods please and thank you
