### ISSUE TITLE
[Request] Opal: Screen Time for Focus

### ISSUE THREAD

**Issue by miguelcardoso1204** [swaggyP36000/TrollStore-IPAs#195]
Hi, can you please add Opal? Thank you in advance

[https://apps.apple.com/us/app/opal-screen-time-for-focus/id1497465230](https://apps.apple.com/us/app/opal-screen-time-for-focus/id1497465230)

**Comment by asdfzxcvbn** [comment]
apps that rely on the screen time API don't work for whatever reason, even through trollstore

**Comment by ArianaMinajj** [comment]
Hello,

This app was uploaded earlier this month, sorry for the delay!
