### ISSUE TITLE
Apple Music last.fm scrobbling m player Soor

### ISSUE THREAD

**Issue by gototheskinny** [swaggyP36000/TrollStore-IPAs#2]
You could add [this](https://starfiles.co/bundle_id/me.tanmay.Music) app for people who looks for the best way to scrobbling to last.fm. The official one only scrobbles library added songs not general streams. This is IMO the best way to apple music scrobbling. BTW I love this repo! Thank you.

**Comment by swaggyP36000** [comment]
Tested and it seems to be working fine. Uploaded! Also, thanks. I'm glad this repo is helping a lot of people

**Comment by gototheskinny** [comment]
> Tested and it seems to be working fine. Uploaded! Also, thanks. I'm glad this repo is helping a lot of people

Could you please add info about this app to the description section. Like this app is currently the best free way for scrobbling to last.fm. If they know what this app is for its better. Thank you for adding this app!
