### ISSUE TITLE
Remini app not working after applying fix

### ISSUE THREAD

**Issue by GrmJJ** [swaggyP36000/TrollStore-IPAs#200]
I posted previously about Remini, it crashed and couldn’t even be opened.

I then received an answer saying that I had to install the original app from the AppStore and then force install the tweaked one. 

I did, first with the latest version and then installing the tweaked app, it didn’t work.

then I installed the same version of the app (same as the tweaked one) from the Apple Store. And then forced install the tweaked one.

first time I opened it, it crashed, but then it starting showing the same message, no internet connection.

what I did, I first opened the original app from the Apple Store, I set it and got it working, then proceeded to install the tweaked one, but it didn’t work. 

I didn’t know it was a known problem, but if you have a post where it tells you how to fix it. Could you please share it with me. 

Thanks in advance.

**Comment by ArianaMinajj** [comment]
Hello,

I can't assist you with that if my last solution didn't work, I will replace Remini with another tweaked version anyway.

There are a few other Remini alternatives available on the repo you could explore though!

**Comment by GrmJJ** [comment]
Hello, what options do you recommend?

thanks in advance for helping me.

**Comment by ArianaMinajj** [comment]
Even though Remini excels in enhancing and restoring faces and details, I highly recommend EnhanceFox Pro for improving the quality of images.
