### ISSUE TITLE
[Request] Tweaked version of ScannerPro 

### ISSUE THREAD

**Issue by drsudhanshu524440** [swaggyP36000/TrollStore-IPAs#205]
https://apps.apple.com/us/app/scanner-pro-scan-pdf-documents/id333710667

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app and I'll upload it tomorrow!

You can grab the latest version **[here](https://gofile.io/d/maeJ3x)** if you do not want to wait.
