### ISSUE TITLE
App icons doesn't in ESign in AppStore tab

### ISSUE THREAD

**Issue by davidkh88** [swaggyP36000/TrollStore-IPAs#21]
Added your ESign repo into ESign but all the apps icon doesn't show.
![image](https://user-images.githubusercontent.com/48116275/219839238-132e1fdd-049f-4fb9-baef-282722a08a8c.png)

**Comment by swaggyP36000** [comment]
Yep. It's a bare-bones repo. None of the apps have icons or descriptions. I will tag hieuddo in this issue. They made the repo

**Comment by davidkh88** [comment]
> Yep. It's a bare-bones repo. None of the apps have icons or descriptions. I will tag hieuddo in this issue. They made the repo

Aww okay bro, because previously I usually download the IPAs from your github Release page directly and they're all have app icon when I imported and installed them with ESign so I thought that there might be some issue with the ESign repo that app icon doesn't show as it should have to.

**Comment by hieuddo** [comment]
> Aww okay bro, because previously I usually download the IPAs from your github Release page directly and they're all have app icon when I imported and installed them with ESign so I thought that there might be some issue with the ESign repo that app icon doesn't show as it should have to.

Adding app icon for it to display in ESign is handiwork (which I don't plan to do at this moment). However, you can download the IPAs in ESign, import to App Library, then the app will come with icons normally.

**Comment by swaggyP36000** [comment]
Hieuddo has updated the script to add icons in the repo!

**Comment by davidkh88** [comment]
Yes I saw it, thanks for that.
