### ISSUE TITLE
Hd Flix crashes

### ISSUE THREAD

**Issue by gototheskinny** [swaggyP36000/TrollStore-IPAs#211]
Ios 15.0 trollstore with Xina15 1.1.8
Iphone 12

<details>
  <summary>Screen recording</summary>
  
 https://github.com/swaggyP36000/TrollStore-IPAs/assets/51786709/79055362-de0d-4cc5-8676-1e8fc9a68798

</details>

**Comment by ArianaMinajj** [comment]
Hello,

I have not experienced any crashes with this app on my device, running the latest version of TrollStore on iOS 17.0
