### ISSUE TITLE
Instarocket Cracked

### ISSUE THREAD

**Issue by achesUwU** [swaggyP36000/TrollStore-IPAs#22]
the instarocketcracked still has the banner for full version underneath

**Comment by swaggyP36000** [comment]
Steps to crack:

1. Go to Rocket Settings
2. Click Manage License
3. Click Restore Purchase

It may ask you to identify your device - allow it, and then hit Restore Purchase

4. Profit

**Comment by swaggyP36000** [comment]
It works - https://imgur.com/a/ezI4nBJ

You can also use a lower version to crack it first and then upgrade without uninstalling

**Comment by 0xMargo** [comment]
what version?

**Comment by swaggyP36000** [comment]
> what version?

Any should work in theory. I've been able to get that method to work for every version I've uploaded

**Comment by 0xMargo** [comment]
ok ok 👍🏽 
now work
I install 2.8.0, restore purchase & upgrade to 2.8.3

thank you

**Comment by DimaSheiko** [comment]
> Steps to crack:
> 
> 1. Go to Rocket Settings
> 2. Click Manage License
> 3. Click Restore Purchase
> 
> It may ask you to identify your device - allow it, and then hit Restore Purchase
> 
> 4. Profit

Thank you! Works perfect

**Comment by zokiej** [comment]
Can you upload newest version please?

**Comment by zokiej** [comment]
Can you answear me?

**Comment by DimaSheiko** [comment]
> Can you upload newest version please?

It would be great to get an update because the last cracked version is not working properly.

**Comment by zokiej** [comment]
I dont know why no one doesnt want to reply here…
