### ISSUE TITLE
[Request] Tweaked version of Paper by WeTransfer

### ISSUE THREAD

**Issue by blackhole-voyager** [swaggyP36000/TrollStore-IPAs#224]
https://apps.apple.com/us/app/paper-by-wetransfer/id506003812

**Comment by ArianaMinajj** [comment]
Hello,

I have just uploaded it!

**Comment by DoctorBinh0219** [comment]
Hi. Can you setup app Navitel Navigater VietNam?

**Comment by dswapnil104** [comment]
> Hello,
> 
> I have just uploaded it!

Could you please share tweak deb? (`fyi.zxcvbn.paperunlocked_1.0.2_iphoneos-arm64.deb`) ?

**Comment by DoctorBinh0219** [comment]
I can’t see it
