### ISSUE TITLE
Can you Update base app this tweaks?

### ISSUE THREAD

**Issue by vjrmy** [swaggyP36000/TrollStore-IPAs#23]
according to title... this repo tweaks ipa https://github.com/ipahost?tab=repositories 

for me, i want to try Dragon for Whatsapp if you could update the base app whatsapp. Thanks

**Comment by swaggyP36000** [comment]
I don't make these IPAs myself. You can request this on ipahost's GitHub, or just use Watusi 3 which has all the features Dragon offers on newer WhatsApp versions
