### ISSUE TITLE
[Request] MarineTraffic Pro or Vessel Finder Pro

### ISSUE THREAD

**Issue by 1Tdd** [swaggyP36000/TrollStore-IPAs#230]
Hello! These 2 apps could really help me! If you can add them it would be awesome!
Thank you for the great work!

Marine Traffic: https://apps.apple.com/it/app/marinetraffic-ship-tracking/id563910324

Vessel Finder Pro: 
https://apps.apple.com/it/app/vesselfinder-pro/id608985698

**Comment by 3rdQuasar** [comment]
Just want say thank to Ariana made Duolingo work with TrollStore

**Comment by ArianaMinajj** [comment]
Hello, 

Vessel Finder Pro has been added to the repository but no tweak is currently available for Marine Traffic. 

Please request only one app at a time in the future, thank you!

**Comment by 1Tdd** [comment]
I will! Sorry I didn’t know!
Thank you!
