### ISSUE TITLE
[Crash] Soor

### ISSUE THREAD

**Issue by TheDiscordHistorian** [swaggyP36000/TrollStore-IPAs#24]
The [Soor](https://soor.app) crashes when trying to open after installing. I tried with ESign & Signulous. I’m on an iPhone 13PM, iOS 16.2 Jailed

**Comment by swaggyP36000** [comment]
Noticed this too but hoped it was just a me thing. I guess not, I will remove the latest version as that is the one that causes the crash. I will let you know when the ReadMe is updated with the change

**Comment by swaggyP36000** [comment]
Done! Check the 12-12-2022 release. Hopefully that version will work
