### ISSUE TITLE
[Request] Widgy

### ISSUE THREAD

**Issue by SakethKanchi** [swaggyP36000/TrollStore-IPAs#240]
Premium version of Widgy?
https://apps.apple.com/us/app/widgy-widgets-home-lock-watch/id1524540481

**Comment by ArianaMinajj** [comment]
Hello,

An existing tweak (satella) is already available but the primary features (widgets) of the app appear to be non-functional, so I won't be uploading it, sorry about that!

**Comment by SakethKanchi** [comment]
> Hello,
> 
> An existing tweak (satella) is already available but the primary features (widgets) of the app appear to be non-functional, so I won't be uploading it, sorry about that!

There is another method. It uses App Manager and restores a widgy backup. It works fine but the app is outdated. Here is a link to it. Idk if that will help or not

https://t.me/dpixel/5124
