### ISSUE TITLE
Reddit++ still shows promoted ads

### ISSUE THREAD

**Issue by hisnawi** [swaggyP36000/TrollStore-IPAs#245]
Seems like on latest version 45, promoted ads still show up even when selected for filtered out in the feed options

**Comment by ArianaMinajj** [comment]
Hello,

Please be aware that Reddit++ has not received updates for some time now and is becoming increasingly outdated. I strongly suggest exploring alternative tweaks variants such as ApolloICA or ApolloPatcher.
