### ISSUE TITLE
[Request] Musi

### ISSUE THREAD

**Issue by AlexVN2505** [swaggyP36000/TrollStore-IPAs#249]
Can you please make premium for this app? 
Thank you so much!!!

https://apps.apple.com/us/app/musi-simple-music-streaming/id591560124?l=vi

**Comment by ArianaMinajj** [comment]
Hello,

A tweak (satella) is already available for this app and I'll upload it within the next few hours!

You can download the latest version **[here](https://gofile.io/d/LpGDTK)** if you prefer not to wait.
