### ISSUE TITLE
Dpixel

### ISSUE THREAD

**Issue by Nyxholas** [swaggyP36000/TrollStore-IPAs#25]
Could we stop with the Dpixel uploads unless there is no other choice? Tired of seeing this dudes popup everytime I update an app, especially when the IPA could come from the official source.

**Comment by swaggyP36000** [comment]
I upload the IPA from whoever releases first. If that happens to be DPixel, then that's what it is. If you happen to have sources that upload some of these IPAs faster, I will be happy to look into them too
