### ISSUE TITLE
[Request] Reelsapp

### ISSUE THREAD

**Issue by aliraxa1** [swaggyP36000/TrollStore-IPAs#251]
https://apps.apple.com/ie/app/reelsapp-video-trends/id1609942350

Can you please unlock the premium? Thanks
Regards

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app and I'll upload it tomorrow!

You can download the latest version **[here](https://gofile.io/d/topEzA)** if you prefer not to wait.

**Comment by aliraxa1** [comment]
Thanks
