### ISSUE TITLE
YouTube ipa's

### ISSUE THREAD

**Issue by ctrlcmdshft** [swaggyP36000/TrollStore-IPAs#258]
I see you were hit in the YouTube dcma that went out please don't ignore it, remove all YouTube ipa's so they don't close the repo down for non compliance 

[https://old.reddit.com/r/sideloaded/comments/1b84htd/balackburn_here_ytliteplus_maintainer_just_got_a](https://old.reddit.com/r/sideloaded/comments/1b84htd/balackburn_here_ytliteplus_maintainer_just_got_a)

**Comment by ArianaMinajj** [comment]
We already did
