### ISSUE TITLE
Instagram Rocket v320.0.2 to 322.0.1: Settings missing

### ISSUE THREAD

**Issue by tmpss88loq** [swaggyP36000/TrollStore-IPAs#270]
as title, the newest version.
could you check it?

**Comment by ArianaMinajj** [comment]
Hello,

Apologies for the inconvenience. I will re-upload a fixed version in the upcoming release. 

In the meantime, you can download it **[here](https://gofile.io/d/8fItd3)**.

**Comment by abheizthe** [comment]
> as title, the newest version.
> could you check it?

this happening again, on 322.0.1 - 3.8.23
first update are fixed but, after app crashed (in my case, zoom-in profile picture) and re open the app, rocket setting was missing

overall, tweak still working
i don't know if (maybe) reinstalling the app will fixed it

**Comment by tmpss88loq** [comment]
same problem happens again. i think instagram has been redesigning its setting page, so maybe need to wait for origin author to make a new version tweak.

**Comment by ArianaMinajj** [comment]
This issue has been resolved in the latest version of rocket (3.8.24) and is available in the latest release.
