### ISSUE TITLE
[Request] Vids - Create Reels and Stories

### ISSUE THREAD

**Issue by st-ivan** [swaggyP36000/TrollStore-IPAs#272]
Hey there awesome work! love all you have done for the community. Any chance for this app in ++ mode:

https://apps.apple.com/es/app/vids-crea-reels-y-historias/id1634361180

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app and I'll upload it tomorrow!

You can download the latest version [here](https://gofile.io/d/16pqV4) if you prefer not to wait. 

*(Note that AI style feature is unavailable)*

**Comment by st-ivan** [comment]
OMG. thanks for the quick response.

**Comment by hahahaha93828** [comment]
just a question.

How are you using this because whenever I want to do something it just requires me to pay

Thank you

**Comment by st-ivan** [comment]
yeah.. once you install it and get to the subscribe window, just close the app entirely and open it again, now the app will open with everything unlocked.

**Comment by hahahaha93828** [comment]
thanks

**Comment by Irf90** [comment]
Hello I’m new here … can you please Upload Instagram Nyx cracked ???

**Comment by Irf90** [comment]
Instagram nyx cracked please

**Comment by lover2006mike** [comment]
Network problem. What do I do?
