### ISSUE TITLE
Documents by Readdle Premium 

### ISSUE THREAD

**Issue by Ahmez209** [swaggyP36000/TrollStore-IPAs#275]
Can you please make Documents by Readdle Premium. Latest version if possible please and thank you for all your work.

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app and I'll upload it tomorrow!

You can download the latest version **[here](https://gofile.io/d/5Iahp5)** if you prefer not to wait.

**Comment by Ahmez209** [comment]
Thank you so much ❤️
All the premium features works fine expect VPN but I can use Aloha browser for that. Thank you!

**Comment by dswapnil104** [comment]
@Ahmez209 @ArianaMinajj I am having an issue where the app crashes on launch , however the option to launch it without tweaks does the job ATM.
Any thoughts on what could be the issue ? 
(iPad/Dopa2/TS2)

**Comment by ArianaMinajj** [comment]
I don't have an iPad so I'm unable to reproduce. However, I can provide you with another tweaked IPA file even though I'm sure that will not resolve your issue.

**Comment by asgeirtj** [comment]
it prompt me that there is an update available everyt time o open the app any way around this?
