### ISSUE TITLE
Strength Training: Tweak does not unlock anything

### ISSUE THREAD

**Issue by kikienrico** [swaggyP36000/TrollStore-IPAs#277]
To unlock premium (correct me if i'm wrong) i press buy premium and then cancel the "order" and everything unlocks, but the premium videos don't load.
There's an infinite loading screen.
![image](https://github.com/swaggyP36000/TrollStore-IPAs/assets/97398717/0e1eeccf-805b-4a48-81ae-49f5c87b831d)

**Comment by ArianaMinajj** [comment]
Hello,

Thank you for bringing this to my attention. You are indeed correct about the process to unlock premium features and I must apologise as I did not thoroughly test whether premium features (such as videos) were actually working..

Unfortunately it seems the tweak does not actually unlock anything which results in the infinite loading screen you've experienced. 

I'm sorry for any inconvenience this may have caused. I'll delete this app as soon as possible.

**Comment by ArianaMinajj** [comment]
Hello,

I re-uploaded the app with another tweak that should solve your issue.

**Comment by sricholkar** [comment]
Hello, I’ve tested it on iOS 17.0 14 Pro. The premium videos don‘t load like before.
