### ISSUE TITLE
App Request Flighty Pro

### ISSUE THREAD

**Issue by Pranobt** [swaggyP36000/TrollStore-IPAs#279]
https://apps.apple.com/gb/app/flighty-live-flight-tracker/id1358823008

**Comment by c12n** [comment]
Doesn't work without Trollstore or jailbreak

![image](https://github.com/swaggyP36000/TrollStore-IPAs/assets/96452263/9aca99b6-346f-4ec4-8310-d1b4dc0af359)

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app and I'll upload it in a few hours!

You can download the latest version **[here](https://gofile.io/d/SrmtmJ)** if you prefer not to wait.

*Note: Tweak is half-working**

**Comment by ArianaMinajj** [comment]
> Doesn't work without Trollstore or jailbreak
> 
> ![image](https://github.com/swaggyP36000/TrollStore-IPAs/assets/96452263/9aca99b6-346f-4ec4-8310-d1b4dc0af359)

Please refrain from posting unnecessary comments without first reading the repository readme.

**Comment by Pranobt** [comment]
> > Doesn't work without Trollstore or jailbreak
> > ![image](https://private-user-images.githubusercontent.com/96452263/313459713-9aca99b6-346f-4ec4-8310-d1b4dc0af359.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MzQ4NzAsIm5iZiI6MTcxMDczNDU3MCwicGF0aCI6Ii85NjQ1MjI2My8zMTM0NTk3MTMtOWFjYTk5YjYtMzQ2Zi00ZWM0LTgzMTAtZDFiNGRjMGFmMzU5LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQwNDAyNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NzhlODhjNTg2Njc0N2EwNjI2MmU4Y2EwOWMwYmQxOWU0ZDVjZmI5M2Q3NjFmMWEzNzVkYjAxOWIzMWE1MGIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3lntaYVPQ54ORb_WlVQch7j7P7y4OrP5QW7SKQCbOP0)
> 
> Please refrain from posting unnecessary comments without first reading the repository readme. _This is your first and last warning_

Is there a problem dude? I read the repository repo there was no comments regarding it. I had posted my request on 15th and u have updated it on 17th

**Comment by ArianaMinajj** [comment]
That comment was meant for the person whose message I deleted, not for you, sorry!

**Comment by Babyyoda777** [comment]
Hi just an issue, I side loaded with side store and the app just crashes on opening, is there a fix for this?

**Comment by RFX530** [comment]
Please update to version 4.0.0 which was released this week. Thank you.

**Comment by c12n** [comment]
4.0.0 is still Trollstore only 

There's an improved tweak by zxcvbn but it's private
