### ISSUE TITLE
InstaRocketBH

### ISSUE THREAD

**Issue by hoangdlnhat** [swaggyP36000/TrollStore-IPAs#281]
on 322.1.1 - 3.8.24
when i reopen the app in the first time log in, BH setting was missing

**Comment by ArianaMinajj** [comment]
Hello,

A fix has already been found for this Instagram version and I'll re-upload it tomorrow.


Feel free to grab it **[here](https://gofile.io/d/wQp5fK)** if you prefer not to wait.

**Comment by Irf90** [comment]
Instagram nyx cracked please
