### ISSUE TITLE
[Request] Flacbox: Hi-Res Music Player

### ISSUE THREAD

**Issue by Russianwaff1e** [swaggyP36000/TrollStore-IPAs#282]
Hey there awesome work! love all you have done for the community. Any chance for this app in ++ mode: 

https://apps.apple.com/us/app/flacbox-hi-res-music-player/id1097564256

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app and I'll upload in a few hours!

You can download the latest version **[here](https://gofile.io/d/Wl1vn5)** if you prefer not to wait.
