### ISSUE TITLE
[Request] Pic Answer AI

### ISSUE THREAD

**Issue by BStyle69** [swaggyP36000/TrollStore-IPAs#286]
https://apps.apple.com/ch/app/pic-answer-ai-solver/id1669210256?l=it

Hello, can you get this app with the premium version? Thank you

**Comment by ArianaMinajj** [comment]
Hello,

I just uploaded it!

**Comment by Irf90** [comment]
Instagram nyx cracked please

**Comment by BStyle69** [comment]
Can you update Pic Answer please. Thx
