### ISSUE TITLE
Adguard Pro from this repo "isn't functional"

### ISSUE THREAD

**Issue by Yuchenjimmy** [swaggyP36000/TrollStore-IPAs#291]
Device: iPad 8th gen
iOS: 14.7.1
Jailbroken: Yes(Taurine)
Trollstore version: 2.0.13
App version: 4.5.2

After I installed the IPA from this repo, the apps crashed instantly. As if using another ipa source(also ver. 4.5.2), though trollstore reports "encrypted binaries" and the filters couldn't update, at least it works. Please check the ipa in this repo again, thank you.

**Comment by ArianaMinajj** [comment]
Hello,

All features of AdGuard Pro are working flawlessly for me. I'm unable to replicate your issue since my device is neither jailbroken nor running iPadOS.
 
*Note that this ipa was grabbed from AppCake*

**Comment by Yuchenjimmy** [comment]
Can comfirm it’s the iOS problem, this ipa is working on 15.3.1 flawlessly.
