### ISSUE TITLE
Boostcamp - Dark mode is gatekeeped

### ISSUE THREAD

**Issue by gokaybalci** [swaggyP36000/TrollStore-IPAs#293]
So there is a very good workout app but dark mode is a premium feature.

Is there a way to make dark mode enabled with or without premium?

https://apps.apple.com/us/app/boostcamp-gym-workout-planner/id1529354455

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app (which also unlock dark mode) and I'll upload it tomorrow!

You can download the latest version **[here](https://gofile.io/d/spjGiX)** if you prefer not to wait.
