### ISSUE TITLE
Issue knowing where to appropriately post.

### ISSUE THREAD

**Issue by Pumba-Mone** [swaggyP36000/TrollStore-IPAs#299]
I understand ISSUES would be an inappropriate place to have flooded with app/tweaked update requests as it would burry real issues and progress.

I have also read the README.md and am not intensionally ignoring it with my question/issue …… 
“Reporting Issues: When opening issues, it's imperative to…Be aware that any…requesting an update…will be immediately marked as completed and closed”

**My issue is not knowing where/if there is an appropriate place to request such updates.**

 Does this repo have a discord or telegram for such requests, any questions, or general discussion?
Or is it just take what you get and check back for when/what comes.

Which I would totally understand as this project must already take an impressive amount of your and contributors time as it is, to then fulfill/maintain additional requests and discussion may simply be to much or uninteresting.

What sprung my post is it is really hard to find a source for consistent ipa updates of Sezo’s Nyx tweak as they only release .debs …I have attempted to research creating .ipa from .deb on device for use with TrollStore with little success. Is there any direction you can point me in to learn this? 

Thank you for your time
I appreciate your work greatly!
What is your dono link?

**Comment by ArianaMinajj** [comment]
Hello,

I appreciate your interest in the project. Regarding update requests I kindly ask for your patience and suggest waiting for updates to be released according to my own schedule. Taking care of individual update requests is impossible as I only focus on stability and quality, which sometimes means updates take longer.

For general discussion, feedback, or questions we don't have a dedicated platform for this repository as I don't find it necessary.

Lastly, If you wish to support our work, the best way to do so is by starring our repository. This not only shows your support but also helps more people discover our project!
