### ISSUE TITLE
Parallel hosting on a decentralized or fully self-controlled Git server

### ISSUE THREAD

**Issue by SoftwareRat** [swaggyP36000/TrollStore-IPAs#303]
Recent events, like the removal of modded YouTube apps from GitHub due to DMCA notices, highlight the risks of relying solely on centralized platforms for hosting your projects. I suggest exploring fully self-controlled Git servers as an alternative hosting option. By doing so, you can reduce the risk of losing access to your work due to platform takedowns.

**Comment by asdfzxcvbn** [comment]
that then transfers the responsibility of responding to DMCAs solely to you, if you own the server that copyrighted material is being hosted on. unless you have a list of services (like VPS hosters) that ignore DMCAs?
