### ISSUE TITLE
[request] CanYouJB .ipa

### ISSUE THREAD

**Issue by ev0tto** [swaggyP36000/TrollStore-IPAs#306]
Could you add this app?
https://github.com/SamoXcZ/CanYouJB/releases

thank you.

**Comment by ArianaMinajj** [comment]
Hello,

I'll upload it tomorrow!

**Comment by ibraheem-200** [comment]
I want to ask please , Is there anyway possible for jailbreaking 17.5.1 PC or not ? , If not is there a way tp downgrade you ipsw in anyway possible ?
