### ISSUE TITLE
Widgy 3.2.1

### ISSUE THREAD

**Issue by SilverFang13** [swaggyP36000/TrollStore-IPAs#309]
Not sure if this is the right place to make an app request (if its not let me know). But would it be possible to get a tweaked ipa of Widgy? The newest ones I’m finding are 5 months old.

**Comment by ArianaMinajj** [comment]
Hello,

Please refer to **[this](https://github.com/swaggyP36000/TrollStore-IPAs/issues/240)**, thank you!
