### ISSUE TITLE
Shark for Messenger 399 doesn't work

### ISSUE THREAD

**Issue by kaloyster** [swaggyP36000/TrollStore-IPAs#31]
It loads and all, can enable the toggles but people can still see you've viewed their message. I can confirm since I tried it on two accounts on different phones.

**Comment by swaggyP36000** [comment]
Known issue. It may be a tweak issue, which means there's nothing you can do for now. There is a jailbreak tweak FBFreeze that may fix that broken feature, just need someone to inject it into FB messenger along with Shark and upload

If that ever happens, I will close this issue
