### ISSUE TITLE
Swipewipe force close

### ISSUE THREAD

**Issue by ashafizullah** [swaggyP36000/TrollStore-IPAs#310]
Hi sir, I have tried swipewipe version v2.03.00 and its force close in iPhone 11 Pro Max.

**Comment by ArianaMinajj** [comment]
Hello,

I'm unable to replicate because I have not experienced any type of crash nor issue. Was the app installed with TrollStore?

**Comment by ashafizullah** [comment]
actually i have installed that on Esign. Is there any guide to install TrollStore? I think its need to root?

**Comment by ArianaMinajj** [comment]
As expected your issue is not Trollstore related so please ensure that any future issues you raise are directly related to this environment. *This is your first and final warning.*
