### ISSUE TITLE
Adobe Acrobat pro

### ISSUE THREAD

**Issue by ssivia** [swaggyP36000/TrollStore-IPAs#313]
Please add Adobe Acrobat Premium

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app and I'll upload it tomorrow!

You can download the latest version **[here](https://gofile.io/d/LxFYbw)** if you prefer not to wait.

**Comment by dswapnil104** [comment]
> Hello,
> 
> A tweak is already available for this app and I'll upload it tomorrow!
> 
> You can download the latest version **[here](https://gofile.io/d/LxFYbw)** if you prefer not to wait.

Hi, could you please link me to tweak? (Dopa2 user)

**Comment by wesmosis** [comment]
Link is not working

**Comment by budakcivic** [comment]
Hi there, looks like this app has issue that unable to view any pdf in adobe acrobat unless copy first to Acrobat AppGroup through Files. Cant add directly in Acrobat.
