### ISSUE TITLE
An issue with Aloha Browser

### ISSUE THREAD

**Issue by TheElexid** [swaggyP36000/TrollStore-IPAs#316]
Hello,

Is it possible at all to stop Aloha Browser Premium from prompting in-app rating review? It comes up every single time I open the downloads tab, and after I close the pop-up with clicking "Not now" or "Cancel" the whole app literally freezes and would have to restart it just for the same thing to happen again whenever I click the downloads tab, deeming it basically inaccessible.

I'm on the latest version, 5.6.1.

For reference, turning off "In-App Ratings & Reviews" in the App Store settings does NOT solve the issue as it doesn't apply to sideloaded apps. I believe the only way would likely be to modify the IPA itself and that's beyond my ability.

![IMG_6083(Y)(scale)(height 1000)](https://github.com/swaggyP36000/TrollStore-IPAs/assets/165325569/a8378793-0a45-4216-b871-db1887da1aea)

I should add, to replicate the issue, you must download a video and keep it available in the downloads tab. Close the app entirely and reopen it, then the in-app rating will start prompting every single time after.

**Comment by ArianaMinajj** [comment]
Hello,

I followed the exact steps meticulously, yet I did not encounter the issue you are facing. Was the app installed with TrollStore ?

**Comment by lucaztz** [comment]
Yes, I have no other way of sideloading. I reinstalled the app multiple times (even on multiple older versions) and I encounter the same issue, following the repro steps I provided above. Hoping you consider just finding a way to get rid of in app rating prompts entirely, if it’s in your capability of course.

**Comment by ArianaMinajj** [comment]
As I said, I am unable to replicate the issue you are experiencing, which means I cannot offer a solution for a problem that I cannot even replicate. Sorry about that!

**Comment by TheElexid** [comment]
Hi,

Not sure who you were talking to but yes, installed with TrollStore. I don’t know what else can be done on my part here as I tried everything. Repro may differ from device to device based on when it was installed and such; I’m aware that there are developers out there who can inject/modify specific code to disable In-App ratings from being prompted at all, hence creating this issue here. Hoping more people who face that same thing to perhaps tell us here as well.

Could you at least keep the issue open as to just see if it’s a common issue and if someone is able to provide a fix?

**Comment by ArianaMinajj** [comment]
"Not sure who you were talking to" 

I answered a message you or an user have deleted:

![image](https://github.com/swaggyP36000/TrollStore-IPAs/assets/117716841/05f36931-0d4c-41de-8ec0-22f91d468e5e)

Note that this "issue" will remain closed and marked as not planned anyway since it appears you are the only one experiencing this.

For additional support and assistance, I suggest consulting the original sources of the IPAs provided **[here](https://t.me/binnichtaktivsipas)** and **[here](https://t.me/AppleTesters)**
