### ISSUE TITLE
Request: WA business aka Whatsapp Business

### ISSUE THREAD

**Issue by schlub51** [swaggyP36000/TrollStore-IPAs#317]
Hi there, 

I was looking for the other app from WhatsApp called WA business that allows me to have 2 different WhatsApp and phone numbers on one phone. 

The current official app from the appstore blocks me coz it detects that I'm jailbroken. Hoping that a modified app for trollstore and injected with watusi could bypass that.

Possible or not, thanks in advance for help

**Comment by ArianaMinajj** [comment]
Hi,

Did you get a chance to check out **[this ipa](https://gofile.io/d/2aa9ke)** from **[DPixel](https://t.me/dpixel)**? 

Note that if it doesn't work for you there's nothing further I can assist with.

**Comment by ArianaMinajj** [comment]
Hello,

I just uploaded it!
