### ISSUE TITLE
[Request] Structured pro

### ISSUE THREAD

**Issue by NicolasBse** [swaggyP36000/TrollStore-IPAs#323]
https://apps.apple.com/us/app/structured-daily-planner/id1499198946

Structured - Daily Planner : Pro version

**Comment by ArianaMinajj** [comment]
Hello,

This app has been in the repo for quite some time now.. Kindly make an effort to read before submitting any requests.

*This is your first and last warning*

**Comment by NicolasBse** [comment]
Hi @ArianaMinajj ,

I apologize for any misunderstanding in my previous request.

I understand that the application is already in the repository, but unfortunately, it doesn't seem to be functioning properly. I've attempted to use it on both a jailbroken iPhone running version 15.7.9 and a non-jailbroken iPhone running version 17.2.1, but the application crashes.

I've tried installing it both via TrollStore and Sidelodly, but encountered the same issue.

Trollstore : 

![image](https://github.com/swaggyP36000/TrollStore-IPAs/assets/35797224/529ca9d2-531d-4753-a217-042f8539d916)

Sidelodly :

![image](https://github.com/swaggyP36000/TrollStore-IPAs/assets/35797224/97d500d7-8fa2-43ff-adb5-537aea2ca973)

Do you have any solutions or suggestions to resolve this?

Thank you in advance for your assistance, and I appreciate your efforts.

**Comment by NicolasBse** [comment]
@ArianaMinajj 

It seems that I've just attempted to install the StructuredPro-3.3.1 version, and the application installs correctly without any issues. 

However, when trying to install version 3.4.0, there seems to be a problem with the installation process.

Thank you for your assistance.

**Comment by ArianaMinajj** [comment]
The message you encountered upon installing the app with TS is a warning as indicated in the initial image, similar to what you'd experience with sideloadly: I did not remove the watch app.

*Note that you may experience crashes as this app requires iOS16 or higher.*
