### ISSUE TITLE
Photomath plus premium features ain't working

### ISSUE THREAD

**Issue by lukar-debug** [swaggyP36000/TrollStore-IPAs#324]
When I try getting a solution from a textbook for example and put show me how. It doesn't work. When I try to put why it doesn't work!![image](https://github.com/swaggyP36000/TrollStore-IPAs/assets/84640224/0aa1ff13-08da-465d-b2ad-bf9598e9849e)
![image](https://github.com/swaggyP36000/TrollStore-IPAs/assets/84640224/942ee8c8-a519-4fc8-83fb-50e96a89cbd8)

Phone: iPhone 12
iOS: 17.0 but was on 15.0 same issue regardless.
Also can you guys bring in mathway pro and guathmath with the pro features I believe educational tools should be free and accessible for everyone

**Comment by ArianaMinajj** [comment]
Hello,

I have not been able to replicate the issue you are experiencing, as Photomath has consistently worked without any problems on my end.

**Comment by asdfzxcvbn** [comment]
those features are server-sided
