### ISSUE TITLE
[Request] Code Runner App

### ISSUE THREAD

**Issue by saifulapm** [swaggyP36000/TrollStore-IPAs#328]
Hi, is this possible to have premium unblocked for this app: https://apps.apple.com/us/app/code-runner-compiler-ide/id6450535928

Thanks

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app and I'll upload it in a few hours!

You can download the latest version **[here](https://gofile.io/d/jKAwuG)** if you prefer not to wait.
