### ISSUE TITLE
Shark 400 and 400.1 still doesn't work

### ISSUE THREAD

**Issue by kaloyster** [swaggyP36000/TrollStore-IPAs#33]
Settings are there but they don't do anything. People you chat can still see you've read their message. They can see you typing. Really tiring.

**Comment by swaggyP36000** [comment]
See [Issue 34](https://github.com/swaggyP36000/TrollStore-IPAs/issues/34)

**Comment by swaggyP36000** [comment]
See [Issue 31](https://github.com/swaggyP36000/TrollStore-IPAs/issues/31). This has yet to be fixed, I will make a note in the release notes if it happens. I have already given the previous issue the bug label and will close it if it ever gets fixed
