### ISSUE TITLE
LA Fitness and TD Canada IPA Request

### ISSUE THREAD

**Issue by christougher2021** [swaggyP36000/TrollStore-IPAs#332]
Hey,

I’m experiencing issues with my Apple Account at the moment, would you be able to release the IPAs for these?

Thank you very much.

**Comment by ArianaMinajj** [comment]
Hello,

For decrypted IPAs, it would be advisable to redirect that request elsewhere, perhaps to this **[place](https://t.me/AppleTesters)**.
