### ISSUE TITLE
Request : Piccolage VIP

### ISSUE THREAD

**Issue by LileAuTresor** [swaggyP36000/TrollStore-IPAs#336]
Hi, is it possible to have Piccolage VIP : https://apps.apple.com/us/app/piccollage-ai-photo-editor/id448639966

Here is the deb made by kiengk0eng (Depends: firmware >=12, mobilesubstrate) : https://github.com/kiengk0eng/kiengk0eng.github.io/blob/master/pkg/com.kiengk0eng.piccollage.deb

This deb works only with 7.56.1 ipa

Thanks !

**Comment by ArianaMinajj** [comment]
Hello,

I'll upload it in a few hours!

You can download the latest version **[here](https://gofile.io/d/4Egut2)** if you prefer not to wait.

**Comment by LileAuTresor** [comment]
Thank you but the deb is not compatible with version 8.34.2, not all the items are unlocked.

I made the 7.56.1 ipa by myself if you want. You can download what you want but there is alwaus the popup for vip subscription (same with jailbreak and deb installed) : https://mega.nz/file/b3RUSIha#gfQFEevfBD6Wayo37VeoNjOWR9zSkxWcYHucB0KC2S0

**Comment by ArianaMinajj** [comment]
Can you please explain specifically what remains locked

**Comment by ArianaMinajj** [comment]
I've tested it with both the tweak you provided and Satella and every VIP features works. 

I'm afraid you're not installing this with TrollStore, are you?

**Comment by LileAuTresor** [comment]
Yes, i installed it with trollstore...
Did you have this message on first launch ?
![IMG_0665](https://github.com/swaggyP36000/TrollStore-IPAs/assets/42318092/f5616a3f-0463-4b38-bf7a-d8d899923547)

**Comment by ArianaMinajj** [comment]
**[Here](https://gofile.io/d/77Zmbh)** an updated link to the IPA that includes a fix. (Satella)

1- Please install the IPA
2- Proceed to purchase VIP. 
3- Restart the app. 

Upon relaunch all VIP features will be unlocked. At this point you can download the app from the App Store and the VIP features will continue to be accessible.

Let me know if this worked for you!

**Comment by LileAuTresor** [comment]
Yes, we had the same idea, i did the same and it works ! Thank you
