### ISSUE TITLE
Request: Wordle!

### ISSUE THREAD

**Issue by dvl2014** [swaggyP36000/TrollStore-IPAs#338]
Request: it would be amazing and it would mean the world if you can add Satella or whatever so we can purchase as many coins as we want without actually getting charged and/or somehow get unlimited /know what the words are

App Store Link: https://apps.apple.com/us/app/wordle/id1095569891

I hope you can make this possible, thank you for all you do in the community!

**Comment by dvl2014** [comment]
Hi i saw you marked this as closed, does it mean you declined to do this or can't do it? Just wondering thanks!

**Comment by ArianaMinajj** [comment]
Hello,

Since it seems to be quite important to you I have still made an ipa **[here](https://gofile.io/d/WCuwFY)**.

Still refrain from requesting games in the future, thank you!

*This is your first and last warning*

**Comment by dvl2014** [comment]
Hi thank you so so much @ArianaMinajj ! I also apologize i didn't know about no game requests. I also wanted to ask you and not annoy you by opening a separate ticket for you to later close, but for TrollRecorder will it work on iPhone that don't have troll store? Thanks again so much for what you do!

**Comment by ArianaMinajj** [comment]
TrollRecorder is TS exclusive pretty much like other ipas in the repo.

I'm uncertain if there's a non-TS alternative that serves the same purpose.
