### ISSUE TITLE
Facebook Wolf 406 crashes on launch

### ISSUE THREAD

**Issue by kaloyster** [swaggyP36000/TrollStore-IPAs#34]
Even if blacklisted on Choicy to not load tweaks the app still crashes rendering it useless.

**Comment by swaggyP36000** [comment]
Even with tweaks enabled it should work fine. I have tested the app myself. What iOS are you on?

**Comment by kaloyster** [comment]
> Even with tweaks enabled it should work fine. I have tested the app myself. What iOS are you on?

I’m on 16.1.2

**Comment by swaggyP36000** [comment]
Some of the apps on this library will likely need to be updated by the devs maintaining them to support iOS 16. I'm gonna close your other issue with Shark for Messenger as well since I have tested both and they are working fine on iOS 14. Sorry about that
