### ISSUE TITLE
[request] iChan, Pyoncord

### ISSUE THREAD

**Issue by ev0tto** [swaggyP36000/TrollStore-IPAs#351]
Can you add these app?

Pyoncord
https://github.com/pyoncord/PyoncordTweak/releases

iChan
https://www.reddit.com/r/iOSSideLoading/comments/16or1wc/ichan_ios_appopen_source_imageboard_browser_for/
https://t.me/ichanapp

**Comment by ArianaMinajj** [comment]
Hello,

I'll add these apps in the repo tomorrow. 

Thank you for your contribution!
