### ISSUE TITLE
[Request] Not Boring Weather

### ISSUE THREAD

**Issue by SakethKanchi** [swaggyP36000/TrollStore-IPAs#361]
Premium Version of this app?
https://apps.apple.com/us/app/not-boring-weather/id1531063436

**Comment by ArianaMinajj** [comment]
Hello,

A tweak for this app is already available but I won't upload it as it is partially functional: 

- Widgets are showing Seattle instead of the user's current location

-Tweak does not work on iOS17.0

**Comment by ArianaMinajj** [comment]
I just uploaded it!
