### ISSUE TITLE
Fitness AI

### ISSUE THREAD

**Issue by maplepy** [swaggyP36000/TrollStore-IPAs#363]
Hello!

I was wondering if there was a tweak for **[fitness ai](https://apps.apple.com/us/app/fitness-ai-gym-home-workout/id1446224156)** ? and if so could you upload the ipa with the tweak please? that's a great app but it cost a lot :skull:  

Thanks :)

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app and I'll upload it tomorrow!

You can download the latest version **[here](https://gofile.io/d/cpnZKi)** if you prefer not to wait.

*I have added the link to the AppStore in your comment*

**Comment by maplepy** [comment]
wooow thank you so much man! love you :heart:

**Comment by maplepy** [comment]
yeah it crashes whenever i want to launch it :/

**Comment by ArianaMinajj** [comment]
You're free to open a separate issue **after carefully reading the reporting notice on the readme.**

**Comment by maplepy** [comment]
> You're free to open a separate issue **after carefully reading the reporting notice on the readme.**

my bad, i thought i was commenting on fitbod, not fitness ai :skull: 

fitness ai works perfectly :) thank you so much!

**Comment by Logic77** [comment]
Anyone else having issues where it just keeps closing?

**Comment by maplepy** [comment]
I have no issue myself, make sure you have the correct iOS version as I know some apps do close on launch because my iOS version is too old

**Comment by xspecialko** [comment]
Can you reshare the link please? It says expired.

**Comment by xspecialko** [comment]
> Hello,
> 
> A tweak is already available for this app and I'll upload it tomorrow!
> 
> You can download the latest version **[here](https://gofile.io/d/cpnZKi)** if you prefer not to wait.
> 
> _I have added the link to the AppStore in your comment_

Can you reshare the link please.
