### ISSUE TITLE
Request for Moises: Ai

### ISSUE THREAD

**Issue by Aethereux** [swaggyP36000/TrollStore-IPAs#365]
is there any tweaked version of this app?

https://apps.apple.com/us/app/moises-ai-music-platform/id1515796612

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app and I'll upload it in a few hours!

You can download the latest version **[here](https://gofile.io/d/LyHPFt)** if you prefer not to wait.

**Comment by League2EB** [comment]
@ArianaMinajj Can you provide an iPA download?
thx all
