### ISSUE TITLE
[Request] Coding app ‘Sololearn’ pro version request

### ISSUE THREAD

**Issue by jasonyooyj** [swaggyP36000/TrollStore-IPAs#372]
Hi, currently loving your contents and what you do. Much thanks to you.

I’ve tried searching for app ‘sololearn’ pro version, but couldn’t find one.

I’ll be grateful if you can help me out.

Thank you.

https://apps.apple.com/kr/app/sololearn-ai-code-learning/id1210079064?l=en-GB

**Comment by ArianaMinajj** [comment]
Hello,

This request has already been submitted and closed as it is currently not possible.
