### ISSUE TITLE
[Request] MacroFactor Macro-Tracker Premium

### ISSUE THREAD

**Issue by Kishenpatel99** [swaggyP36000/TrollStore-IPAs#373]

**Comment by ArianaMinajj** [comment]
Hello, 

I just uploaded it!

**Comment by Kishenpatel99** [comment]
Thank you so much!!

**Comment by mackswell08** [comment]
Fantastic! The app works just as promised. Is there any way to get the widgets working too? Or is that the trade-off for installing these IPA's?

**Comment by ArianaMinajj** [comment]
Hello @mackswell08 ,

I've retested the widgets and they are working, your feedback prompted me to double-check.

I'm guessing you're not installing that app with TrollStore?

**Comment by mackswell08** [comment]
Hello @ArianaMinajj ,

I am not. I am downloading the IPA and installing through Signulous, as my phone is unjailbroken. I guess that's on me. Is there any way to make the widgets work on a non-jailbroken iPhone? Thanks!

**Comment by sunkenship2025** [comment]
hey i cant find it where do i download

**Comment by sunkenship2025** [comment]
> Hello @ArianaMinajj ,
> 
> I am not. I am downloading the IPA and installing through Signulous, as my phone is unjailbroken. I guess that's on me. Is there any way to make the widgets work on a non-jailbroken iPhone? Thanks!

can u help me out pleaseeee

**Comment by hsmvsdawrld** [comment]
I am an android user, how can i download this. Is there an apk ? And is this a cracked free version of "macrofactor" app ? Please guide me
