### ISSUE TITLE
[Request] Strava: Run, Bike, Hike Premium

### ISSUE THREAD

**Issue by Kishenpatel99** [swaggyP36000/TrollStore-IPAs#376]
It would be absolutely amazing if you can unlock premium on this app!

Thank you all so much again!

**Comment by Kishenpatel99** [comment]
When it says not planned does that mean it’s not possible?

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app and I'll upload it tomorrow!

You can download the latest version **[here](https://gofile.io/d/Saxveq)** if you prefer not to wait.

**Comment by Defflix** [comment]
Decrypted strava crashes when installed through trollstore. Would it be possible to make a .deb tweak out of this ipa to make it compatible with the roothide bootstrap?

**Comment by datrip** [comment]
> Hello,
> 
> A tweak is already available for this app and I'll upload it tomorrow!
> 
> You can download the latest version **[here](https://gofile.io/d/Saxveq)** if you prefer not to wait.

Is this still available? the link no longer works :(

**Comment by ivanstojkovicapps** [comment]
do you have a problem on apple that you are always signed out once you close the app?

**Comment by RishiSuthar** [comment]
> here

i have the same problme

**Comment by ZerOneX** [comment]
hey, any news regarding the tweaked app? thx

**Comment by HsiaoSeanHS** [comment]
The ipa from this update may work. The app can be opened normally, but I haven't tested the functions yet.
iOS 15.7.2 with TrollStore v2.1
https://github.com/swaggyP36000/TrollStore-IPAs/releases/tag/05-05-2024
