### ISSUE TITLE
Looking for a music streaming/downloading app

### ISSUE THREAD

**Issue by SilverFang13** [swaggyP36000/TrollStore-IPAs#379]
I’m looking for an app that can do streaming and downloading music. I have tried blackhole and spotube but am having problems with both. The new spotify tweak that was added also hasn’t been working for me.

**Comment by ArianaMinajj** [comment]
It is obvious that downloading songs on tweaked music streaming apps is impossible as this is a server sided, but you might still consider trying **[Audiomack Premium](https://github.com/swaggyP36000/TrollStore-IPAs/releases/download/04-06-2024/AudiomackPremium-6.29.1.ipa)**. 

Please note that if this doesn't work there's nothing further I can do to assist.

**Comment by SilverFang13** [comment]
I’m sorry if these is a dumb question but how do blackhole and spotube download songs if it’s impossible on ipa’s?

**Comment by ArianaMinajj** [comment]
I believe it's because they use YouTube's / YouTube's music free api to grab songs, though I'm not certain about Blackhole.
