### ISSUE TITLE
Turbo Vpn New Ipa not working

### ISSUE THREAD

**Issue by achesUwU** [swaggyP36000/TrollStore-IPAs#38]
The new Turbo Vpn that was posted is not working. Whenever I connect to a vpn, it disconnects immediately

**Comment by gluesn** [comment]
Try using the one built into Speedtest instead.

**Comment by swaggyP36000** [comment]
It is TrollStore only. I'll make a note in the readme and close this issue when I can access my PC again. Sorry about that
