### ISSUE TITLE
kamo hacks are just republishers

### ISSUE THREAD

**Issue by rootleg** [swaggyP36000/TrollStore-IPAs#39]
kamohacks just repacks other communities ipas as their own and make it seem like they made it
iosgods
![05CC30A9-80B6-47CB-ACD2-837BBC5320A1](https://user-images.githubusercontent.com/93836206/229173948-df013446-50f0-49c9-9ee5-0299355b9a55.jpeg)
kamohacks
![137CCAA2-24A3-4F3B-9C89-BA12C9C90559](https://user-images.githubusercontent.com/93836206/229173955-21372ecd-9c53-45b9-b81a-053270f6a22c.jpeg)

**Comment by rootleg** [comment]
also kamohack also gets access to your Apple token which is basically grants access to your smart card
![5ABBD90C-E854-4DCF-B403-BE909B22D40A](https://user-images.githubusercontent.com/93836206/229175294-917914f1-4a19-4518-bccf-c74a0c703163.png)
![6D0D93FB-E92E-4EEB-9739-C831E87CD12C](https://user-images.githubusercontent.com/93836206/229175385-78bf7fca-6334-4e87-8927-370bdfcea24c.png)

**Comment by swaggyP36000** [comment]
This is known. I just happen to use their telegram for updates - if you play the games or use the apps you can see the iOSGods portal

Also, a lot of the apps in here have that com.apple.token thing. I wouldn't worry too much about it
