### ISSUE TITLE
[Request] AnkiPro Premium

### ISSUE THREAD

**Issue by SilverFang13** [swaggyP36000/TrollStore-IPAs#395]
Is there a way to get this flashcard app or another similar one?

**https://apps.apple.com/us/app/anki-pro-study-flashcards/id1573585542**

**Comment by ArianaMinajj** [comment]
Hello,

As this is not possible, I recommend trying alternatives such as AnkiMobile Flashcards which is available on **[AppCake](https://iphonecake.com/app_373493387_.html)**

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app and I'll upload in a few hours!

You can download the latest version **[here](https://gofile.io/d/cj6fqR)** if you prefer not to wait.
