### ISSUE TITLE
Strength Training: this tweak still does work 

### ISSUE THREAD

**Issue by sricholkar** [swaggyP36000/TrollStore-IPAs#397]
Hello, as subject of the issue says it all. Although you fixed something as part of issue #277 , it still doesn’t work on iOS 17.0 14 Pro(not in jailbroken state), the premium videos don’t load or I don’t know if there are any additional steps apart from clicking Professional —> Subscribe to make it work?

**Comment by ArianaMinajj** [comment]
Hello,

Are you installing the app via TrollStore?

**Comment by sricholkar** [comment]
Yes

**Comment by ArianaMinajj** [comment]
I am unable to replicate the issue as the videos are not only functional but also downloadable, sorry about that!
