### ISSUE TITLE
Gangster: New Vegas down

### ISSUE THREAD

**Issue by m0420** [swaggyP36000/TrollStore-IPAs#4]
Hi,
The gangsters ipa‘s link is already down. Could you please re-up to another Hoster? Thanks a lot!

**Comment by swaggyP36000** [comment]
> Hi,
> 
> The gangsters ipa‘s link is already down. Could you please re-up to another Hoster? Thanks a lot!

I'll re-upload it to Mega as soon as I can. The file is on my computer and I won't have access to it until at least midnight

**Comment by swaggyP36000** [comment]
New link has been posted to the latest release. Enjoy!
