### ISSUE TITLE
TikTokLRD v3.3 possibly cracked.

### ISSUE THREAD

**Issue by GuinnessShep** [swaggyP36000/TrollStore-IPAs#401]
I may have inadvertently cracked TikTokLRD v3.3 on TikTok version 32.3.0. It seems to install across all of my devices without the activation splash screen. I originally had access to the paid version, and it seems after activating it and decrypting it a few times with different apps (appindex, TrollDecrypt, and appdump2), it just works. The only thing is, installing it on my devices automatically signs me in to TikTok. I’m not sure if my login is saved in the ipa or locally, but I’ll share it with you and you can test it if you’d like.

**Comment by ArianaMinajj** [comment]
Hello,

Thank you for your efforts! Could you please provide a direct download link so I can check and test the ipa?

I believe the automatic login can be reset through AppsManager though I'm not entirely sure.

**Comment by GuinnessShep** [comment]
@ArianaMinajj https://gofile.io/d/n5YAAr
Please lmk asap if my acc is linked 😭

**Comment by ArianaMinajj** [comment]
Your account doesn't seem to be linked in any way, I'll consider uploading that to the repo. (As an update)

**Comment by c12n** [comment]
Tried installing this on my 13pm on 17.4.1 via dev cert 

Installed, works, can't get past the login screen for LRD. It's asking for a code. 

App appears not to be cracked. 

Might only work through TS or jailbreak.

**Comment by GuinnessShep** [comment]
> Tried installing this on my 13pm on 17.4.1 via dev cert
> 
> Installed, works, can't get past the login screen for LRD. It's asking for a code.
> 
> App appears not to be cracked.
> 
> Might only work through TS or jailbreak.

Interesting, yeah I’ve only been using it with TrollStore.
