### ISSUE TITLE
[Request] Premium Version of Blitzer app

### ISSUE THREAD

**Issue by EloneMusk** [swaggyP36000/TrollStore-IPAs#407]
Can you please upload premium version of Blitzer app

https://apps.apple.com/de/app/blitzer-de-pro/id498732510

**Comment by ArianaMinajj** [comment]
Hello,

You might want to try this **[ipa](https://gofile.io/d/IW5dNt)**, it should be working.

*This will not be uploaded to the repo nor will I assist you further.*
