### ISSUE TITLE
YouTube Elite v18.11.2 & 18.13.4 login issues

### ISSUE THREAD

**Issue by swaggyP36000** [swaggyP36000/TrollStore-IPAs#41]
If you aren't installing the latest YouTube Elite IPAs with TrollStore, you may be facing one of the issues below:

- YouTube 18.11.2 - sign-in may require [this workaround](https://www.reddit.com/r/sideloaded/comments/12dfaa9/comment/jf871f3/?utm_source=share&utm_medium=web2x&context=3)
- YouTube 18.13.4 - signs out after every app close, no idea why this is

For now, either install these with TrollStore or use v18.03.3 under the [01-31-2023 release](https://github.com/swaggyP36000/TrollStore-IPAs/releases/tag/01-31-2023)

I will close this issue when a new sign-in fix is added that addresses these issues

**Comment by asdfzxcvbn** [comment]
i've been having this problem too, i decrypt and inject tweaks myself and everything worked fine up until v18.12.2 i think. i have had someone tell me [this](https://hostigram.xyz/?tkn=MbEHAPgGHzpImEyAVdwsqJSEZBofKhMaH5EQQ48jQkoPt) fixed it for them but i didnt have any luck with it.

**Comment by swaggyP36000** [comment]
> i've been having this problem too, i decrypt and inject tweaks myself and everything worked fine up until v18.12.2 i think. i have had someone tell me [this](https://hostigram.xyz/?tkn=MbEHAPgGHzpImEyAVdwsqJSEZBofKhMaH5EQQ48jQkoPt) fixed it for them but i didnt have any luck with it.

The fixLogin dylib already exists in the YouTube Elite IPA. You can view the existing dylibs in the IPA through ESign

**Comment by asdfzxcvbn** [comment]
> The fixLogin dylib already exists in the YouTube Elite IPA. You can view the existing dylibs in the IPA through ESign

and it’s still not working? i even tried rolling back to an old version of youtube that i KNOW worked but it logs me out on restart too..

**Comment by leo04real** [comment]
Please, can you also decrypt Textme app?

**Comment by asdfzxcvbn** [comment]
> The fixLogin dylib already exists in the YouTube Elite IPA. You can view the existing dylibs in the IPA through ESign

bander [committed a login fix](https://github.com/qnblackcat/uYouPlus/commit/43220f7d31cfda622fc43b50fba658958ec1bf4c) to uyouplus’s repo, and it seems to work fine on the latest version. perhaps you could turn it into a dylib somehow?

**Comment by swaggyP36000** [comment]
> > The fixLogin dylib already exists in the YouTube Elite IPA. You can view the existing dylibs in the IPA through ESign
> 
> 
> 
> bandar [committed a login fix](https://github.com/qnblackcat/uYouPlus/commit/43220f7d31cfda622fc43b50fba658958ec1bf4c) to uyouplus’s repo, and it seems to work fine on the latest version. perhaps you could turn it into a dylib or build an ipa with the fix?
> 
> 

I saw this as well, I'll take a look at it in a couple hours when I can access my PC

**Comment by asdfzxcvbn** [comment]
> > > The fixLogin dylib already exists in the YouTube Elite IPA. You can view the existing dylibs in the IPA through ESign
> > 
> > 
> > bandar [committed a login fix](https://github.com/qnblackcat/uYouPlus/commit/43220f7d31cfda622fc43b50fba658958ec1bf4c) to uyouplus’s repo, and it seems to work fine on the latest version. perhaps you could turn it into a dylib or build an ipa with the fix?
> 
> I saw this as well, I'll take a look at it in a couple hours when I can access my PC

could you release a dylib or any other form of a patch in case you do figure it out?

**Comment by swaggyP36000** [comment]
> > > > The fixLogin dylib already exists in the YouTube Elite IPA. You can view the existing dylibs in the IPA through ESign
> > > 
> > > 
> > > bandar [committed a login fix](https://github.com/qnblackcat/uYouPlus/commit/43220f7d31cfda622fc43b50fba658958ec1bf4c) to uyouplus’s repo, and it seems to work fine on the latest version. perhaps you could turn it into a dylib or build an ipa with the fix?
> > 
> > 
> > I saw this as well, I'll take a look at it in a couple hours when I can access my PC
> 
> could you release a dylib or any other form of a patch in case you do figure it out?

If I manage to figure it out, I will definitely release an update to the library

**Comment by swaggyP36000** [comment]
Quick update: I just got notified that I'm locked out of my Twitter (lord knows why), and I won't be able to do anything about it for 24 hours. I'll see if I can reach BandarHL via GitHub

**Comment by swaggyP36000** [comment]
To anyone viewing this, I got a response from BandarHL, and I have created 2 test IPAs:

1. https://drive.google.com/file/d/1tWKxFdvwPwMAJeeJCDHzC77-UcVhGXY8/view?usp=drivesdk

2. https://drive.google.com/file/d/1b6icyTMKDEnczKHfxzEDm811xKuqa7NG/view?usp=drivesdk

Lmk which, if either, fix the sign in issues when sideloaded

**Comment by asdfzxcvbn** [comment]
> To anyone viewing this, I got a response from BandarHL, and I have created 2 test IPAs:
> 
> 1. https://drive.google.com/file/d/1tWKxFdvwPwMAJeeJCDHzC77-UcVhGXY8/view?usp=drivesdk
> 2. https://drive.google.com/file/d/1b6icyTMKDEnczKHfxzEDm811xKuqa7NG/view?usp=drivesdk
> 
> Lmk which, if either, fix the sign in issues when sideloaded

hey, we need access, it’s not letting me access it

**Comment by asdfzxcvbn** [comment]
> Sorry, just changed access for those two files

the first one is still private, and the second one is crashing

iphone xr running 16.3

**Comment by swaggyP36000** [comment]
Just unprivated the first one, sorry about that

**Comment by asdfzxcvbn** [comment]
first one is also crashing

**Comment by swaggyP36000** [comment]
In tha case I have no idea. The FixLogin (not fixLogin) dylib is extractable from the IPA with ESign, so you should be able to test it yourself. Unfortunately I'm not sure what else to try at this point

**Comment by swaggyP36000** [comment]
In tha case I have no idea. The FixLogin (not fixLogin) dylib is extractable from the IPA with ESign, so you should be able to test it yourself. Unfortunately I'm not sure what else to try at this point

**Comment by asdfzxcvbn** [comment]
> In tha case I have no idea. The FixLogin (not fixLogin) dylib is extractable from the IPA with ESign, so you should be able to test it yourself. Unfortunately I'm not sure what else to try at this point

you forgot to fix the dependency on CydiaSubstrate, but even with it fixed, it still crashes

**Comment by asdfzxcvbn** [comment]
i figured out how to fix it, i think all that's required is that you have at least one open source tweak injected. you could just inject IAmYouTube anyway, i can help u with this tomorrow if you dm me on telegram - @asdfzxcvbn0
