### ISSUE TITLE
[Request] Ketchup+ for Pokémon

### ISSUE THREAD

**Issue by ThatGuy0rion** [swaggyP36000/TrollStore-IPAs#412]
https://apps.apple.com/us/app/ketchup-for-pok%C3%A9mon/id6477297968

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app and I'll upload it in a few hours!

You can download the latest version **[here](https://gofile.io/d/kQPYGq)** if you prefer not to wait.
