### ISSUE TITLE
Duolingo - App Throws Error when accessing "Refreshers"

### ISSUE THREAD

**Issue by dankmaster** [swaggyP36000/TrollStore-IPAs#416]
![photo_5886517631861768439_y](https://github.com/swaggyP36000/TrollStore-IPAs/assets/85390419/d4bfb702-3870-4d34-aa68-9da78598e1a4)

App Throws Error when accessing "Refreshers", some exercises seem to work. Might be due to app is getting outdatet.

**Comment by ArianaMinajj** [comment]
Hello,

Was the app installed with TrollStore? This behavior frequently occurs when using ESign or other sideloading methods.

**Comment by dankmaster** [comment]
Hello, Thanks for quick reply, that's right, this instance is from sideloadly.
Thanks for clarifying.
