### ISSUE TITLE
[Request] how to submit requests

### ISSUE THREAD

**Issue by benswolo** [swaggyP36000/TrollStore-IPAs#418]
Is there a reason why some apps are rejected over others? I wasn't able to find any info about requesting apps. Do you only upload Freemium apps that are satella compatible? Even saying that you only accept apps you care about would clear up a lot of confusion and I would be grateful.

**Comment by ArianaMinajj** [comment]
Hello,

If you can't find any information about it that's simply because it's not permitted in the first place. I'm only doing this in my spare time.

If a request is closed it means either tweaking the app isn't feasible at the moment or the app is too specific for my current scope.
