### ISSUE TITLE
你好，可以谈下合作，方便的话可以加下我微信搜索：dumpapp

### ISSUE THREAD

**Issue by bigsen** [swaggyP36000/TrollStore-IPAs#42]
你好，可以谈下合作，方便的话可以加下我微信搜索：dumpapp

**Comment by swaggyP36000** [comment]
I don't use WeChat, but we can talk on here if you want to. What kind of collab?

**Comment by bigsen** [comment]
I am the webmaster of dumapp.com. If we cooperate, you can provide ipa continuously, and I can give you fees or traffic advertisements

**Comment by swaggyP36000** [comment]
I think there's been a slight misunderstanding - I am not the owner of most of the apps I upload to this library. I have listed the maintainers behind the tweaked IPAs that I am hosting here. I think you will want to ask them about this offer instead. Thanks for the offer, though
