### ISSUE TITLE
Tumblr bear no-ads isn't working

### ISSUE THREAD

**Issue by gototheskinny** [swaggyP36000/TrollStore-IPAs#43]
It asks for a purchase. Is it only the free version?

**Comment by swaggyP36000** [comment]
I may be missing something but I'm not seeing ads in Tumblr. If you mean Bear, yeah it's the free version

**Comment by gototheskinny** [comment]
> I may be missing something but I'm not seeing ads in Tumblr. If you mean Bear, yeah it's the free version

I don't know where you live in but in my country Türkiye, I see ads in main page. I asked about Bear yes. The tweak ask for a paid account(for bear not Tumblr) if you click the remove ads section so yeah.

**Comment by swaggyP36000** [comment]
For adblock you can also try one of the MyBloxx profiles. Results may vary based on country

**Comment by gototheskinny** [comment]
> For adblock you can also try one of the MyBloxx profiles. Results may vary based on country

Adblock dns works!
