### ISSUE TITLE
[Request]  Clip Studio Paint

### ISSUE THREAD

**Issue by Jehicular** [swaggyP36000/TrollStore-IPAs#432]
Shot in the dark as it seems it hasn't had a crack since ~2022, but
https://apps.apple.com/us/app/clip-studio-paint/id1262985592

They charge monthly for access to features now. 

Thanks anyway, great work!

**Comment by ArianaMinajj** [comment]
Hello,

This app doesn't seem to be compatible with my device or any iOS devices? So I'll have to close that request, sorry about that!
