### ISSUE TITLE
[Request] Musixmatch Premium

### ISSUE THREAD

**Issue by CattoYT** [swaggyP36000/TrollStore-IPAs#433]
May as well ask, no idea if this has been cracked though.
https://apps.apple.com/us/app/musixmatch-lyrics-finder/id448278467

**Comment by tyhallcsu** [comment]
v7.11.0 decrypt if you wanted to sideload the tweak:

https://workupload.com/file/e5JxmWGKpCm

_TrollDecrypt on iOS 15.4.1 / Dopamine was used to decrypt._
