### ISSUE TITLE
Requeste Noteshelf 3

### ISSUE THREAD

**Issue by BStyle69** [swaggyP36000/TrollStore-IPAs#436]
https://apps.apple.com/ch/app/noteshelf-3/id6458735203?l=it

Hallo, it’s possible to have this app with premium unlocked? Thx a lot.

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app and I'll upload it in a few hours!

You can download the latest version **[here](https://gofile.io/d/xYYb9X)** if you prefer not to wait.

**Comment by BStyle69** [comment]
thanks for the quick reply
