### ISSUE TITLE
[Request] Perfect IPTV PRO

### ISSUE THREAD

**Issue by ssivia** [swaggyP36000/TrollStore-IPAs#437]
Can you please add perfect IPTV **PRO** https://apps.apple.com/ca/app/iptv-watch-tv-online/id1516946830

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app and I'll upload it in a few hours!

You can download the latest version **[here](https://gofile.io/d/A2rAk6)** if you prefer not to wait.

**Comment by ssivia** [comment]
Can you please update it

**Comment by ssivia** [comment]
Version 2.8.1 update please
