### ISSUE TITLE
[Request] Alight Motion Premium

### ISSUE THREAD

**Issue by ed6dev** [swaggyP36000/TrollStore-IPAs#438]
Hello Can You Please Add These Apps : 
- **[Alight Motion](https://apps.apple.com/us/app/alight-motion/id1459833443)**
- **[Video Star](https://apps.apple.com/us/app/video-star/id438596432)**

They Both Require A Subscription To Remove The Watermark and Unlock Features
_Thank you in advance_

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for *Alight Motion** and I'll upload it in a few hours!

You can download the latest version **[here](https://gofile.io/d/T7xq22)** if you prefer not to wait.

**Kindly request one app at a time in the future, thank you!**

**Comment by ed6dev** [comment]
Just Tried It. It Doesn't Seem To Be Working

**Comment by ArianaMinajj** [comment]
You'll have to develop?
