### ISSUE TITLE
Can you make a Scarlet version 

### ISSUE THREAD

**Issue by Bean0-0** [swaggyP36000/TrollStore-IPAs#44]

**Comment by swaggyP36000** [comment]
Doesn't Scarlet allow you to import downlaoded apps?

**Comment by Bean0-0** [comment]
Yes, but importing your repo crashes the app

**Comment by swaggyP36000** [comment]
Don't import the repo. Use something like ESign to download the apps and then import to Scarlet

**Comment by Bean0-0** [comment]
Ok thanks
