### ISSUE TITLE
[Request] Ibis Paint X Prime

### ISSUE THREAD

**Issue by Aethereux** [swaggyP36000/TrollStore-IPAs#441]
[Ibis Paint X](https://apps.apple.com/ph/app/ibis-paint-x/id450722833)

Prime Unlocked

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app and I'll upload it in a few hours!

You can download the latest version **[here](https://gofile.io/d/vK6FSQ)** if you prefer not to wait.
