### ISSUE TITLE
[Request] OPL Monitor

### ISSUE THREAD

**Issue by gonlarravri** [swaggyP36000/TrollStore-IPAs#447]
It's an app to configure Opel/Vauxhall vehicle parameters. I'll be glad if anyone could inject satella or free in app purchases.

https://apps.apple.com/es/app/opl-monitor/id1559105523

Best regards,

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app but won't be uploaded into the repo.

You can download the latest version **[here](https://gofile.io/d/bD6bHZ)**.
