### ISSUE TITLE
[Request] Deezer Premium

### ISSUE THREAD

**Issue by gototheskinny** [swaggyP36000/TrollStore-IPAs#450]
I don't know which version is the best tho. Can you add this or would that be dangerous bc of the DMCA.

**Comment by ArianaMinajj** [comment]
Hello,

I intentionally refrained from uploading this because the only available **[tweaked IPA](https://gofile.io/d/635eoz)** is significantly outdated. 

I'm not even sure if this is actually working.

**Comment by gototheskinny** [comment]
> Hello,
> 
> I intentionally refrained from uploading this because the only available **[tweaked IPA](https://gofile.io/d/635eoz)** is significantly outdated. 
> 
> I'm not even sure if this is actually working.

Some people are saying that they're using that ipa. I don't know if it's good enough or worth it tho. Downloading feature works for that ipa that's why those people are using it. Some people would use that feature for sure.
