### ISSUE TITLE
[Request] EpocCam Webcamera for Computer

### ISSUE THREAD

**Issue by eggwosh** [swaggyP36000/TrollStore-IPAs#453]
https://apps.apple.com/us/app/epoccam-webcamera-for-computer/id435355256

Need paid version for higher quality camera streaming.

**Comment by ArianaMinajj** [comment]
Hello,

You can find the latest version **[here](https://gofile.io/d/efoY5D)**.

Please note that this won't be uploaded into the repo as AppCake already is hosting that **[app](https://www.iphonecake.com/app_435355256_.html)**.
