### ISSUE TITLE
[Request] Scorecam - Embedded Scoreboard

### ISSUE THREAD

**Issue by st-ivan** [swaggyP36000/TrollStore-IPAs#457]
Hello!, thanks for your work, can you please upload this app:

https://apps.apple.com/us/app/scorecam-embedded-scoreboard/id862175401

**Comment by st-ivan** [comment]
hello, just a quick question, care to explain why this was not accepted/cracked? That way i know which apps i could not request

**Comment by ArianaMinajj** [comment]
Hello,

Please refer to **[this](https://github.com/swaggyP36000/TrollStore-IPAs/issues/418)**, thank you!
