### ISSUE TITLE
Spotify IPA cannot be installed via Scarlet

### ISSUE THREAD

**Issue by KieranBLK** [swaggyP36000/TrollStore-IPAs#46]
So far this IPA is the only one thats giving me this issue when installing with Scarlet. It just fails to codesign the app every time for every Spotify IPA in this repo. Any idea why? 

![image](https://user-images.githubusercontent.com/120525685/233354822-92bfc45b-cce2-42f0-90f1-cc8c45347cc5.png)

**Comment by swaggyP36000** [comment]
Scarlet has issues with some imported apps. Not sure what the reason behind that is. Is this with the latest Spotilife IPA?

**Comment by KieranBLK** [comment]
> Scarlet has issues with some imported apps. Not sure what the reason behind that is. Is this with the latest Spotilife IPA?

Yeah. This is with the latest but it's also happened with the last 2 you've posted.

**Comment by swaggyP36000** [comment]
Try another method to sign

**Comment by Nanki0722** [comment]
> So far this IPA is the only one thats giving me this issue when installing with Scarlet. It just fails to codesign the app every time for every Spotify IPA in this repo. Any idea why? 
> 
> ![image](https://user-images.githubusercontent.com/120525685/233354822-92bfc45b-cce2-42f0-90f1-cc8c45347cc5.png)

bro how can u download the youtube music ipa？

**Comment by KieranBLK** [comment]
> Try another method to sign

It's fine, i already have a working Spotify IPA. Was just curious as to why this one specifically doesn't work with scarlet when all the others I've tried do.

**Comment by KieranBLK** [comment]
> > So far this IPA is the only one thats giving me this issue when installing with Scarlet. It just fails to codesign the app every time for every Spotify IPA in this repo. Any idea why? 
> > 
> > ![image](https://user-images.githubusercontent.com/120525685/233354822-92bfc45b-cce2-42f0-90f1-cc8c45347cc5.png)
> 
> bro how can u download the youtube music ipa？

It's not from this repo. Got it from a different source.

**Comment by Nanki0722** [comment]
Ok bro> ipa？
