### ISSUE TITLE
[REQUEST] Loud Alarm Clock

### ISSUE THREAD

**Issue by dvl2014** [swaggyP36000/TrollStore-IPAs#460]
Hi, I was wondering if it would be possible to unlock everything as this is a very useful app for those who are heavy sleepers like myself. In the "coffee shop" there are options for upgrades but on the bottom right of the coffee shop there is an option that says "get everything".
Thanks for all you do! 

Appstore Link: https://apps.apple.com/us/app/loud-alarm-clock-the-loudest/id1146308678

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app but won't be uploaded into the repo.

You can download the latest version **[here](https://gofile.io/d/vDcI1y)**.

**Comment by dvl2014** [comment]
Hello @ArianaMinajj! I apologize for bothering you, I seem to have deleted the IPA, I tried to go back on the link you sent me and it says the files not available. Is there any chance you can re-upload it for me please

**Comment by ArianaMinajj** [comment]
Files hosted on Gofile expire if they are not downloaded for an extended period: I have reuploaded it **[here](https://gofile.io/d/YUMofc)**.

Please grab it in time as I won't be re-uploading that, thank you!
