### ISSUE TITLE
[REQUEST] Repair Spots POS Subscription

### ISSUE THREAD

**Issue by KurthVTM** [swaggyP36000/TrollStore-IPAs#463]
Hi, is it possible to have unlimited free subscription in this app, they only give 24 hour free.

https://apps.apple.com/us/app/repair-spots-pos/id1126615436

**Comment by ArianaMinajj** [comment]
Hello,

I'm unable to take that request as this app is locked under multiple conditions. You'll have to test it yourself using that **[ipa](https://gofile.io/d/7JeBCP)**.

I will not provide further assistance if it does not work.

PS: Sorry for the late reply!
