### ISSUE TITLE
[Request] ESPN+

### ISSUE THREAD

**Issue by dvl2014** [swaggyP36000/TrollStore-IPAs#466]
Hi! I am requesting if possible for ESPN+ 

Thank you for all you do! 

App Name: ESPN Live Sports & Scores
Request: ESPN+ 
App Store Link: https://apps.apple.com/us/app/espn-live-sports-scores/id317469184

**Comment by kadelw07** [comment]
> Hi! I am requesting if possible for ESPN+ 
> 
> Thank you for all you do! 
> 
> App Name: ESPN Live Sports & Scores
> Request: ESPN+ 
> App Store Link: https://apps.apple.com/us/app/espn-live-sports-scores/id317469184

Not possible
