### ISSUE TITLE
Request Camera+

### ISSUE THREAD

**Issue by kadelw07** [swaggyP36000/TrollStore-IPAs#467]
Hoping to a get a new cracked version of camera+ their new prices are insane. https://apps.apple.com/us/app/camera-pro-camera-editor/id1313580627

**Comment by ArianaMinajj** [comment]
Hello,

What do you mean by "new cracked version"? Was there a legacy crack for this app?

**Comment by kadelw07** [comment]
> Hello,
> 
> What do you mean by "new cracked version"? Was there a legacy crack for this app?

https://appdb.to/details/d774918a8ff64c361f84366518b31a42d24c0323 yes there's a few old versions on AppDB
