### ISSUE TITLE
[Request] OSLink

### ISSUE THREAD

**Issue by 0xNekochan** [swaggyP36000/TrollStore-IPAs#468]
It's an app that allow you to use your iPhone to connecting to your computer for emulating android games natively, similar to cloud gaming. I hope anyone could inject Satella or free in app purchases for VIP/SVIP membership.

App Link: https://apps.apple.com/us/app/oslink/id6444689630

Thanks!

**Comment by ArianaMinajj** [comment]
Hello,

You'll have to test it yourself using that **[ipa](https://gofile.io/d/aHkOBQ)**.

I will not provide further assistance if it does not work.
