### ISSUE TITLE
Spotify hifi unlocker isn't working properly

### ISSUE THREAD

**Issue by gototheskinny** [swaggyP36000/TrollStore-IPAs#47]
It should be like this: ![image](https://user-images.githubusercontent.com/51786709/233534081-2b29eef1-02fe-4ca9-9ed6-967c13d23f49.jpeg)

But it's like this:![image](https://user-images.githubusercontent.com/51786709/233534121-58568bd4-7c46-4379-b152-70ac658f7b97.jpeg)

I didn't test the literal sound quality with a headphone but legit version has a hifi toggle.

**Comment by gototheskinny** [comment]
Just tried again with a newly created account and it shows this: ![image](https://user-images.githubusercontent.com/51786709/233538766-7d491314-8a3d-496a-bdd8-8a67385a24a8.png)but not tried yet if it's a placebo or legit "hifi".

**Comment by swaggyP36000** [comment]
Not sure. The hifi should be legit but I have now way of confirming that. If there are updates for the Hi-Fi unlocker it'll be updated in a new release

**Comment by gototheskinny** [comment]
> Not sure. The hifi should be legit but I have now way of confirming that. If there are updates for the Hi-Fi unlocker it'll be updated in a new release

I don't have a way to confirm %100 either. Bluetooth connection doesn't have hifi label tho: ![image](https://user-images.githubusercontent.com/51786709/233540807-050b9c92-3902-4cc1-a636-45b2c3505400.jpeg)

**Comment by swaggyP36000** [comment]
I see.. I will keep this issue opened until a dev makes an update for this tweak

**Comment by gototheskinny** [comment]
> I see.. I will keep this issue opened until a dev makes an update for this tweak

I've just tried the same song on Spotify, Tidal, Apple Music with lossless enabled. Spotify is using only 5-6mb data, but others are 25+mb. It's not real it can't be without at least 20+mb data usage

**Comment by mbs0ft** [comment]
Hi-Fi unlock doesn't work and won't work if account is _freemium_
Even if you have Premium account, this also won't work: Spotify don't give access to this feature _yet_
Also, you can wait for [official release of new Premium plan.](https://www.reddit.com/r/truespotify/comments/16ntlnj/the_new_spotify_supremium_plan_with_lossless_and/)

**Comment by gototheskinny** [comment]
> Hi-Fi unlock doesn't work and won't work if account is _freemium_
> 
> Even if you have Premium account, this also won't work: Spotify don't give access to this feature _yet_
> 
> Also, you can wait for [official release of new Premium plan.](https://www.reddit.com/r/truespotify/comments/16ntlnj/the_new_spotify_supremium_plan_with_lossless_and/)

I know it's not available yet. I opened this issue bc **actually** there's no HIFI functionality for freemium nor premium accounts.
