### ISSUE TITLE
[Request] STBEmuTV (Pro)

### ISSUE THREAD

**Issue by Kishenpatel99** [swaggyP36000/TrollStore-IPAs#475]
https://apps.apple.com/us/app/stbemutv-pro/id1564403188

If possible, that’d be amazing!

**Comment by ArianaMinajj** [comment]
Hello,

You can find the latest version **[here](https://gofile.io/d/L4xYDy)**.

Please note that this won't be uploaded into the repo as AppCake already is hosting that **[app](https://www.iphonecake.com/app_1564403188_.html)**.
