### ISSUE TITLE
Rippple ios 15 ?

### ISSUE THREAD

**Issue by maplepy** [swaggyP36000/TrollStore-IPAs#476]
https://ripppleapp.com/

Is it possible to have that app for ios 15 or without the ios 17.0 requirement at least ?

Thank you very much :)

**Comment by ArianaMinajj** [comment]
Hello,

You'll have to test it yourself using that **[ipa](https://gofile.io/d/51Frru)**.

I will not provide further assistance if it does not work.

**Comment by maplepy** [comment]
It crashes instantly :(

**Comment by maplepy** [comment]
Hey @ArianaMinajj where did you find that ipa? did you do it yourself?

**Comment by ArianaMinajj** [comment]
I packaged it myself and removed the list of supported devices. 

Crash was most likely inevitable as it seems there's missing dependencies on iOS15 that the app exclusively requires for iOS17 devices? That is just my guess, sorry about that!

**Comment by maplepy** [comment]
yeah no worries ! is it hard to packages your own ipas? I'd love to try myself but the documentation i found online was pretty scarce

**Comment by ArianaMinajj** [comment]
Use ESign, Sideloadly, or manually edit it by unzipping the IPA file

**Comment by maplepy** [comment]
Thank you ! What repos do you use to get the tweaks usually ?

**Comment by ArianaMinajj** [comment]
Credits are mentioned for each app in the repo; you should check them out!

**Comment by ArianaMinajj** [comment]
But I already answered your question, ESign and Sideloadly provide signing services where ESign use free/paid certificate(s) and Sideloadly use your own Apple ID, as well as IPA packaging/export capabilities!

**Comment by maplepy** [comment]
so you package your ipa with sideloadly ? also for example fitnessai the credit is just a telegram author, there is no link or whatever to the tweak so that was my question
