### ISSUE TITLE
[Request] WebSSH

### ISSUE THREAD

**Issue by CreepsoOff** [swaggyP36000/TrollStore-IPAs#479]
https://apps.apple.com/fr/app/webssh-sysadmin-tools/id497714887

Hello, iOS 16.1.1 user here, app WebSSH needs 16.6 at least, could it be possible to get the IPA so I can install it ? My goal is to Port Forward :) Thank you!

**Comment by ArianaMinajj** [comment]
Hello,

You'll have to test it yourself using that **[ipa](https://gofile.io/d/FTJecy)**. *Pro features are unlocked using Satella*

I will not provide further assistance if it does not work.
