### ISSUE TITLE
Last 2 versions of BHtwitter are failing to install with 175 error.

### ISSUE THREAD

**Issue by Leone-Montana** [swaggyP36000/TrollStore-IPAs#48]
The last 2 updates of BHTwitter won't install resulting in 175 error with Trollstore. In my case the version 9.54 is the last one that installs with no problem.

**Comment by swaggyP36000** [comment]
Noted. I'll keep updating it in hopes that a newer version works but since I'm not on iOS 15 I won't be able to test myself. Sorry about that

**Comment by Leone-Montana** [comment]
Thx for your efforts in keeping it all updated, much appreciated

**Comment by Leone-Montana** [comment]
Latest updates is working ok, closing this. Thx
