### ISSUE TITLE
Flightradar24 IPA "phishing"

### ISSUE THREAD

**Issue by cursefroge** [swaggyP36000/TrollStore-IPAs#480]
The Flightradar24 IPA seems to attempt to phish the user's Apple ID. It opens a fake popup, asking for Apple ID and password, then takes you to settings and opens another popup (trying to seem more legitimate?).

**Comment by ArianaMinajj** [comment]
Hello,

You have not provided any specific information about the IPA in question, which makes it challenging to investigate your concern thoroughly.

Note that a lot of IPAs in the repo require users to connect using methods such as Google or Apple ID to unlock certain features like Gold access for example here. This is a standard practice for many tweaked apps.

Your allegation suggests that I'm uploading malicious IPAs into the repo which is quite concerning.. I take user trust very seriously and ensure all IPAs in this repo undergo rigorous checks.

This is your first and last warning regarding the spread of misinformation.

*If you believe my statement is incorrect, please provide proof evidence to support your claim. Thank you!*

**Comment by cursefroge** [comment]
I do not believe you are intentionally uploading malicious IPAs, however when I started the app, it prompted for my Apple ID details, saying my account was locked and required them to be unlocked, using a default iOS 2-field prompt. When I entered invalid credentials, it accepted them and attempted to take me to settings. I am not trying to accuse you of spreading malicious IPAs, merely raising my concerns and inquiring about why the IPA did this.

**Comment by cursefroge** [comment]
Just providing additional details

The prompt appeared on every fresh launch of the app. If I hit cancel, then started the app again, it would function as normal. This leads me to believe that the app’s launch opens the prompt, perhaps only under certain conditions.

**Comment by cursefroge** [comment]
![IMG_0163](https://github.com/swaggyP36000/TrollStore-IPAs/assets/49785023/8fa6655d-f3da-4ad7-be9c-0fcd885f3723)
![IMG_0162](https://github.com/swaggyP36000/TrollStore-IPAs/assets/49785023/e994cab7-cd8c-4f94-b1a9-6fb0137a5f95)
![IMG_0161](https://github.com/swaggyP36000/TrollStore-IPAs/assets/49785023/afdd093b-cd9b-4e4a-bbcb-c2c087b84cad)
![IMG_0160](https://github.com/swaggyP36000/TrollStore-IPAs/assets/49785023/17952fc3-849e-47ca-8126-0b2ba3f7601e)

Is this a legitimate message? I can sign in to my Apple account just fine, and this only occurs when opening the app. Is there some way to open Settings with a specified dialog? I accidentally cropped the last image too much, but it’s also while App Store is selected in Settings. Very sorry for any inconvenience caused if this is legitimate, but I believe Apple ID sign-ins must be authenticated with their own dedicated popup, or a web view. Correct me if I’m wrong.

**Comment by ArianaMinajj** [comment]
Thank you for the quick responses and the screenshots! The issue you're facing is understandable as it appears you've installed the app on iPadOS which isn't natively supported by the tweak maker. (Dell)

Note that this behavior also occurs when you're not using TrollStore to install IPAs and instead rely on other sideloading methods like Sideloadly or ESign. *(If that's the case, your issue remains invalid as this would be non-trollstore related)*

**Comment by cursefroge** [comment]
Hey! Thanks for the quick response. I was not using TrollStore to sign. Terribly sorry about that, but thanks for your understanding.
