### ISSUE TITLE
[request] INKHUNTER - AI Tattoo Designs Premium

### ISSUE THREAD

**Issue by blockearcash** [swaggyP36000/TrollStore-IPAs#489]
https://apps.apple.com/us/app/inkhunter-ai-tattoo-designs/id991558368

**Comment by ArianaMinajj** [comment]
Hello,

A tweak (Satella) is already available for this app and I'll upload it tomorrow!

You can download the latest version **[here](https://gofile.io/d/s9Nx09)** if you prefer not to wait.

**Comment by ArianaMinajj** [comment]
I've just uploaded it. Apologize for the delay; there was an issue that needed to be resolved.
