### ISSUE TITLE
Insta Regram Cracked

### ISSUE THREAD

**Issue by SakethKanchi** [swaggyP36000/TrollStore-IPAs#491]
There's a version of instagram regram cracked. And Other instagram tweaks too combined in one single ipa. I would highly suggest added it to the ipas list.

https://t.me/zxcvbn_tweaked/1046

**Comment by ArianaMinajj** [comment]
Hello,

I did not post that one combination of multiple tweaks into Instagram because it is extremely unstable. 

Instead, I already planned to post Instagram Regram Cracked, as it has incredible potential compared to Rocket!

**Comment by SakethKanchi** [comment]
> Hello,
> 
> I did not post that one combination of multiple tweaks into Instagram because it is extremely unstable.
> 
> Instead, I already planned to post Instagram Regram Cracked, as it has incredible potential compared to Rocket!

Yeah just regram cracked is also really good. And SCinsta instead of BHinsta is also really good.

**Comment by ArianaMinajj** [comment]
I just uploaded it!

**Comment by asdfzxcvbn** [comment]
> I did not post that one combination of multiple tweaks into Instagram because it is extremely unstable.

could you please clarify?

**Comment by ArianaMinajj** [comment]
I was exactly referring to that ipa (v333) you mentioned in your edited comment

**Comment by virtualcrane** [comment]
so whats better: Instagram Regram or InstaMulti?

**Comment by asdfzxcvbn** [comment]
> so whats better: Instagram Regram or InstaMulti?

multi is just a tweak manager. it would let you enable and disable regram (among other tweaks) at any time
