### ISSUE TITLE
AltStore repo is broken

### ISSUE THREAD

**Issue by yanivb380** [swaggyP36000/TrollStore-IPAs#496]
When I try to add the AltStore repo, I get the attached error.
I have tried with multiple devices and I got the same error, pls help
![AltStore error](https://github.com/swaggyP36000/TrollStore-IPAs/assets/172412831/6d7134da-f14a-498e-9b5b-59491f11af13)

**Comment by yanivb380** [comment]
May I know why is the request invalid?

**Comment by ArianaMinajj** [comment]
Hello,

This is another non-TrollStore related "issue" which makes it invalid.

Please take the time to review the existing issues and the sources supported by the repository. Thank you!
