### ISSUE TITLE
[Request] Shotsy+

### ISSUE THREAD

**Issue by Holmes31** [swaggyP36000/TrollStore-IPAs#497]
There is a premium version, Shotsy+. Would be great to have. 

https://apps.apple.com/us/app/shotsy-weight-loss-tracker/id6499510249

**Comment by ArianaMinajj** [comment]
Hello,

You can find the latest version **[here](https://gofile.io/d/3yeoLn)**.

Please note that this won't be uploaded into the repo.

**Comment by Holmes31** [comment]
Thank you!
