### ISSUE TITLE
Duolingo updated to the latest v/ link down below

### ISSUE THREAD

**Issue by gototheskinny** [swaggyP36000/TrollStore-IPAs#498]
[https://www.ipauniverse.com/2024/03/duolingo-language-lessons-v790.html?m=1](https://www.ipauniverse.com/2024/03/duolingo-language-lessons-v790.html?m=1)

**Comment by ArianaMinajj** [comment]
Hello,

- 1. The link you provided comes from a known **unsafe** source which is notorious for stealing and reuploading **my IPAs** from this repository.

- 2. This party has stolen the IPA from **[iOSGods](https://iosgods.com/topic/78624-duolingo-v7261-jailed-mod-1/)** *(where its containers and keychain groups are also absolutely broken)* and injected their own pop-ups.

- 3. Lastly, as stated in the repository guidelines, requesting updates is not allowed and has led to numerous invalid issues. *(Including yours)*

I'm confused how you thought it was ok to use that website as a source? Unless you were unaware of its reputation?

This is your first and final warning, thank you for your understanding!

**Comment by gototheskinny** [comment]
> Hello,
> 
> 1. The link you provided comes from a known **unsafe** source which is notorious for stealing and reuploading **my IPAs** from this repository.
> 
> 2. This party has stolen the IPA from **[iOSGods](https://iosgods.com/topic/78624-duolingo-v7261-jailed-mod-1/)** *(where its containers and keychain groups are also absolutely broken)* and injected their own pop-ups.
> 
> 3. Lastly, as stated in the repository guidelines, requesting updates is not allowed and has led to numerous invalid issues. *(Including yours)*
> 
> I'm confused how you thought it was ok to use that website as a source? Unless you were unaware of its reputation?
> 
> This is your first and final warning, thank you for your understanding!

I thought the previous version were from there(maybe I'm wrong but I remember something about this ipas source was that source). That's why I linked that site, 

I Knew it was "problematic" but this "duolingo tweak whatever the fuck ipa" isn't common at all, thats why I thought maybe you made an exception added that ipa. I'm sorry for misunderstanding the situation, thank you for your work and maintaining this repo, I appreciate it.
