### ISSUE TITLE
Addons

### ISSUE THREAD

**Issue by hoangdlnhat** [swaggyP36000/TrollStore-IPAs#499]
it’s possible to have this app with premium unlocked?

https://apps.apple.com/vn/app/addons-%E6%B5%8F%E8%A7%88%E5%99%A8%E6%89%A9%E5%B1%95%E6%8F%92%E4%BB%B6%E5%B9%BF%E5%91%8A%E6%8B%A6%E6%88%AA/id6446811843?l=vi

**Comment by ArianaMinajj** [comment]
Hello,

There's already a tweaked version of this app but after testing, it appears to be not working with Safari. 

As a result I won't be uploading it, sorry about that!
