### ISSUE TITLE
Adguard Pro ipa doesn't work

### ISSUE THREAD

**Issue by gototheskinny** [swaggyP36000/TrollStore-IPAs#5]
It's not working at all like other ipas on appdb or other places.

**Comment by swaggyP36000** [comment]
Opens and runs fine for me. Is it a crash on launch, or is a specific feature not working?

**Comment by gototheskinny** [comment]
> Opens and runs fine for me. Is it a crash on launch, or is a specific feature not working?

This app is an adblock extension for safari but its not loading and updating the filters. Stucks at "Updating". I think this and other sideloaded safari Extensions will never work without jailbreak even with trollstore. This and other sideloaded safari apps needs some other permissions to work properly.

**Comment by swaggyP36000** [comment]
Ah, I see the issue now. I'll remove it from the library until someone releases a TrollStore specific update

**Comment by gototheskinny** [comment]
> Ah, I see the issue now. I'll remove it from the library until someone releases a TrollStore specific update 

I think that update will never come but we can always hope.

**Comment by swaggyP36000** [comment]
Given that the app isn't using entitlements that TrollStore just can't support, it's a possibility
