### ISSUE TITLE
Twitch+ Ads showing

### ISSUE THREAD

**Issue by TuffestLeader** [swaggyP36000/TrollStore-IPAs#50]
Just updated to the latest v15.1 twitch+ ipa and I'm getting ads. I confirmed it's enabled in the settings, tried. turning it on / off, same for proxy, closing and reopening, etc.

**Comment by swaggyP36000** [comment]
Tried it twice. Not sure what the issue is but I haven't seen a single ad in-app

**Comment by TuffestLeader** [comment]
Yeah I’m defiantly getting ads more than half the time. I have this installed on my iPhone and iPad. I’ve tried turning Adblock on and off, rebooting, etc. Running the latest release. I’m in Canada, if that somehow helps. Lmk if there’s anything I do

**Comment by swaggyP36000** [comment]
I am not sure. Tried it both ways and no ads appeared. Tested on stock iOS 14.4

**Comment by TuffestLeader** [comment]
So weird! I’m on iOS 15/16 and ads are constantly coming when I first load the stream. Not sure if they come in after that, I’ll try to take note. I did try to uninstall and start fresh with the latest IPA but it still has ads.

**Comment by thexYeti** [comment]
Not sure if this is really still open. 

For anyone looking for a fix though, use twitchadblock by level3jg and enable low latency player, works very well
