### ISSUE TITLE
[Request] MyRadar Weather Radar Pro

### ISSUE THREAD

**Issue by Holmes31** [swaggyP36000/TrollStore-IPAs#501]
https://apps.apple.com/us/app/myradar-weather-radar-pro/id325683306

**Comment by ArianaMinajj** [comment]
Hello,

You can find the latest version **[here](https://gofile.io/d/Z416xj)**.

Please note that this won't be uploaded into the repo as AppCake already is hosting that **[app](https://iphonecake.com/app_325683306_.html)**.
