### ISSUE TITLE
How to remove saved login infos on Instagram

### ISSUE THREAD

**Issue by dvl2014** [swaggyP36000/TrollStore-IPAs#502]
Everytime I download InstagramRocket when i first open the app I see profiles of previously signed in users I used on it. I tried deleted, reinstalling, restarting phone, etc. but the profiles are always there no matter what. I tried downloading the app store version of instagram and when i open it never shows the profiles. Only when i download instagram rocket, is there any way for me to clear the profiles when i try to install instagram rocket? Maybe its a locally stored folder for my profiles or something since only instagram rocket remembers the profiles not the regular instagram app. I have an iPhone 14, and I use eSign. Hope you can help me!! First photo is what I see everytime I download instagram through app store and other photo is what i see everytime I open instagram rocket for first time regardless of deleting, reinstalling, etc. profiles are saved for some reason only for Instagram rocket and dont know how to clear/remove it! 

![image](https://github.com/swaggyP36000/TrollStore-IPAs/assets/61545683/787dce8b-8ee9-4783-a186-9af6a5fba791)

![image](https://github.com/swaggyP36000/TrollStore-IPAs/assets/61545683/34318d8f-393c-4b2b-ba57-4504589a11bc)

**Comment by ArianaMinajj** [comment]
Hello,

While your question isn't related to Rocket nor TrollStore I still can assist you!

Login data is stored locally on your device giving you two ways to delete them:

1. Use Apps Manager to wipe Instagram’s data.

2. Tap the three dots in the upper right corner of Instagram (as shown in the second screenshot you provided) and manually delete the logins by selecting the "remove" option.

**Comment by dvl2014** [comment]
What app manager do you suggest? And yes i tried deleting profiles with the top right three dot option and it doesnt let me ![image](https://github.com/swaggyP36000/TrollStore-IPAs/assets/61545683/bde7d365-f68e-4b12-89dd-e108c06337fe)

**Comment by ArianaMinajj** [comment]
Apps Manager is the name of an app that is available on this repository.

Install it using TrollStore then proceed to wipe its data.

**Comment by ArianaMinajj** [comment]
Redirect your issue somewhere else
