### ISSUE TITLE
[Request] SnapEdit

### ISSUE THREAD

**Issue by dvl2014** [swaggyP36000/TrollStore-IPAs#504]
App Name: SnapEdit
Feature Request: Pro Unlocked
App Store Link: https://apps.apple.com/us/app/snapedit-remove-objects-ai/id1611282499

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app and I'll upload it in a few hours!

You can download the latest version **[here](https://gofile.io/d/lYyGBr)** if you prefer not to wait.

**Comment by adrianmihalko** [comment]
Hi,

there are apps where we need to push on subscribe button to get pro version. If I login with my appstore account, I get:

“ You are not authorised to make purchases of this InApp in Sandbox at this time.
This Apple Account does not have permission to make In-App Purchases.
You can change account permissions in App Store Connect.
[Environment: Sandbox]”

How can I make it work?

Example apps: Snapedit pro, Speedometer
