### ISSUE TITLE
Need Help Clearing Cached Files (Documents and Data) Without Deleting and Reinstalling the App

### ISSUE THREAD

**Issue by EAP7-hub** [swaggyP36000/TrollStore-IPAs#505]
Hey! Question,

I’m trying to figure out how to clear the Instagram cache within the Instagram Regram hack, which is still in beta. In the BHInstagram hack available on GitHub, there’s an option to open Flex Explorer within the settings of BHInsta and clear some cache files. However, the Instagram Regram hack doesn’t have the Flex Explorer option to remove these cache files. What can I do?

Thanks in advance!

**Comment by ArianaMinajj** [comment]
Hello,

In the Regram settings under "Contact & More" there's an option to clear Instagram's caches without deleting its documents and that's the only clearing feature available.

To completely wipe Instagram's data, you'll need to use "Apps Manager" which is available in the repository.
