### ISSUE TITLE
[Request] Gentler Streak Fitness Tracker

### ISSUE THREAD

**Issue by lizmoew** [swaggyP36000/TrollStore-IPAs#506]
App Name: Gentler Streak Fitness Tracker
Feature Request: Pro Unlocked
App Store Link: https://apps.apple.com/us/app/gentler-streak-fitness-tracker/id1576857102

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app and I'll upload it in a few hours!

You can download the latest version **[here](https://gofile.io/d/bDBoTN)** if you prefer not to wait.

**Comment by janvidaal** [comment]
It closes when I open it. How can I solve it?

**Comment by lizmoew** [comment]
> Hello,
> 
> A tweak is already available for this app and I'll upload it in a few hours!
> 
> You can download the latest version **[here](https://gofile.io/d/bDBoTN)** if you prefer not to wait.

Thank you but crash app when open. Can you check again?
