### ISSUE TITLE
Request - PDF it All Document Converter

### ISSUE THREAD

**Issue by SaifeeMir** [swaggyP36000/TrollStore-IPAs#508]
Request to have a free working version of paid subscription based application https://apps.apple.com/sa/app/pdf-it-all-document-converter/id627640657

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app and I'll upload it in a few hours!

You can download the latest version **[here](https://gofile.io/d/EipLrM)** if you prefer not to wait.

**Comment by SaifeeMir** [comment]
Oh dear! I can’t believe how fast you did it!!!
Many thanks!!!
Do you have paypal or any way I can buy you a coffee?

Thanks
Best Regards
Saifee Mir

**Comment by ArianaMinajj** [comment]
You're welcome! Your support through starring or sharing this repo would be greatly appreciated!
