### ISSUE TITLE
[Request] Surround - Online Go client for iOS

### ISSUE THREAD

**Issue by jiucenglou** [swaggyP36000/TrollStore-IPAs#510]
Request to get the free version of [Surround - Online Go client for iOS](https://apps.apple.com/us/app/surround-online-go-client/id1535010544)

**Comment by jiucenglou** [comment]
could you suggest what is valid request ? :D

**Comment by ArianaMinajj** [comment]
Hello,

Games are not allowed on this repo. *(This was stated multiple times already)*

You'll have to request apps only, thank you!
