### ISSUE TITLE
Instagram (v336.08) break Rocket:  Grid Layout functionality limited

### ISSUE THREAD

**Issue by tmpss88loq** [swaggyP36000/TrollStore-IPAs#513]
Version: 336.0.8-3.8.25
when on "Grid Layout" mode, nothing happen after clicking any post.

**Comment by ArianaMinajj** [comment]
Hello,

The latest version of Instagram has a known compatibility issue that appears to have broken the Grid Layout functionality, limiting interactions to just the download feature. *(long-press context)*

Please wait for a fix or switch to a lower version for now, thank you!

**Comment by tmpss88loq** [comment]
On a lower version (334.0.0-3.8.24), stories on top are gone on Grid Layout mode. So I think maybe it will work fine on this pair: 335.0.0-3.8.25
But nvm, lets wait for a fix :)

**Comment by ArianaMinajj** [comment]
This issue has been resolved in the latest version of rocket (3.8.24) and is available in the latest release.
