### ISSUE TITLE
[Request] Salatuk App

### ISSUE THREAD

**Issue by CiroHoodLove** [swaggyP36000/TrollStore-IPAs#515]
hello , the **Muslim Pro** app and **Athan Pro** didn’t seem to work (both quit right after i click on them) tried other versions from other repo’s but widgets and basically most paid features didn’t work , was wondering if you can look into them because the emoji (✅) indicates they are working , if it isnt possible i wonder if you can upload the **Salatuk** App , thanks in advance

https://apps.apple.com/us/app/salatuk-%D8%B5%D9%84%D8%A7%D8%AA%D9%83/id686077611

**Comment by ArianaMinajj** [comment]
Hello,

I must regretfully deny your request and mark it as invalid due to the considerable amount of misinformation it contains.

Please take time to **read** carefully the README.md, especially the "additional information" part. Thank you!
