### ISSUE TITLE
[Request] Panels 3

### ISSUE THREAD

**Issue by mxrtnez** [swaggyP36000/TrollStore-IPAs#518]
App Name: Panels 
Feature Request: **Panels 3**
Link: https://apps.apple.com/es/app/panels-comic-reader/id1236567663

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app and I'll upload it in a few hours!

You can download the latest version **[here](https://gofile.io/d/wv4N71)** if you prefer not to wait.
