### ISSUE TITLE
CarPlay Spotify Issue

### ISSUE THREAD

**Issue by Leone-Montana** [swaggyP36000/TrollStore-IPAs#52]
Latest Spotify upload seems to break the CarPlay functionality. Doesn't appear in menu, so no way to add it to CarPlay.

**Comment by swaggyP36000** [comment]
Thought it was working from what I could tell. I'll test this more when i get the chance

**Comment by Leone-Montana** [comment]
Thanks, I will do some more testing myself as well, to make sure it's not one off thing

**Comment by Leone-Montana** [comment]
Latest update seems to fix the CarPlay issue. Thx
