### ISSUE TITLE
[Request] OBDeleven 

### ISSUE THREAD

**Issue by BStyle69** [swaggyP36000/TrollStore-IPAs#520]
https://apps.apple.com/us/app/obdeleven-vag-car-diagnostics/id1458334123

Hallo, it's possible to have this app with premium content? thx

**Comment by BStyle69** [comment]
Of course, as soon as I try it I'll tell you if it works. Thanks again!

**Comment by BStyle69** [comment]
Unfortunately not work, on iOS 16.5 (iPad Pro and iPhone 13 pro)

![748FD8E1-025F-4420-9F8F-169D135122E1](https://github.com/swaggyP36000/TrollStore-IPAs/assets/48559242/f9a316de-2184-463f-9db0-4d75507588ca)
![36C219A6-E1BD-4BFA-9EBC-6F4EF5939146](https://github.com/swaggyP36000/TrollStore-IPAs/assets/48559242/a2638e67-5116-406b-bfc0-965b1c80ff40)
![9E5AA831-3EC9-4BBD-AA6B-0077384E81E1](https://github.com/swaggyP36000/TrollStore-IPAs/assets/48559242/95968d67-0fc6-4f7a-9c44-86231504287b)

**Comment by ArianaMinajj** [comment]
Apologies for the inconvenience, the features may be server-side or the tweak might just not be working at all.

**Comment by BStyle69** [comment]
Thx 🙏🏻
