### ISSUE TITLE
[Request] Shotsy+ Update

### ISSUE THREAD

**Issue by Holmes31** [swaggyP36000/TrollStore-IPAs#521]
Can you update to the latest version 1.0.3?

https://apps.apple.com/us/app/shotsy-glp-1-shot-tracker/id6499510249

**Comment by Holmes31** [comment]
Are you not able to update the app?

**Comment by Holmes31** [comment]
@ArianaMinajj

**Comment by ArianaMinajj** [comment]
Hello,

Please take time to read carefully the README.md, especially the "additional information" part. Thank you!

**This is your final and last warning**
