### ISSUE TITLE
[Request] CapyMood

### ISSUE THREAD

**Issue by KurthVTM** [swaggyP36000/TrollStore-IPAs#529]
Hi, please I would like to request the full unlocked features of this app. Thanks.

https://apps.apple.com/us/app/capymood-daily-stress-tracker/id6471785489

**Comment by ArianaMinajj** [comment]
Hello,

You can find the latest version **[here](https://gofile.io/d/Mv6N9s)**.

Please note that this won't be uploaded into the repo.
