### ISSUE TITLE
Cannot log into google 

### ISSUE THREAD

**Issue by gnagnabeubla** [swaggyP36000/TrollStore-IPAs#53]
I sideloaded the 1.4.1 app using Alststore on an iphone 13 pro with iOS 16.5 and could not log into google it says "google couldnt verify that the app is not unsafe"

**Comment by gnagnabeubla** [comment]
I managed to connect after having logged in into other apps and trying again but it it still kind of odd that I couldnt to begin with

**Comment by swaggyP36000** [comment]
I'm not following, what app were you trying?
