### ISSUE TITLE
[Req] Updated version for BHTikTok Plus

### ISSUE THREAD

**Issue by mxrtnez** [swaggyP36000/TrollStore-IPAs#536]
Please, is it possible to update the BHTikTok Plus to a newer version? Thanks

**Comment by mxrtnez** [comment]
Why isn't it valid if you don't mind me asking?

**Comment by ArianaMinajj** [comment]
Hello,

The repo clearly states that updates are prohibited. 

Please take a moment to read carefully, as this is causing an unusually high number of invalid issues, including yours.

Also note that **BHTiktok Plus is unable to work on version above >34.1.0 without experiencing a crash in the tweak menu.**
