### ISSUE TITLE
[Request] Infuse for tvOS

### ISSUE THREAD

**Issue by GuyKh** [swaggyP36000/TrollStore-IPAs#538]
As [Suffuse-Team](https://github.com/Suffuse-Team/suffuse-team.github.io) left the business, is there any "new" way to install Infuse Pro for tvOS?

(perhaps also - remove the Suffuse link)

**Comment by ArianaMinajj** [comment]
Hello,

I credited Suffuse once because I grabbed one ipa from them in 2023.

Every single releases are mostly from **[InfusePlus](https://github.com/dayanch96/InfusePlus)**, so have you considered using their IPAs instead? Or those are not compatible with tvOS? *(I don't know anything about tvOS)*

**Comment by GuyKh** [comment]
> Hello,
> 
> I credited Suffuse once because I grabbed one ipa from them in 2023.
> 
> Every single releases are mostly from **[InfusePlus](https://github.com/dayanch96/InfusePlus)**, so have you considered using their IPAs instead? Or those are not compatible with tvOS? _(I don't know anything about tvOS)_

I'm not sure myself. Using sufface old version and too scared to try (and uninstalling a working old version).

Has anyone tried?
