### ISSUE TITLE
Request: add Narwhal 2 for Reddit with free premium

### ISSUE THREAD

**Issue by calvincorrieri** [swaggyP36000/TrollStore-IPAs#539]
Idk if this could be done with Satella since it’s a subscription but it would be awesome to have it. 
I saw that someone requested AddonsPro premium and it was added, I’m hoping this can be too.

**Comment by ArianaMinajj** [comment]
Hello,

Can you please use the request template *(refer to examples from others)* and include a direct link to the app, thank you!
