### ISSUE TITLE
Are all of these confirmed to be safe

### ISSUE THREAD

**Issue by lukar-debug** [swaggyP36000/TrollStore-IPAs#54]
Have all of these been checked to be safe?

Also there's a grammar mistake in the beginning as the author of this repository misspelled currently

**Comment by swaggyP36000** [comment]
As far as I've tried, these apps are fine to use. Where exactly is the grammar mistake? I just checked and the ReadMe is correct from what I can see

I won't be able to change anything anytime soon as I'm in the process of moving and my computer is currently packed away. I'll be able to get started on updating everything regularly in a couple weeks or so

**Comment by swaggyP36000** [comment]
Forgot to mentinon it here but I fixed that typo. Lmk if you see any more
