### ISSUE TITLE
Instagram Regram Cracked

### ISSUE THREAD

**Issue by Cinytax** [swaggyP36000/TrollStore-IPAs#545]
The latest version requires a license. I can't use the features. (InstagramRegramCracked-338.0.0-1.0b8.ipa)

![IMG_1315](https://github.com/swaggyP36000/TrollStore-IPAs/assets/132007279/babfaac7-7fd3-406f-ad94-6ee6f58199e4)

**Comment by WvBijsterveld** [comment]
idk if it’s the same but i’m using one where you will login with patreon, get the free tier(just one click no fees or anything) then in the app it will say you have it, if not click restore purchases then it should work.

**Comment by LenardValdez** [comment]
> idk if it’s the same but i’m using one where you will login with patreon, get the free tier(just one click no fees or anything) then in the app it will say you have it, if not click restore purchases then it should work.

Can confirm, you just have to sign up(use sign up with apple and hide email and name) then just click the "subscribe for free" button
