### ISSUE TITLE
Boostcamp Pro Not Working

### ISSUE THREAD

**Issue by TheRealCasmat** [swaggyP36000/TrollStore-IPAs#550]
Hey!

Boostcamp Pro was not working? I’m using SideStore, app works just as it is when downloaded from App Store, no tweaks visible

**Comment by WvBijsterveld** [comment]
if you haven’t tried, try clicking on to purchase the pro, or to restore purchases.

**Comment by TheRealCasmat** [comment]
Still not working

**Comment by WvBijsterveld** [comment]
> @WvBijsterveld Still not working

i just installed via appdb and i'm getting a annual subscription that ends in 9692 so download again and make sure you don't already have it installed i guess?

**Comment by TheRealCasmat** [comment]
@WvBijsterveld did it ask you to sign in when first opening?

**Comment by WvBijsterveld** [comment]
@TheRealCasmat 
yes it asked me like 600 questions and then i just made a account with hide my email and 1 letter name. so if you're logged in (using the  cracked ipa) then you should have premium

**Comment by TheRealCasmat** [comment]
@WvBijsterveld interesting, I deleted it and reinstalled but it still isn’t working… I also used the appdb download link, then imported to sidestore

**Comment by WvBijsterveld** [comment]
@TheRealCasmat weird. and you're sure you're downloading the ipa from swaggy's repo on appdb instead of the default ipa?

https://appdb.to/details/4896031120630111e03d6e4c386e334e0e5f7f72

try installing with another signing program/service. else just try to start from beginning ; clear download folder to ensure you have the correct ipa and walk through the steps carefully.

**Comment by TheRealCasmat** [comment]
@WvBijsterveld just retried with sideloadly and different Apple ID, still no luck, did you see different things than what you see in the images?
![IMG_0303](https://github.com/swaggyP36000/TrollStore-IPAs/assets/68253033/93cd7b96-3de5-467b-82ce-3a8bed54125c)
![IMG_0304](https://github.com/swaggyP36000/TrollStore-IPAs/assets/68253033/ebc59ac3-63fc-4432-b0a5-88b9e915c7f9)

**Comment by WvBijsterveld** [comment]
@TheRealCasmat 
hmm idk something's not right. maybe try installing via appdb using a free certificate (if available) i just logged in and everything regarding pro never appears.![image](https://github.com/swaggyP36000/TrollStore-IPAs/assets/14361841/bc8ccfaf-6503-404e-95c4-0175d978d7d1)
![image](https://github.com/swaggyP36000/TrollStore-IPAs/assets/14361841/e988610c-c190-4fad-b049-4f668320c358)

**Comment by TheRealCasmat** [comment]
@WvBijsterveld what iOS are you running?

**Comment by WvBijsterveld** [comment]
@TheRealCasmat ios 18 dev beta, however as far as i know that shouldn't influence anything.
have you deleted the original app store app before installing the ipa via side store?

**Comment by TheRealCasmat** [comment]
@WvBijsterveld yup I’m on 17.5.1, I don’t know if it’s holding data from the App Store version as it auto logged me into the ipa automatically from my App Store version account, I logged out and tried again but no luck, also tried on an SE also on 17.5.1, but the same thing happened using sideloadly. Couldn’t get appdb to work for some reason, pressing install on the app listing just gives me an error popup saying:
`To install apps to this device, you need to [choose desired way of sideloading](https://appdb.to/my/buy). We recommend you to use only official sideloading with your own developer account purchased from Apple, so you can sideload unlimited amount of apps and face no revocations`

**Comment by WvBijsterveld** [comment]
@TheRealCasmat idk how to do it but try installing it as a duplicate app. also try installing from app store, then log out then delete the app. after that install the ipa again from sideloadly or side store. if that doesn't work i'm gonna try to send you my signed ipa as a duplicate app after that i don't have any more ideas.

**Comment by TheRealCasmat** [comment]
@WvBijsterveld yeah it’s still not budging, if you could share your ipa, that’d be worth a shot! Thanks

**Comment by WvBijsterveld** [comment]
https://www.dropbox.com/scl/fi/ms2pset6nqe6czxcm5dt3/BoostcampPro-212.ipa?rlkey=b0cee6c2onmulu87g6j3bgm62&st=matis5ix&dl=0

Install using sideloadly and click advanced options and signing method> normal install.

**Comment by TheRealCasmat** [comment]
@WvBijsterveld hmm, tried and sideloadly throws an error towards the end of the process saying 
3892346881 ApplicationVerificationFailed (Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.TWmeaZ/extracted/Payload/Boostcamp.app : 0xe8008001 (An unknown error has occurred.))

**Comment by WvBijsterveld** [comment]
no idea then.
@TheRealCasmat

**Comment by TheRealCasmat** [comment]
@WvBijsterveld thanks for your help!

**Comment by WvBijsterveld** [comment]
@TheRealCasmat no problem!
