### ISSUE TITLE
[REQUEST] Money Manager No Ads Version

### ISSUE THREAD

**Issue by josephlee25** [swaggyP36000/TrollStore-IPAs#552]
https://apps.apple.com/us/app/money-manager-expense-budget/id560481810
Hi, can you please tweak this app to the no ads version below? Your effort is highly appreciated. 
https://apps.apple.com/us/app/money-manager-remove-ads/id564730202

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app and I'll upload it in a few hours!

You can download the latest version **[here](https://gofile.io/d/qJvXfI)** if you prefer not to wait.

**Comment by josephlee25** [comment]
Thank you so much for the tweak! Awesome job 👍
