### ISSUE TITLE
[Request] Concepts Pro

### ISSUE THREAD

**Issue by unblankxd** [swaggyP36000/TrollStore-IPAs#558]
The free version is extremely limited in its features and I would forever be grateful if you could help.
Other websites do have it but they are all 6+ versions behind (Newest I could find was 6.8.8, actual is 6.14.2)
https://apps.apple.com/us/app/concepts/id560586497
https://concepts.app/en/

Cheers!

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app and I'll upload it in a few hours!

You can download the latest version **[here](https://gofile.io/d/FjjCtD)** if you prefer not to wait.

*Note: Connect using your Apple ID and only make the one-time purchases. (Purchasing may result in multiple severe app freezes)*

**Comment by unblankxd** [comment]
App crashes whenever loading in - it has not been signed into or anything. Nothing seems out of the ordinary... 
Sideloaded using Apple ID via Sideloadly

**Comment by ArianaMinajj** [comment]
The app will be added despite the "issue" you're experiencing:

No support will be offered because this is unrelated to Trollstore (invalid), similar to many past issues you likely didn't bother reading. Please read the repository guidelines thoroughly, thank you!

**Comment by Chris2004m** [comment]
App crashes upon installation for me too

**Comment by aasutossh** [comment]
@unblankxd do you have the older working ipa? I am unable to find it anywhere.
