### ISSUE TITLE
[Request] VideoViewer Pro

### ISSUE THREAD

**Issue by st-ivan** [swaggyP36000/TrollStore-IPAs#559]
Can you please add this modified ipa

https://apps.apple.com/us/app/videoviewer-pro/id6453359966?l=es-MX

**Comment by st-ivan** [comment]
hi, care to explain why invalid?

**Comment by ArianaMinajj** [comment]
Hello,

This app appears to work only on iPadOS devices.

This repo only takes requests for iOS device, sorry about that!

**Comment by st-ivan** [comment]
gotcha! thanks for your time and work.
