### ISSUE TITLE
TikTokLRD 30.0.0 have different Bundle ID and App name 

### ISSUE THREAD

**Issue by mbs0ft** [swaggyP36000/TrollStore-IPAs#56]
![IMG_5599](https://github.com/swaggyP36000/TrollStore-IPAs/assets/22106304/e2d5c7c6-4687-445d-9936-25e84a5b6390)

**Comment by swaggyP36000** [comment]
Mistake on my part. Will fix this shortly

**Comment by mbs0ft** [comment]
> Will fix this shortly
Already did with Sideloadly!

https://www.dropbox.com/s/rgjwxx010jv4lio/TikTokLRD-30.0.0%20Modified.ipa?dl=0

**Comment by swaggyP36000** [comment]
Mind that some apps altered through ModMyIPA will have different names but will be under the same bundleID's
