### ISSUE TITLE
BHTikTok Plus's settings crash on 35.1.0 version

### ISSUE THREAD

**Issue by sonnee4** [swaggyP36000/TrollStore-IPAs#560]
Yeah, status say that app was checked and it working well, but for me it’s crashing

**Comment by GunnarOgNils** [comment]
Can you fix it?

**Comment by c12n** [comment]
Downgrade to 32.9.1 

Apply your settings then upgrade to 35.1.0 

[Here](https://t.me/SultanModsIPAs/102)

**Comment by ArianaMinajj** [comment]
Hello @c12n ,

I removed your comment because it appeared to be self-promotion for your Telegram channel and **it reiterated information already provided in BHTikTok's description**.

This so-called "issue" is invalid because those two unknown people clearly didn't bother to read anything.

**Comment by c12n** [comment]
M'kay

**Comment by GunnarOgNils** [comment]
I understand but i cant find the description

**Comment by GunnarOgNils** [comment]
Thank you

lør. 13. juli 2024 kl. 21:19 skrev c12n ***@***.***>:

**Comment by GunnarOgNils** [comment]
But where do i find the description
