### ISSUE TITLE
[Request] Growlr Pro

### ISSUE THREAD

**Issue by cosmicfl0w** [swaggyP36000/TrollStore-IPAs#561]
hii so i've been using this dating app called Growlr and been looking for a way to get the premium version? the subscription is really expensive since i don't live in the usa. i hope u can help me and thank u for ur efforts!

the link to the app: https://apps.apple.com/us/app/growlr-gay-bears-near-you/id393402212

features i want: the pro version or even a way to unblur private photos

**Comment by ArianaMinajj** [comment]
Hello,

It is evident that all dating apps are entirely server-based and cannot be cracked or have their features unlocked by any means.

However, Grindr is the only gay dating app that has a tweak available but this is only for Android users. 

Sorry about that!

**Comment by cosmicfl0w** [comment]
> Hello,
> 
> It is evident that all dating apps are entirely server-based and cannot be cracked or have their features unlocked by any means.
> 
> However, Grindr is the only gay dating app that has a tweak available but this is only for Android users. 
> 
> Sorry about that!

oh no :(( thank u for the quick reply tho!
