### ISSUE TITLE
Kodi -"Missing" tvOS link

### ISSUE THREAD

**Issue by Burna91** [swaggyP36000/TrollStore-IPAs#562]
The given link to the external website that hosts Kodi for tvOS does not work with Trollstore on Apple TV. It requires the direkt URL link that ends with “.ipa” and the link is not obtainable.

**Comment by ArianaMinajj** [comment]
Hello,

I noticed some misinformation in your message: The "missing" tvOS link you're referring to is actually available [here](https://github.com/swaggyP36000/TrollStore-IPAs/issues/91). *(As a result, your "issue" is not valid)*

Additionally, please direct any discussions related to Kodi to this [closed request](https://github.com/swaggyP36000/TrollStore-IPAs/issues/91). thank you!
