### ISSUE TITLE
[Request] Doppler 3

### ISSUE THREAD

**Issue by hollfol** [swaggyP36000/TrollStore-IPAs#567]
thank you so much for all your work 
can you unlock the full version of this app?

https://apps.apple.com/us/app/doppler-mp3-flac-player/id1468459747

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app and I'll upload it tomorrow!

You can download the latest version **[here](https://gofile.io/d/N1xfns)** if you prefer not to wait.
