### ISSUE TITLE
[Request] PhotoGrid Pro

### ISSUE THREAD

**Issue by hamidmirza** [swaggyP36000/TrollStore-IPAs#568]
Hello,
Please ~~create an IPA for these two apps~~. Thank you for your work. 

https://apps.apple.com/pk/app/photogrid-video-collage-maker/id543577420

~~https://apps.apple.com/pk/app/b612-ai-photo-video-editor/id904209370~~

**Comment by ArianaMinajj** [comment]
It looks like you're requesting tweaked versions of 2 apps but you were advised (a few hours ago) to submit **one request at a time.**

Therefore, I'll only consider PhotoGrid here, so please (for the second time) open a separate request for each app. *(In your case, you'll have to open an separate request for the "B612" app)*

Thank you!

**Comment by ArianaMinajj** [comment]
A tweak is already available for PhotoGrind and I'll upload it tomorrow!

You can download the latest version **[here](https://gofile.io/d/QX2sPv)** if you prefer not to wait.
