### ISSUE TITLE
Snapchat Falcon Crashing

### ISSUE THREAD

**Issue by TronziaHQ** [swaggyP36000/TrollStore-IPAs#57]
I just got a feeling and just wanted to try it out, I installed the latest updated version on it with TrollStore and installation went fine.

But now when I try to open the app it crashes and I see a blurred out Box with the number one on it. Nothing else. I also see my account around it.

The picture Is what I see for a split second before it forcefully closes the app.

![1B6FD81C-554C-4FF2-BA72-77F210D88B2F](https://github.com/swaggyP36000/TrollStore-IPAs/assets/100530921/4c91bcb8-bcfc-4973-928a-0903b63ce937)

**Comment by swaggyP36000** [comment]
Does this happen on other versions of the Falcon IPA or only this one?

**Comment by TronziaHQ** [comment]
I’ll try out an older version of it right now.

**Comment by TronziaHQ** [comment]
Getting the same crash on the version from the May 24 release

**Comment by swaggyP36000** [comment]
Interesting.. I have seen some people getting this to work, but most are having issues. I'll note this issue on the ReadMe and contact the dev about it

**Comment by asdfzxcvbn** [comment]
this happens when you've been jailbroken before -- falcon doesnt work on jailbroken devices

**Comment by TronziaHQ** [comment]
> this happens when you've been jailbroken before -- falcon doesnt work on jailbroken devices

Really? And why’s that?. I tried the apps when I wasn’t jailbroken too.

**Comment by asdfzxcvbn** [comment]
it works perfectly fine when you've never jailbroken before, but im pretty sure if it detects any leftover jb files then it doesnt work

> > this happens when you've been jailbroken before -- falcon doesnt work on jailbroken devices
> 
> Really? And why’s that?. I tried the apps when I wasn’t jailbroken too.

**Comment by TronziaHQ** [comment]
> it works perfectly fine when you've never jailbroken before, but im pretty sure if it detects any leftover jb files then it doesnt work
> 
> > > this happens when you've been jailbroken before -- falcon doesnt work on jailbroken devices
> > 
> > 
> > Really? And why’s that?. I tried the apps when I wasn’t jailbroken too.

 "Pretty sure" Yeeah if Snapchat had jailbreak detection it wouldn't be a popular app. It's not the cause for the crash.

**Comment by TronziaHQ** [comment]
Oh and normal Snapchat works flawlessly. So no that's not the cause for the crash.

**Comment by swaggyP36000** [comment]
This is known to be hit-and-miss for some users. I am unsure if the dev is aware of it but I have already reached out to them about it. I don't see how the "normal version of x app works" statement applies here because, that is generally how all normal versions of apps work.

**Comment by asdfzxcvbn** [comment]
> > it works perfectly fine when you've never jailbroken before, but im pretty sure if it detects any leftover jb files then it doesnt work
> > > > this happens when you've been jailbroken before -- falcon doesnt work on jailbroken devices
> > > 
> > > 
> > > Really? And why’s that?. I tried the apps when I wasn’t jailbroken too.
> 
> "Pretty sure" Yeeah if Snapchat had jailbreak detection it wouldn't be a popular app. It's not the cause for the crash.

nono, not snap. falcon doesnt work on devices that have been previous jailbroken

**Comment by asdfzxcvbn** [comment]
> > > "Pretty sure" Yeeah if Snapchat had jailbreak detection it wouldn't be a popular app. It's not the cause for the crash.
> > 
> > 
> > nono, not snap. falcon doesnt work on devices that have been previously jailbroken
> 
> Why would the developer go out of their way to make it so an app doesn't work on jailbroken iphones? Plus where Is your actual info?

info? source? from the dev:

![image](https://github.com/swaggyP36000/TrollStore-IPAs/assets/109937991/bdbaa591-df9f-4d80-baab-133d43298279)

**Comment by TronziaHQ** [comment]
> > > > "Pretty sure" Yeeah if Snapchat had jailbreak detection it wouldn't be a popular app. It's not the cause for the crash.
> > > 
> > > 
> > > nono, not snap. falcon doesnt work on devices that have been previously jailbroken
> > 
> > 
> > Why would the developer go out of their way to make it so an app doesn't work on jailbroken iphones? Plus where Is your actual info?
> 
> info? source? from the dev:
> 
> ![image](https://user-images.githubusercontent.com/109937991/254972234-bdbaa591-df9f-4d80-baab-133d43298279.png)

And why the actual FUCK is it made like that bruuh.
