### ISSUE TITLE
Remove Strava's "Background App Refresh"

### ISSUE THREAD

**Issue by TrayBer** [swaggyP36000/TrollStore-IPAs#571]
Strava App: https://apps.apple.com/us/app/strava-run-bike-hike/id426826309

Could you remove the mandatory requirement for "Background App Refresh"? Alternatively, could you provide a method to disable it?
Thank you for your contribution to the community, much appreciated!

![IMG_0629](https://github.com/user-attachments/assets/b1a0e2e4-307c-4c1a-b2bb-ebdc66f27ae7)

**Comment by ArianaMinajj** [comment]
Hello,

You simply need to temporarily switch the app registration to "User" to access the app's settings and then uncheck it. *(Note that Strava partially depends on background activity)*
