### ISSUE TITLE
Spotify Deluxe Old has a newer 8.6.xxx-0.5 version on appdb

### ISSUE THREAD

**Issue by gototheskinny** [swaggyP36000/TrollStore-IPAs#58]
I don't know what has changed but it's 7~ mb smaller and it's working well for me so far.
if you don't wanna wait on appdb link directer:
[https://starfiles.co/file/iHonyAVY7nFc/SpotifyDeluxeOldv-8](https://starfiles.co/file/iHonyAVY7nFc/SpotifyDeluxeOldv-8)

**Comment by swaggyP36000** [comment]
Adding this to today's release

**Comment by swaggyP36000** [comment]
Checked this - 8.6.94 is newer than 8.6.4 right? That is an older version
