### ISSUE TITLE
Replace esign no logs ipa

### ISSUE THREAD

**Issue by asdfzxcvbn** [swaggyP36000/TrollStore-IPAs#580]
the one added to the repo shouldnt block all the domains. in my own testing, there are some domains not stored in the binary's strings, which can only be blocked by further patching. (i had bypassed esign's dylib detection, however it was only compatible with trollstore for whatever reason..)

you should replace (or add alongside) the ipa with will's binary patched version (which is an old version, v5.0), which correctly blocks all network requests.

you can get it from my mirror here: pub [dot] tbqh [dot] dev / ESignV5.0_noLogs_V1.1.ipa

**Comment by emreozcn06** [comment]
Hi, what exactly is the difference between ESignNoLogs and others?

**Comment by augustobob** [comment]
There´s a no logs version with trollstore capabilities?

**Comment by asdfzxcvbn** [comment]
> _(I can't grab the IPA as the link has no redirection)_

looks like you were able to get it, great! by the way, you can mark this as the source: https://discord.com/channels/1021310444167778364/1036011684587913266/1198515581679312937 (r/sideloaded announcement)

**Comment by asdfzxcvbn** [comment]
> Hi, what exactly is the difference between ESignNoLogs and others?

telemetry is removed, that's all

**Comment by asdfzxcvbn** [comment]
> There´s a no logs version with trollstore capabilities?

i would never recommend using esign+, i meant i made an ipa with my no logs tweak injected but the ipa only works if you install it with trollstore while jailbroken and idk why

**Comment by augustobob** [comment]
> i would never recommend using esign+, i meant i made an ipa with my no logs tweak injected but the ipa only works if you install it with trollstore while jailbroken and idk why

That’s fine, I don’t really install apps with Esign+, all the apps I download or modify I install with TrollStore.
I like the “installed apps” tab which let me manage my apps
