### ISSUE TITLE
Strava keeps signing me out

### ISSUE THREAD

**Issue by djsmix** [swaggyP36000/TrollStore-IPAs#588]
Hi, 
The Strava app is singing me out when im closing the app, or when it have been docked for 10 minutes?

**Comment by djsmix** [comment]
Why closing it when its an issue lol

**Comment by ArianaMinajj** [comment]
Hello,

It seems like you can't read nor understand how this is invalid.. But as simple as that is, your "issue" is not TrollStore related, so please do not ping me. Thank you!

*(This is your last warning)*
