### ISSUE TITLE
[Request] RadioApp - A Simple Radio

### ISSUE THREAD

**Issue by JellyPeixe** [swaggyP36000/TrollStore-IPAs#590]
It would be awesome if possible to add this radio app with Lifetime premium features unlocked.

Link: https://apps.apple.com/br/app/radioapp-a-simple-radio/id720291153

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app and I'll upload it in a few hours!

You can download the latest version **[here](https://gofile.io/d/a32Qmd)** if you prefer not to wait.
