### ISSUE TITLE
[Request] Pocket Fur TV

### ISSUE THREAD

**Issue by CyborgParrot** [swaggyP36000/TrollStore-IPAs#592]
https://pocket-fur-tv.appstor.io

Been trying to buy/download this app made as a tie in for this MTV show that was on around the end of the 2000s/beginning of the 2010s.

IDK if it's still available or if it's long gone.

I'd really like to get my hands on it just so I can rip/extract the audio files for personal use.

**Comment by ArianaMinajj** [comment]
Hello,

It seems like the app you're looking for is no longer available and extremely outdated; I can't find it on the App Store or any other websites. Sorry about that!
