### ISSUE TITLE
Apollo with Artemis or ApolloApi .ipa

### ISSUE THREAD

**Issue by gototheskinny** [swaggyP36000/TrollStore-IPAs#60]
For no jailbreak trollstore or sideload users this would be great.

**Comment by swaggyP36000** [comment]
I can upload this but it will be untested since I use the Reddit client with jailbreak tweaks. It will be up under today's coming release, whenever I get around to updating apps today

**Comment by swaggyP36000** [comment]
There are two available, Artemis and ApolloPatcher. Both crash on launch when installed via TrollStore so there's no point uploading them to this repo. However, they're up on zxcvbn's telegram and AppDB if you or anyone else would like to try sideloading those

Feel free to reopen this issue if you find versions of these apps that work with TrollStore

**Comment by gototheskinny** [comment]
> There are two available, Artemis and ApolloPatcher. Both crash on launch when installed via TrollStore so there's no point uploading them to this repo. However, they're up on zxcvbn's telegram and AppDB if you or anyone else would like to try sideloading those
> 
> 
> 
> Feel free to reopen this issue if you find versions of these apps that work with TrollStore

I'm using apollo tweaked with Artemis on xina15 rn. I saw on jb reddit that it works on sideload too that's why I've opened this issue. If it's not working on trollstore than don't bother especially if you're not using it. Thanks for checking it.

**Comment by asdfzxcvbn** [comment]
> There are two available, Artemis and ApolloPatcher. Both crash on launch when installed via TrollStore so there's no point uploading them to this repo. However, they're up on zxcvbn's telegram and AppDB if you or anyone else would like to try sideloading those
> 
> Feel free to reopen this issue if you find versions of these apps that work with TrollStore

my IPA is crashing? apollo is ios 15 minimum, so that's probably why it's crashing since you're on ios 14 iirc. it should work just fine with trollstore
