### ISSUE TITLE
VesselFinder Pro outdated

### ISSUE THREAD

**Issue by diamonddwow** [swaggyP36000/TrollStore-IPAs#615]
hey, i installed vesselfinderpro from your ipas and when i enter the app it says that the app is outdated so i cant use it, may you update it please?

**Comment by diamonddwow** [comment]
https://apps.apple.com/it/app/vesselfinder-pro/id608985698
App link
——————
Maybe you can add marinetraffic too?

**Comment by ArianaMinajj** [comment]
Hello,

Thank you for letting me know! I'll go ahead and remove the app from the repository. If a newer version becomes available, I'll be sure to upload it!

Please note that it has already been mentioned in [#230](https://github.com/swaggyP36000/TrollStore-IPAs/issues/230) that no tweak has been found for MarineTraffic.
