### ISSUE TITLE
Athan Pro Premium v8.4.3 - Tweak is unstable 

### ISSUE THREAD

**Issue by honestyan** [swaggyP36000/TrollStore-IPAs#616]
I have been enjoying Athan Pro Premium v8.4.3 for the past few months, and it has been a great experience. However, I've recently encountered an issue where the premium features are no longer accessible and seem to have reverted to the free version.

These features were working perfectly about 2-3 months ago, and I'm concerned about this unexpected change. Could you please look into this and provide any updates or solutions?

**Comment by ArianaMinajj** [comment]
Hello,

I'm afraid you're wrong.. I just double-checked the IPA and it appears to be working just fine? When first installed it requires two restarts and approximately two minutes for the Pro features to unlock. 

Once this process is complete, the Pro features will remain permanently active.

Note that this has obviously been tested using TS and I'm on iOS17.0, it would be interesting to know if you're also installing the ipa with TrollStore!

**Comment by honestyan** [comment]
> Hello,
> 
> I'm afraid you're wrong.. I just double-checked the IPA and it appears to be working just fine? When first installed it requires two restarts and approximately two minutes for the Pro features to unlock.
> 
> Once this process is complete, the Pro features will remain permanently active.
> 
> Note that this has obviously been tested using TS and I'm on iOS17.0, it would be interesting to know if you're also installing the ipa with TrollStore!

I've been experiencing an issue with Athan Pro Premium v8.4.3. After installing the app on iOS 16.6 using TrollStore, the premium badge is displayed, but the features seem to be restricted to the free version. For example, the widget remains locked even though the premium status is indicated.

I have already tried restarting the app a couple of times and waiting a few minutes, but the Pro features still don’t activate.

It's worth noting that I installed the IPA with TrollStore, similar to what you've mentioned with TS on iOS 17.0, where it seems to work fine.

**Comment by ArianaMinajj** [comment]
Thank you! So it seems like the tweak only supports iOS 17.0 devices? 

I'll test it on my old phone where it runs iOS 16. If it doesn't work, that will confirm what you mentioned and I'll make sure to update the description of the app accordingly.

**Comment by honestyan** [comment]
> Thank you! So it seems like the tweak only supports iOS 17.0 devices?
> 
> I'll test it on my old phone where it runs iOS 16. If it doesn't work, that will confirm what you mentioned and I'll make sure to update the description of the app accordingly.

Thank you for your response. I wanted to update you that my device running iOS 17.0 has also reverted to the free version (especialli the widget features), just like the issue I experienced on iOS 16.6. It seems this problem isn't limited to iOS 16.6 but affects iOS 17.0 as well.

**Comment by honestyan** [comment]
> Thank you! So it seems like the tweak only supports iOS 17.0 devices?
> 
> I'll test it on my old phone where it runs iOS 16. If it doesn't work, that will confirm what you mentioned and I'll make sure to update the description of the app accordingly.

I wanted to update you on the situation. The Athan Pro Premium app is working again, and the premium features have been restored. I’m a bit puzzled as to why it suddenly reverted to the free version earlier, with the widget showing a lock symbol.

However, after restarting my device (not just the app), the premium features became active again. You might consider adding a notice for users that if they experience this issue, restarting the device can help resolve it.

So i think this issue properly solved. Thanks in advance.

**Comment by ArianaMinajj** [comment]
I'll note that on the app's description, thank you for testing it for me!
