### ISSUE TITLE
[Request] Carly All Brands

### ISSUE THREAD

**Issue by BStyle69** [swaggyP36000/TrollStore-IPAs#619]
https://apps.apple.com/ch/app/carly-obd2-auto-scanner/id467344155?l=it

Hallo, it’s possible to have this app with premium unlock? Thx 🙏🏻

**Comment by ArianaMinajj** [comment]
Hello,

Please test this **[ipa](https://gofile.io/d/HUIxx3)** and let me know if it’s working. Thank you!
