### ISSUE TITLE
TikTokLRD isn't cracked from latest release

### ISSUE THREAD

**Issue by mbs0ft** [swaggyP36000/TrollStore-IPAs#62]
[This release](https://github.com/swaggyP36000/TrollStore-IPAs/releases/tag/07-25-2023
)
TikTokLRD isn't cracked:
![IMG_18BFBD64FF07-1](https://github.com/swaggyP36000/TrollStore-IPAs/assets/22106304/6d20ba42-d04e-44a9-be85-f8ff24644ee1)

**Comment by ArianaMinajj** [comment]
Check the latest [Asset](https://github.com/swaggyP36000/TrollStore-IPAs/releases/download/07-25-2023/TikTokLRDCracked-2.5-30.3.0.ipa) from the [release](https://github.com/swaggyP36000/TrollStore-IPAs/releases/tag/07-25-2023) and let me know if it works for you!

**Comment by mbs0ft** [comment]
>  and let me know if it works for you!
Yep, it's working!
