### ISSUE TITLE
[Request] Stemz Max

### ISSUE THREAD

**Issue by st-ivan** [swaggyP36000/TrollStore-IPAs#620]
Hey there, Can we get this one? 

https://apps.apple.com/us/app/stemz-ai-tool-for-musicians/id1596495598

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app and I'll upload tomorrow!

You can download the latest version **[here](https://gofile.io/d/jw7JUy)** if you prefer not to wait.

**Comment by RRST16** [comment]
Hi, can we get a mod of this app pls

https://apps.apple.com/es/app/jurassic-world-alive/id1231085864
