### ISSUE TITLE
Does EeveeSpotify come with OpenSpotifySafariExtension built-in? 

### ISSUE THREAD

**Issue by Infinitay** [swaggyP36000/TrollStore-IPAs#621]
From [EeveeSpotify](https://github.com/whoeevee/EeveeSpotify)'s repo

> To open Spotify links in sideloaded app, use [OpenSpotifySafariExtension](https://github.com/BillyCurtis/OpenSpotifySafariExtension). Remember to activate it and allow access in Settings > Safari > Extensions.

Does the ipa you host on this repo come with this extension already added?

**Comment by ArianaMinajj** [comment]
Hello,

No because this isn't necessary for TrollStore users.
