### ISSUE TITLE
[Request] Reflection Premium

### ISSUE THREAD

**Issue by ibrokethelaw** [swaggyP36000/TrollStore-IPAs#629]
https://apps.apple.com/us/app/reflection-journal-prompts/id1504547616

Thank you!

**Comment by ibrokethelaw** [comment]
<img width="131" alt="image" src="https://github.com/user-attachments/assets/5e73ee2e-5913-41dc-9946-797930efd069">

**Comment by ArianaMinajj** [comment]
Hello,

You can download the latest version **[here](https://gofile.io/d/QKkGf8)** if you prefer not to wait.

Please note that this app will not be uploaded to the repo.

**Comment by ibrokethelaw** [comment]
I can’t believe it that you did it so fast and it workedHave a nice day thank you very muchCheers,KOn 2 Aug 2024, at 12:25, Ariana ***@***.***> wrote:﻿
Closed #629 as completed.
