### ISSUE TITLE
[Request] Photoroom Pro 

### ISSUE THREAD

**Issue by ssivia** [swaggyP36000/TrollStore-IPAs#633]
Can you please add **[Photoroom](https://apps.apple.com/us/app/photoroom-ai-photo-editor/id1455009060)** Pro?

**Comment by ArianaMinajj** [comment]
Hello,

I'll upload it tomorrow!

**Comment by kn3w** [comment]
> Hello,
> 
> A tweak is already available for this app and I'll upload it in a few hours!
> 
> You can download the latest version **[here](https://gofile.io/d/Mf25aP)** if you prefer not to wait.

Didn’t work :(
