### ISSUE TITLE
[Request] Web Video Caster Premium

### ISSUE THREAD

**Issue by vnVyanz** [swaggyP36000/TrollStore-IPAs#634]
Hello .
Could you remove ads for it ? Thank you very much.

https://apps.apple.com/us/app/web-video-cast-browser-to-tv/id1400866497     

[Web Video Cast | Browser to TV](https://apps.apple.com/us/app/web-video-cast-browser-to-tv/id1400866497 )

**Comment by ArianaMinajj** [comment]
Hello,

I just uploaded it!
