### ISSUE TITLE
[Request] Fotor Pro

### ISSUE THREAD

**Issue by giangcoi89** [swaggyP36000/TrollStore-IPAs#635]
Hi, please I would like to ask for this app to be premium subscription enabled.
App Name: Fotor AI Photo Editor
Feature Request: Pro Unlocked
App Store Link: https://apps.apple.com/us/app/fotor-ai-photo-editor/id440159265

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app and I'll upload it in a few hours!

You can download the latest version **[here](https://gofile.io/d/XPlU8U)** if you prefer not to wait.
