### ISSUE TITLE
[Request] GrowIt Premium

### ISSUE THREAD

**Issue by NicolasBse** [swaggyP36000/TrollStore-IPAs#637]
Hi, please I would like to ask for this app to be premium subscription enabled.

App Name : **GrowIt: Vegetable Garden Care**

Feature Request: Pro Unlocked

App Store Link : https://apps.apple.com/us/app/growit-vegetable-garden-care/id6443580320

**Comment by ArianaMinajj** [comment]
Hello,

It appears that the only tweak somewhat working on this app is Satella but it is quite unstable; premium features tend to stop working after the app is relaunched.

You can try it **[here](https://gofile.io/d/ToFIi7)**. (It won't be uploaded to the repo)
