### ISSUE TITLE
[Request] Anytune Pro+

### ISSUE THREAD

**Issue by cakebomb999** [swaggyP36000/TrollStore-IPAs#639]
Hi, please I would like to ask for this app to be premium subscription enabled.

App Name : Anytune

Feature Request: Base/Pro/Studio Packet unlocked ~~| Anytune Pro +~~

App Store Link Anytune : https://apps.apple.com/de/app/anytune/id415365180
~~App Store Link Anytune Pro+: https://apps.apple.com/de/app/anytune-pro/id478293637~~

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app and I'll upload it tomorrow!

You can download the latest version **[here](https://gofile.io/d/eWr9ZA)** if you prefer not to wait.

*Note: I edited your initial message because the latest paid version of the app is unavailable.*
