### ISSUE TITLE
"Tutorial" needed for wicked 

### ISSUE THREAD

**Issue by TronziaHQ** [swaggyP36000/TrollStore-IPAs#64]
Can you please do a tutorial on how to use the cracked version on Snapchat wicked. Cause the description you wrote doesn’t tell me nothing.

**Comment by ArianaMinajj** [comment]
I have created a comprehensive tutorial, which is linked in its description. You can access it [here](https://rentry.co/whadahell). Would you mind checking it out and informing me of its usefulness?
