### ISSUE TITLE
[Request] Remote Mouse Pro

### ISSUE THREAD

**Issue by KenjiUrban** [swaggyP36000/TrollStore-IPAs#641]
Is it possible to get this unlocked? I use remote mouse every day (all day) for work.

https://apps.apple.com/us/app/remote-mouse/id385894596

thank you 😊

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app and I'll upload it in a few hours!

You can download the latest version **[here](https://gofile.io/d/zFJzeY)** if you prefer not to wait.

**Comment by KenjiUrban** [comment]
Thank you very much 🙇🏻‍♂️
