### ISSUE TITLE
[Request] Loora premium

### ISSUE THREAD

**Issue by cljag** [swaggyP36000/TrollStore-IPAs#644]
Is it possible to have this app unlocked please?

https://apps.apple.com/it/app/parla-inglese-con-loora-ai/id1552708303

thanks!

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app and I'll upload it tomorrow!

You can download the latest version **[here](https://gofile.io/d/myJYXs)** if you prefer not to wait.
