### ISSUE TITLE
Adguard Pro crashes on startup

### ISSUE THREAD

**Issue by Khazmar10** [swaggyP36000/TrollStore-IPAs#645]
Adguard pro 4.5.5
iPhone SE3 15.6.1
Dopamine 2.2.1
Trollstore Helper 2.0.15

I can install it successfully but when I try to open it, it just suddenly crashes. I’ve read some previous issues so I’m not sure if it might be due to my iOS version or not.

**Comment by ArianaMinajj** [comment]
Hello,

Previous issues were not related to TrollStore and it might not be due to your iOS version as AdGuard requires iOS >=13. 

You will have to investigate what's causing the problem yourself because I cannot reproduce your issue. Sorry about that!
