### ISSUE TITLE
[Request] Backdrops Pro

### ISSUE THREAD

**Issue by ikbenhetalex** [swaggyP36000/TrollStore-IPAs#646]
Backdrops Pro - https://apps.apple.com/nl/app/backdrops-wallpapers/id1500143735?l=en-GB

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app!

You can download the latest version **[here](https://gofile.io/d/hiWmck)**.

*Note that this won't be uploaded into the repo.*
