### ISSUE TITLE
[Request] FlipaClip Plus

### ISSUE THREAD

**Issue by jamunano** [swaggyP36000/TrollStore-IPAs#652]
hi are you able to do this? 🙏

https://apps.apple.com/jp/app/flipaclip-create-2d-animation/id1101848914

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app. You can download the **outdated version [here](https://gofile.io/d/iuZ619)**.

*Please note that this app will not be uploaded to the repo as injecting the tweak into latest version(s) leads to a crash.*
