### ISSUE TITLE
[Request] Tone Pro

### ISSUE THREAD

**Issue by Hoe2020** [swaggyP36000/TrollStore-IPAs#655]
I am so sorry, if this breaks any rules. My bad then, but I requested a decrypt for tone perfect pitch

https://apps.apple.com/us/app/tone-learn-perfect-pitch/id1139019670

Could you unlock it? Thanks so much!

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app!

You can download the latest version **[here](https://gofile.io/d/J4Ow1p)**.

Note that this app won't be uploaded into the repo.

**Comment by Hoe2020** [comment]
Thank you so much!

The app crashes and requests for my apple Id whenever I open it.
I know this is not your IPA, but I was wondering if you knew a solution.

Thanks!

**Comment by ArianaMinajj** [comment]
Obviously because you're not installing the app with TS.. 

I updated the download link to "fix" your problem.

*Note: I kindly ask that you refrain from opening any issues/requests unless you are on TrollStore.*

**Comment by Hoe2020** [comment]
Ok thanks!
