### ISSUE TITLE
EOS for Tiktok (Beta) - Sezo

### ISSUE THREAD

**Issue by xLinoelx** [swaggyP36000/TrollStore-IPAs#660]
Hello! I am currently an InstagramNix user and I follow Sezo on telegram and I would like to know if it is possible for you to add EOS to the repository, so I could also use my license for that tool. Thank you for the support.

![IMG_4224](https://github.com/user-attachments/assets/63c84b85-fa0e-416d-84c1-ff5eb1b834be)

**Comment by ArianaMinajj** [comment]
Hello,

Refer to **[#292](https://github.com/swaggyP36000/TrollStore-IPAs/issues/292)**
