### ISSUE TITLE
[Request] Evermusic Pro 

### ISSUE THREAD

**Issue by thexYeti** [swaggyP36000/TrollStore-IPAs#664]
Would be awesome if Evermusic Pro could be added to the library, its probably the most extensive audioplayer for podcasts and music.

Thanks!

App Store link: https://apps.apple.com/de/app/evermusic-pro-offline-musik/id905746421

**Comment by ArianaMinajj** [comment]
Hello,

The only place offering that app is **[AppCake](https://www.iphonecake.com/app_905746421_.html)**; but I will not upload it because that's outdated.
