### ISSUE TITLE
[Question] MyFitnessPal Premium Version

### ISSUE THREAD

**Issue by Invisible40** [swaggyP36000/TrollStore-IPAs#666]
Hi! The chart says that MyFitnessPal Premium was last updated on 08-01-2024 to 24.30.0	by IPALibrary.me

However on the IPALibrary.me website, it says it was last updated on 03/08/2024 to version 24.9.0

You may want to update the link and/or version

**Comment by ArianaMinajj** [comment]
Hello,

Updates are taken from another source that I forgot to mention: **[binnichtaktiv's ipa library](https://t.me/binnichtaktivsipas)**
