### ISSUE TITLE
Memrise Premium - v2024.7.5 -  can not access to scenarios premium topic

### ISSUE THREAD

**Issue by sitien173** [swaggyP36000/TrollStore-IPAs#668]
When I click on a premium topic in Scenario, it prompts me to buy the Pro version. This issue occurs on iOS 16.3.

**Comment by ArianaMinajj** [comment]
Hello,

This is a known issue due to recent updates affecting features server-side. I'm actually looking for a tweak to unlock all features and will update you if I find one. Sorry for the inconvenience!
