### ISSUE TITLE
[Request] HD Flix No Ads

### ISSUE THREAD

**Issue by rrrr123456789** [swaggyP36000/TrollStore-IPAs#671]
https://apps.apple.com/us/app/breeze-video-movies/id6502223676

Add no ads tweak please :)

**Comment by ArianaMinajj** [comment]
Hello,

I'll upload it in a few hours!

**Comment by rrrr123456789** [comment]
@ArianaMinajj Will it have no ads tweak injected? Thanks.

**Comment by rrrr123456789** [comment]
@ArianaMinajj After testing the ipa I cannot play anything, is this normal?

**Comment by ArianaMinajj** [comment]
I found that blocking ads on the app now stops playback. *(This is a new issue as ad blocking used to work fine)*

I'll re-upload the original HDflix but it will include ads. Sorry for the inconvenience!

**Comment by rrrr123456789** [comment]
Umm okay then :(
Then where is the old version that still works with ad blocker?

**Comment by ArianaMinajj** [comment]
I fixed the issue myself, you can download it [here](https://gofile.io/d/2AF5Rq), I'll re-upload it shortly!
