### ISSUE TITLE
[Request] Qr Code cracked life time subscription 

### ISSUE THREAD

**Issue by NoozPrime** [swaggyP36000/TrollStore-IPAs#676]
Here’s the link of the app 👍 
https://apps.apple.com/app/id6469319539
I would like to have the lifetime subscription for it

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app! You can download the latest version **[here](https://gofile.io/d/Unf1v1)**.

Note that this app won't be uploaded into the repo.

**Comment by NoozPrime** [comment]
> Hello,
> 
> A tweak is already available for this app! You can download the latest version **[here](https://gofile.io/d/Unf1v1)**.
> 
> Note that this app won't be uploaded into the repo.

I’m not able to use it is it only for trollstore i sidelead on esign?
