### ISSUE TITLE
AI Chat Smith + Genie not working

### ISSUE THREAD

**Issue by kexo1** [swaggyP36000/TrollStore-IPAs#679]
I tried both of these apps and they seem to be broken for me:

1. When launching AI Chat Smith and "buying subscription", I always get pop-up for review. If I cancel review the app gets frozen and you can't press anything. (I can't make review because it's grayed out)

2. When launching Genie, I get telegram pop-up and after that the app gets frozen.
![image](https://github.com/user-attachments/assets/8288d6e0-6086-45f9-9f89-987c6d7e7e74)

**Comment by kexo1** [comment]
Hello? Did you even read my post?
The point of this issue is to solve it, not close it like you did with others...

**Comment by ArianaMinajj** [comment]
Hello,

Let me clarify why your so-called "issue" is not valid.

First, I've personally tested both IPAs before uploading them to the repository, (as I do with every single one here) and they are working fine. Second, you had the audacity to question whether I read your post yet you didn't take the time to read the instructions on how to properly report an issue..? **which is clearly outlined in the repo's Readme.md.**

Lastly, I'm quite certain that this isn't even related to TrollStore. (You wouldn't have raised this "issue" if you were aware that using TrollFools could resolve it.)

Note that if your next "issue" is also found to be invalid, you will be permanently banned from the repo. Thank you for your understanding!

**Comment by kexo1** [comment]
Firstly, thank you for taking your time to respond.

I know this issue doesn't have to do anything with TrollStore, but how else can I report non-TrollStore app that is **potentially** not functioning on my device? You test your apps before uploading them, I know that, however I have no idea why it's not working on my device. 

My device is iPhone 14 with IOS 17.6.1, no TrollStore, no Jailbreak, just default. If you don't believe me, I can send you video proof of the bug I stated in issue.

Sure, this might not be your problem that it's not working for me, or maybe others, however instead of instantly closing this issue with invalid, at least consider the fact that app **might** be unstable/buggy, and change issue label to bug, or maybe status in apps repo.

**Comment by ArianaMinajj** [comment]
The fact that you openly admit you're not using TrollStore (in a TS-Only repo) and continue to persist in your stubbornness, (while spreading misinformation about app(s) functionality) makes me wonder if you're trolling?

It only takes about 2 to 5 minutes to **read** through the repository's Readme.md. It contains information and guidelines that can help you understand **if you're addressing your concerns in the right place, which you currently are not.**

I respectfully can't help with the lack of reading skills/stubbornness and I'm afraid it might be best to refrain from further comments at this point..

**Comment by kexo1** [comment]
> In order to clarify, the presence of the term "TrollStore" in the title may lead some individuals to assume that all the applications listed herein are exclusively compatible with TrollStore. This, however, is not the case. Many of the apps featured on this list can indeed function seamlessly when sideloaded.

Literally says many of the apps can be **sideloaded**, which mean's I don't require TrollStore.
If an app requires TrollStore, it's specifically mentioned in description:

![image](https://github.com/user-attachments/assets/ef7789d2-a00c-40dd-8180-d8fb5697ffda)

And I am not spreading "misinformation" about apps functionality, as I said, if you want video proof then ask for it.
