### ISSUE TITLE
Pixel Pals Premium crashing

### ISSUE THREAD

**Issue by IvanIVGrozny** [swaggyP36000/TrollStore-IPAs#695]
App crashes upon launch. Turned on Increased Memory Limit and Extended Virtual Addressing entitlements for both the Widget Extension and the base app to no avail. Attaching ips crash logs.

iPhone 15 Pro, iOS 17.0, paid developer account.

[PixelPals-2024-08-21-235212.txt](https://github.com/user-attachments/files/16700420/PixelPals-2024-08-21-235212.txt)
[PixelPalsWidgetExtension-2024-08-21-234337.txt](https://github.com/user-attachments/files/16700423/PixelPalsWidgetExtension-2024-08-21-234337.txt)

**Comment by IvanIVGrozny** [comment]
What the flop do you mean invalid, you got your description, logs, all the info and the app indeed does not work

**Comment by ArianaMinajj** [comment]
Hello,

Please take a moment to review my comments **[here](https://github.com/swaggyP36000/TrollStore-IPAs/issues/679)** for a more comprehensive understanding since you can't read, Thank you !
