### ISSUE TITLE
[Request] Dynamic Island - Notch

### ISSUE THREAD

**Issue by hieunv95** [swaggyP36000/TrollStore-IPAs#696]
An interesting and useful app to associate with [DynamicCowTS](https://github.com/matteozappia/DynamicCowTS)

https://apps.apple.com/us/app/dynamic-island-notch/id1615753081

Thanks in advance! :heart:

**Comment by ArianaMinajj** [comment]
Hello,

I uploaded a variant version of the app you requested **[here](https://github.com/swaggyP36000/TrollStore-IPAs/releases/tag/09-01-2024)**. *("Wallpapers for Dynamic Island")*
