### ISSUE TITLE
[Request] ToneStack Pro

### ISSUE THREAD

**Issue by Aethereux** [swaggyP36000/TrollStore-IPAs#697]
https://apps.apple.com/ph/app/tonestack-pro-guitar-amps-fx/id1529842791

Feature request: Unlock all Gears

**Comment by ArianaMinajj** [comment]
Hello,

Could you please test this **[ipa](https://gofile.io/d/V4BCuh)** and tell me if it works? Thanks in advance!

**Comment by Aethereux** [comment]
It works! Although you need to use bootstrap and enable tweaks to prevent it from crashing when launching. 

Overall it works. Thanks!

**Comment by Aethereux** [comment]
That's strange... I'm on 15.5. The app keeps crashing when launching it. However if I enable tweaks using Bootstrap, it launches perfectly fine.

[YT Clip Demonstration](https://youtu.be/xQc_yJEESsQ?si=bXBHL6QzwH7lwEyl)

**Comment by ArianaMinajj** [comment]
I can't reproduce since I'm neither on iPadOS nor using bootstrap, sorry about that! (Thank you for the video though)
