### ISSUE TITLE
Spotify Deluxe Old v. doesn't work properly for TURKISH ACCOUNTS

### ISSUE THREAD

**Issue by gototheskinny** [swaggyP36000/TrollStore-IPAs#70]
If you're on ios 15.0> can you check if it's working like it used to? Bc it's now I can't select from my Liked songs list or ANY list like it used to. Spotify fvcked that version or probably all versions up. Now I'm on the latest  spotilife and it let's me choose any track but can't disable shuffle and all around not like the old deluxe version!.

Edit: + The latest deluxe and spotilife prevents you from switching to the part of the song you want. for example you can't fast forward, old deluxe version have that feature.

Edit 23.09.2023: ![image](https://github.com/swaggyP36000/TrollStore-IPAs/assets/51786709/9fdb44d5-0bad-4b21-903e-f2a60f4a2ed9)

Edit3: 
Vpns for 2 week check:

•star vpn premium mod ipa from Kamo hacks telegram channel worked.

•Protonvpn **didn't** work.

**Comment by ArianaMinajj** [comment]
Hi there,

I’m currently running iOS 15.5 and have conducted some tests using Spotify Deluxe Old. I can confirm that all premium features appear to be functioning just as they do in the latest Spotify Deluxe/Spotilife version. Based on this, it seems that the issue you’re experiencing may not be related to the specific iOS version ?

However, it’s worth noting that Spotilife may not work optimally on Spotify versions above 8.6.42, as suggested by **[zxcvbn](https://t.me/SpotilifeIPAs)**. If you’re encountering issues with Premium features, you might want to consider creating a new Spotify account to see if that resolves the problem.

Additionally, I’ve provided a link to a potential IPA (from **[zxcvbn](https://t.me/zxcvbn_tweaked)**) that could help fix the issue: **https://gofile.io/d/znt2Y5**

If you continue to experience issues, please provide more details or feel free to ask for further assistance.

**Comment by gototheskinny** [comment]
> Hi there,
> 
> 
> 
> I’m currently running iOS 15.5 and have conducted some tests using Spotify Deluxe Old. I can confirm that all premium features appear to be functioning just as they do in the latest Spotify Deluxe/Spotilife version. Based on this, it seems that the issue you’re experiencing may not be related to the specific iOS version ?
> 
> 
> 
> However, it’s worth noting that Spotilife may not work optimally on Spotify versions above 8.6.42, as suggested by **[zxcvbn](https://t.me/SpotilifeIPAs)**. If you’re encountering issues with Premium features, you might want to consider creating a new Spotify account to see if that resolves the problem.
> 
> 
> 
> Additionally, I’ve provided a link to a potential IPA (from **[zxcvbn](https://t.me/zxcvbn_tweaked)**) that could help fix the issue: **https://gofile.io/d/znt2Y5**
> 
> 
> 
> If you continue to experience issues, please provide more details or feel free to ask for further assistance.

The link that you've given is given me the same result with the same account tho. I've blocked a lot of artists on that account and been using it for 2 years~ creating new account is not the most convenient solution TBH but we don't have any other solution for this I guess. I've created this account on a older version of Spotilife BTW and that worked that time. I wish we had an absolute solution to this syit! 
I thought Spotify finally changed their apis? Or something like that but ofc not it's only for me..

**Comment by ArianaMinajj** [comment]
It's possible that Spotify has made some recent server-sided API changes such as **[this](https://www.reddit.com/r/Piracy/comments/16cbm6i/spotify_lyrics/)** ? Which could be causing the issue you're experiencing. I apologize for not having a proper fix for this problem. It's frustrating when such issues arise especially for Spotify.

I encourage others who are facing the same issue to also share their experiences and insights in this current issue.

**Comment by gototheskinny** [comment]
> It's possible that Spotify has made some recent server-sided API changes such as **[this](https://www.reddit.com/r/Piracy/comments/16cbm6i/spotify_lyrics/)** ? Which could be causing the issue you're experiencing. I apologize for not having a proper fix for this problem. It's frustrating when such issues arise especially for Spotify.
> 
> 
> 
> I encourage others who are facing the same issue to also share their experiences and insights in this current issue.

Creating a new account solved it. I wasn't expecting you guys to solve it I was just wondering is it just me or did Spotify broke apis or whatever. Thank you for your help I appreciate it!

**Comment by gototheskinny** [comment]
> It's possible that Spotify has made some recent server-sided API changes such as **[this](https://www.reddit.com/r/Piracy/comments/16cbm6i/spotify_lyrics/)** ? Which could be causing the issue you're experiencing. I apologize for not having a proper fix for this problem. It's frustrating when such issues arise especially for Spotify.
> 
> 
> 
> I encourage others who are facing the same issue to also share their experiences and insights in this current issue.

@ArianaMinajj . Well... It's over AGAIN. I've looked into this issue  and the issue is **my account region "Turkey"** **FUCK** SPOTIFY RACIST FUCKS. I'm raging rn and have to **seek asylum** in USA bc Spotify hates Turkish users. Ridiculous.

**Comment by gototheskinny** [comment]
I suggest you to keep an Issue Open and let people know about this Turkish account issue bc there are a lot of people who experience this issue even on Android as well.

**Comment by ArianaMinajj** [comment]
Hello,

Thank you for sharing your experience and providing this valuable information. I will reopen the issue so that we can continue to investigate the "Turkish account" issue, gathering more insights and help others facing the same problem.

Additionally, it's great to hear that switching to USA region with a VPN resolved the issue for you. However, as you rightly pointed out, VPN region changes typically last for about two weeks and may revert to the default region afterward.

**Comment by gototheskinny** [comment]
> Hello,
> 
> 
> 
> Thank you for sharing your experience and providing this valuable information. I will reopen the issue so that we can continue to investigate the "Turkish account" issue, gathering more insights and help others facing the same problem.
> 
> 
> 
> Additionally, it's great to hear that switching to USA region with a VPN resolved the issue for you. However, as you rightly pointed out, VPN region changes typically last for about two weeks and may revert to the default region afterward.

Yeah I've switched to USA in the past that's correct they let you 2 weeks than force you to switch to your region back again. If you want to know about this "Turkey region" issue it's on xmanager (android Spotify mod) discord. Only the Turkish region accounts experience this issue. I guess Turkish users use the mods so much they're breaking them for us?!? Everyone in my family uses the mods so yeah maybe.

**Comment by 3rdQuasar** [comment]
Bro Italy too wtf

**Comment by ArianaMinajj** [comment]
@3rdQuasar, @gototheskinny Can you guys kindly try **[this particular version](https://github.com/swaggyP36000/TrollStore-IPAs/releases/download/12-02-2023/Sposilife-8.6.42.ipa)** please? While it may not necessarily resolve the issue, it wouldn't hurt to give it a try..

**Comment by gototheskinny** [comment]
@3rdQuasar just checked the Xmanager discord and no one is complaining having issues in Italy  accounts. It seems like only Türkiye accounts has issues. You should try the ipa that @ArianaMinajj have recommended.

**Comment by ArianaMinajj** [comment]
> > @3rdQuasar, @gototheskinny Can you guys kindly try **[this particular version](https://github.com/swaggyP36000/TrollStore-IPAs/releases/download/12-02-2023/Sposilife-8.6.42.ipa)** please? While it may not necessarily resolve the issue, it wouldn't hurt to give it a try..
> 
> <details>
>   <summary>Türkiye Region Account</summary>
>   
>  ![image](https://github.com/swaggyP36000/TrollStore-IPAs/assets/51786709/0c743a1e-01bd-4822-93f0-3f824bfc8a6a)
>   
> </details>
> 
> <details>
>   <summary>USA region account</summary>
>   
>  ![image](https://github.com/swaggyP36000/TrollStore-IPAs/assets/51786709/75009883-d0bc-402f-820d-6c7b2f572ca6)
> 
> </details>

Tysm for sharing the two screenshots! This is incredibly helpful in clarifying that Turkey is indeed blacklisted from modified versions of Spotify. Let's hope this issue doesn't extend to other countries as well..

**Comment by 3rdQuasar** [comment]
sorry for late comment didnt see the notification.
so with this new ipa that you shared it work perfectly thank you so much

**Comment by ArianaMinajj** [comment]
Hello,

Could you please check out the most recent version of EeveeSpotify uploaded **[here](https://github.com/swaggyP36000/TrollStore-IPAs/releases/tag/04-22-2024)**? Thank you in advance!

**Comment by gototheskinny** [comment]
> Hello,
> 
> Could you please check out the most recent version of EeveeSpotify uploaded **[here](https://github.com/swaggyP36000/TrollStore-IPAs/releases/tag/04-22-2024)**? Thank you in advance!

You've just read my mind! I was just checking the side TURKISH account that I have and it's working in live container app(not trollstore or sideloaded . Just checked 1 old Turkish account tho. If I encounter any issues I'll let you guys know.

**Comment by ArianaMinajj** [comment]
I'm truly glad to see this is working for you so far!

Could you please confirm if it's working via TS too? (It should be but I'm checking just to be sure)

**Comment by gototheskinny** [comment]
> I'm truly glad to see this is working for you so far!
> 
> Could you please confirm if it's working via TS too? (It should be but I'm checking just to be sure)

I've switched to a newer version iOS and a newer iPhone unfortunately (**jb-swapped** my old iPhone 12 15.0) so I really can't do it sorry :( 
It's not that hard to open and try it, you just need a vpn that has Turkey as a location that's it. If you don't wanna do it I get it it's not that big of a deal. as far as I see there's no issues RN for ME.

**Comment by ArianaMinajj** [comment]
No worries! I'll do it myself, thanks again!

**Comment by gototheskinny** [comment]
> No worries! I'll do it myself, thanks again!

Thank you for doing all of this work us Apple junkies :) I truly appreciate your work <3
