### ISSUE TITLE
[Request] Crunchyroll update + app tweak

### ISSUE THREAD

**Issue by Jainbaba** [swaggyP36000/TrollStore-IPAs#71]
Just need the access for Crunchyroll and also Crunchyroll is not available in my country. Would that be a issue?

**Comment by ArianaMinajj** [comment]
Hello, thank you for reaching out with your concern. I will be updating the application to the latest version.

**Comment by Jainbaba** [comment]
Could i request for an IOS Application to be tweaked? 
I am looking for a Mod Premium unlocked Version for Brilliant.org App.

**Comment by Jainbaba** [comment]
Could i request for an IOS Application to be tweaked?
I am looking for a Mod Premium unlocked Version for Brilliant.org App.

**Comment by ArianaMinajj** [comment]
I'll look into this request and keep you updated whether it's feasible or not. Thanks for your patience!

**Comment by c12n** [comment]
Crunchyroll crashes upon launch on my 13pm iOS 17RC using dev cett signed with gbox

**Comment by ArianaMinajj** [comment]
> Crunchyroll crashes upon launch on my 13pm iOS 17RC using dev cett signed with gbox

Thank you for reporting the issue. It appears that the problem with Crunchyroll crashing upon launch is widespread, affecting various devices and configurations.

To keep everyone updated on the status of this issue and potential fixes, please refer to **#72**.

Unfortunately, as of now, there is no immediate fix available for this problem. Therefore, I will be closing the current issue. Please follow the latest issue for any developments regarding this issue. Your patience is greatly appreciated.
