### ISSUE TITLE
[Request] Add uber for iOS 16.2 and lower

### ISSUE THREAD

**Issue by macosx10-hash** [swaggyP36000/TrollStore-IPAs#710]
When you try to install it the normal way it gives the low ios version error.

Do not know if this site is legit or not but here is a collection of ipas: https://decrypt.day/app/id368677368

If it is not a legit site please tell us.

I am on ios 15.3.1 and on a 11pm if it's important.

**Comment by swaggyP36000** [comment]
The site is legit. You can use it to grab base IPAs of most apps on a lot of different versions

**Comment by ArianaMinajj** [comment]
Hello,

I'm currently not on iOS 16.2 or below so I'll provide you with several versions for testing and I would need your feedback, Thank you!

You can try this version **[here](https://gofile.io/d/2pUxMg)**.

*Note: The website linked is indeed safe but known for its intrusive ads.*

**Comment by macosx10-hash** [comment]
The one you provided did not work for me but the version 3.568.10000 did.

**Comment by ArianaMinajj** [comment]
Where did you get the 3.568.10000 version from? The website you linked?

**Comment by ArianaMinajj** [comment]
You could try this **[version](https://gofile.io/d/w85cCi)**.
