### ISSUE TITLE
[Request] KyBook 3 Pro 

### ISSUE THREAD

**Issue by DrLetha1** [swaggyP36000/TrollStore-IPAs#711]
https://apps.apple.com/in/app/kybook-3-ebook-reader/id1348198785

Please can you upload ipa with pro features enabled (at least autoscroll )for this ebook reader app
Thank you

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app. You can download the latest version **[here](https://gofile.io/d/1DL8NU)**.

*Please note that this app will not be uploaded to the repo.*

**Comment by DrLetha1** [comment]
Sorry for the late reply,
Thanks for the response but i can't download the ipa file from gofile
website as site can't be reached (*cold4.gofile.io
<http://cold4.gofile.io>* took
too long to respond).

I tried 3 days straight and can't download it. Can you please sent me some
other way!

Thankyou

**Comment by ArianaMinajj** [comment]
The file has expired due to your extended delay in downloading, I'll re-upload it tomorrow. (last time)
