### ISSUE TITLE
Self made update for scmusicplus

### ISSUE THREAD

**Issue by 001bl33d** [swaggyP36000/TrollStore-IPAs#714]
Hello, i’ve recently updated scmusicplus to 7.51.1 (ad free soundcloud) and was wondering if I could provide you the file to add to the release list for any others looking for an updated version of the app if not all fine just let me know

**Comment by ArianaMinajj** [comment]
Hello,

You may upload the IPA file using a service such as gofile.io. It will be checked and tested before I upload it!
