### ISSUE TITLE
Request Brave Browser App

### ISSUE THREAD

**Issue by Khazmar10** [swaggyP36000/TrollStore-IPAs#715]
Please make “Brave Browser” ipa compatible with trollstore. The minimum version for the latest is iOS16, idk if there’s a workaround for it to work on iOS15. I tried decrypted Brave Browser with trollstore but it just crashes upon start. Thank you

**Comment by ArianaMinajj** [comment]
Hello,

If the app is crashing, the best solution is to downgrade using AppStore++. 

This is likely because the app relies on dependencies that are not available on iOS15 and lower.
