### ISSUE TITLE
Request for Removal of TwitchDvnloader

### ISSUE THREAD

**Issue by dayanch96** [swaggyP36000/TrollStore-IPAs#718]
This tweak was originally released as a paid product, and it has recently come to my attention that it has been leaked and made available for free without my consent.

The unauthorized distribution of this tweak not only undermines the work and effort that went into its development but also violates the terms under which it was intended to be distributed.

I kindly ask that you remove TwitchDvn from your repository as soon as possible to prevent further unauthorized access and distribution.

Thank you for your understanding.

**Comment by swaggyP36000** [comment]
I don't think we have explicitly stated this anywhere on the repo (we probably should), but in an effort to not get shut down and have years' worth of work disappear overnight, we are open to takedown requests.

I went ahead and removed the IPAs as well as any mention of the tweak from the releases

**Comment by dayanch96** [comment]
> I don't think we have explicitly stated this anywhere on the repo

Thank you. Providing an email for DMCA would significantly simplify the process for you, as repeated DMCA takedown notices could lead to the permanent suspension of your account without the possibility of appealing the decision.

**Comment by swaggyP36000** [comment]
That is the other worry as well. I do understand that GitHub will notify users with a 24 hour time window in the case that only part of the repo falls under a DMCA claim, but I don't know how many times they will do that before they decide they've had enough of it lol. I don't really care to find out either
