### ISSUE TITLE
Request: BeFunky

### ISSUE THREAD

**Issue by saifulapm** [swaggyP36000/TrollStore-IPAs#722]
Hi, BeFunky app possible ? 

https://apps.apple.com/hr/app/befunky/id442716817

**Comment by saifulapm** [comment]
Not available any crack ?

**Comment by ArianaMinajj** [comment]
Hello,

No sorry, in fact that's impossible. (For now)

**Comment by saifulapm** [comment]
Ok. Thanks Bro
