### ISSUE TITLE
Apps crashing

### ISSUE THREAD

**Issue by GreeenJJ** [swaggyP36000/TrollStore-IPAs#729]
Some apps with green checkmark keep crashing upon launch.
Examples of apps that crash: adGuardPro, Loora, Lightroom, Photoleap etc...
Not all apps I installed with trollapps crash though, for ex. genie, trollLed, remoteMouse work fine.

TrollStore version 2.0.15 TrollApps version 2.3
Iphone 12 Pro Max, iOS 15.0.2 
No JB, sileo, altstore or anything on my phone except for trollstore and trollapps.

I haven't been modding or jailbreaking my iphones in over 5 years so I'm very out of touch, if this is an invalid issue please point me in the right direction as I tried finding a solution myself before posting but couldn't.
Thanks

**Comment by ArianaMinajj** [comment]
Hello,

The status reflects the results of my personal testing; if an app works on my end, I'll conclude that it is working for others as well. So if you have an issue with an app that is working on my end, I obviously won't be able to replicate it. Therefore you'll need to find/explore alternative solutions on your own.
