### ISSUE TITLE
Discord banned

### ISSUE THREAD

**Issue by swaggyP36000** [swaggyP36000/TrollStore-IPAs#73]
Hi, I think you may have already realized, but my discord account got banned. Can you message me at u/Jailbrick3d on Reddit? I don't remember your username and have no other way of getting in contact with you again

**Comment by ArianaMinajj** [comment]
Hi there,

I tried messaging you on Reddit, but I'm consistently getting the error message "Unable to invite the selected invitee(s)" when I attempt to reach out. My username is Wulfoze

**Comment by swaggyP36000** [comment]
I messaged you. think it went through
