### ISSUE TITLE
[REQUEST] Blitzer.de Pro with IAP/Satella injected

### ISSUE THREAD

**Issue by calvinklein97** [swaggyP36000/TrollStore-IPAs#736]
Hello, would it be possible to add Blitzer.de Pro to the repo, injected with Satella or cracked IAP, to unlock mobile speed camera warnings that are behind a paywall in said app?

App Name: Blitzer.de PRO

Request: mobile speed camera warnings unlocked (which is an IAP inside the app)

App Store Link: https://apps.apple.com/de/app/blitzer-de-pro/id498732510

Reason: Bought the app back in the day assuming the pro version has mobile speed cameras unlocked by default. Turns out they're charging 10€ for it. Would love to save the money on that end if possible.

Thank you for the repo and all your work you put into this!

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app and I'll upload it in a few hours!

You can download the latest version **[here](https://gofile.io/d/2ofhg7)** if you prefer not to wait.
