### ISSUE TITLE
Trucker Path truck gps

### ISSUE THREAD

**Issue by defrt** [swaggyP36000/TrollStore-IPAs#739]
Is it possible to crack the diamond tear  and remove ads?

 https://apps.apple.com/us/app/trucker-path-truck-gps-fuel/id782746890

They ask for too much for it just because its a niche app

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app and I'll upload it in a few hours!

You can download the latest version **[here](https://gofile.io/d/varLws)** if you prefer not to wait.

**Comment by defrt** [comment]
App crashes immediately

**Comment by ArianaMinajj** [comment]
The app has been added despite the "issue" you're experiencing:

No support will be offered because this is unrelated to Trollstore (invalid), similar to many past issues you likely didn't bother reading. Please read the repository guidelines thoroughly, thank you!
