### ISSUE TITLE
TikTokBHPlus 2.2.1: 31.5.0 

### ISSUE THREAD

**Issue by mbs0ft** [swaggyP36000/TrollStore-IPAs#74]
dayanch96 updated [BHTikTokPlus](https://github.com/dayanch96/BHTikTok-Plus/releases/tag/v2.2.1) to 2.2.1
IPA Source of TikTok 31.5.0 [is here](https://decrypt.day/app/id835599320)

Injected tweak via Sideloadly, Cydia Substrate+Substitute

Download tweaked IPA: [Mega](https://mega.nz/file/dE1VyAoB#VXwZq0OI5xcfqHtLWrHXbJl64FTayk_TETnhLLwPfBI), [Google Drive](https://drive.google.com/file/d/10oq157b7sFUv2H8gLP1tZc5esVWrW--4/view?usp=sharing)

![IMG_1F57A46C9890-1](https://github.com/swaggyP36000/TrollStore-IPAs/assets/22106304/9384a27e-04d9-498e-8309-e09b9c631e9e)

**Comment by ArianaMinajj** [comment]
Hi there,

Thank you for bringing this but it appears there might be a misunderstanding as the repository is already up-to-date with the latest commit from the dayanch96 branch, and we are currently using TikTok version 31.5.0. It seems there was also a mistake in the version number mentioned in your comment "23.5.0", it should be 31.5.0.

**Comment by mbs0ft** [comment]
> Hi there,
> 
> Thank you for bringing this but it appears there might be a misunderstanding as the repository is already up-to-date with the latest commit from the dayanch96 branch, and we are currently using TikTok version 31.5.0. It seems there was also a mistake in the version number mentioned in your comment "23.5.0", it should be 31.5.0.

Oh yeah, 31.5.0, didn't see that mistake
But okay! :)
