### ISSUE TITLE
Windy.com - Weather & Radar

### ISSUE THREAD

**Issue by Lawrence323tw** [swaggyP36000/TrollStore-IPAs#740]
App Name: Windy.com - Weather & Radar

Request: Premium Unlocked

App Store Link: https://apps.apple.com/us/app/windy-com-weather-radar/id1161387262

Reason: If you’re involved in outdoor activities like climbing or diving, I believe many people would use this app. The advanced version, which updates every hour, is very convenient. I’ve seen a cracked APK for Android, and it would be a real pity if it can't be used on iOS.

I would like to express my deepest gratitude if you could fulfill my wish.

**Comment by Lawrence323tw** [comment]
@ArianaMinajj 
This is not a duplicate; what currently exists is the app at windy.app, not the one at windy.com.

**Comment by Lawrence323tw** [comment]
@ArianaMinajj  Does 'no planned' mean that it's impossible to crack, or does it simply indicate that there is no plan or demand for it? I use this app quite often and really hope for a cracked version to be available.Thx

**Comment by ArianaMinajj** [comment]
Hello,

It's impossible. *(For now)*

**Comment by Lawrence323tw** [comment]
Ok got it
