### ISSUE TITLE
[REQUEST] PhotoSync

### ISSUE THREAD

**Issue by phantomedc** [swaggyP36000/TrollStore-IPAs#741]
PhotoSync Pro features
https://apps.apple.com/us/app/photosync-transfer-photos/id415850124
please add this app to enable auto transferring and full image quality

**Comment by racedickinson** [comment]
**App name:** mood.camera

**Link:** https://apps.apple.com/bg/app/mood-camera/id6472954208

**Request:** Premium unlocked

**Reason:** it’s very easy to take professional looking picture, my free trial has ended :(

**Thanks in advance!**

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app and I'll upload it in a few hours!

You can download the latest version **[here](https://gofile.io/d/GlML9A)** if you prefer not to wait.
