### ISSUE TITLE
[Request] My Timetable - Quick & Simple

### ISSUE THREAD

**Issue by ShazPx** [swaggyP36000/TrollStore-IPAs#747]
App name: My Timetable - Quick & Simple

Link: https://apps.apple.com/my/app/my-timetable-quick-simple/id1498484092

Request: Premium unlocked

Reason: I want to share my timetable to a friend but it requires premium to do it. 

Thank you so much in advance if you decide to help me with this request! 🙏

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app and I'll upload it tomorrow!

You can download the latest version **[here](https://gofile.io/d/gqsudH)** if you prefer not to wait.

**Comment by ShazPx** [comment]
Thank you so much, you're the best!
