### ISSUE TITLE
[Request] Joint pro ipa

### ISSUE THREAD

**Issue by Warninn** [swaggyP36000/TrollStore-IPAs#750]
App name: Joint Craft - 3D Print Monitor

Link: https://apps.apple.com/us/app/joint-craft-3d-print-monitor/id6455888249

Request: Pro unlocked

Reason: I want the live activities to see the progress of the print

thanks

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app, you can download it **[here](https://gofile.io/d/oJNLWW)**. 

*Note: This won't be uploaded on the repo*

**Comment by Warninn** [comment]
tysm
