### ISSUE TITLE
[REQUEST] Grammarly: AI Writing Keyboard

### ISSUE THREAD

**Issue by dvl2014** [swaggyP36000/TrollStore-IPAs#752]
**App Name**: Grammarly: AI Writing Keyboard 

**Request(s)**: Premium Unlocked 

**Reason**: Because Grammar & Writing Has Always Been Not My Greatest Strength And I Usually Email And Message My Professors At College & People At Work Often From My Phone, Would Love Premium Unlocked For This App So I Can Improve How I Talk To/Communicate With People. Plus I Am Sure Many Others Would Love & Appreciate This Request Too! 

**App Store Link**: https://apps.apple.com/us/app/grammarly-ai-writing-keyboard/id1158877342 

**Other**: As Always, Thank You For All You Do!

**Comment by dvl2014** [comment]
Hi! I saw you closed it but dont see a comment, I assume this is not do-able? Thanks!

**Comment by ArianaMinajj** [comment]
Hello,

It appears you didn't take a moment to review the repository by looking at the app; Last year, there was a tweak available for Grammarly but it wasn't actually working. The keyboard seems to be entirely server-sided, so there's nothing that can be done about it.
