### ISSUE TITLE
[Request] Lightleap Pro

### ISSUE THREAD

**Issue by Lawrence323tw** [swaggyP36000/TrollStore-IPAs#753]
App Name: Lightleap 

Request: Lightleap unlimited access

App Store Link: https://apps.apple.com/us/app/lightleap-by-lightricks/id1254875992

Reason: Lightleap is a powerful photo editing app that lets you change the sky, remove imperfections, apply filters and effects, and make precise adjustments. Transform your photos with ease and achieve professional results effortlessly.

Thank you so much in advance if you decide to help me with this request! 🙏

**Comment by ArianaMinajj** [comment]
Hello,

I just uplodad it!

**Comment by Lawrence323tw** [comment]
Thank you so much

**Comment by ArianaMinajj** [comment]
I can't reproduce that "issue" because it is working for me.

**Note: If you installed the app without TrollStore, please don't open an issue as it will be closed for being invalid and unrelated to TS.**
