### ISSUE TITLE
[Request] CapCut - Video Editor

### ISSUE THREAD

**Issue by ShazPx** [swaggyP36000/TrollStore-IPAs#759]
App name: CapCut - Video Editor

Link: https://apps.apple.com/us/app/capcut-video-editor/id1500855883

Request: Pro Unlocked

Reason: I wonder if you can crack this app and make pro unlocked.

Thank you so much in advance if you decide to help me with this request! 🙏

**Comment by ShazPx** [comment]
Hi? i saw you flag it as duplicate, where can I find the original post? Thank you

**Comment by ArianaMinajj** [comment]
Hello,

This has already been requested and closed twice **[here](https://github.com/swaggyP36000/TrollStore-IPAs/issues/206)** and **[here](https://github.com/swaggyP36000/TrollStore-IPAs/issues/509)**
