### ISSUE TITLE
BHTikTokPlus 2.3 + 31.7.0 update

### ISSUE THREAD

**Issue by mbs0ft** [swaggyP36000/TrollStore-IPAs#76]
Download: [Google Drive](https://drive.google.com/file/d/1YqN_ZQ21r61-FTG_DXibcNK_yBP2h7N3/view?usp=sharing), [Mega.nz](https://mega.nz/file/NN1lASrL#5NcS2-ep4Jvg8tczo1MRvC5uKqxKc8rMQK2i6c1962U)
TikTok .ipa from [decrypt.day](https://decrypt.day/app/id835599320)
Injected with Sideloadly
![IMG_9D9AD364C270-1](https://github.com/swaggyP36000/TrollStore-IPAs/assets/22106304/aa401da3-b4c2-4eb7-8d8c-1b48676337ca)

**Comment by mbs0ft** [comment]
> Could you please grant me permission to upload it to the repo?

Yes, sure! You can upload this .ipa to the repo

**Comment by asdfzxcvbn** [comment]
face id might not work if injected with sideloadly without adding the necessary plist key. should check that

**Comment by mbs0ft** [comment]
> face id might not work if injected with sideloadly without adding the necessary plist key. should check that

What injecting tool do you prefer?

**Comment by asdfzxcvbn** [comment]
> > face id might not work if injected with sideloadly without adding the necessary plist key. should check that
> 
> What injecting tool do you prefer?

with [pyzule](https://github.com/asdfzxcvbn/pyzule), you can properly make a bhtiktok ipa by first making a `faceid.plist` file with the following contents:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>NSFaceIDUsageDescription</key>
    <string>hi, this is for face id -zx</string>
</dict>
</plist>

```

then using the following command:
`pyzule -i <decrypted tiktok> -o BHTikTokPlus -uwsf bhtiktok_2.3_iphoneos-arm.deb -l faceid.plist -m 11.0`

i also like injecting [OpenTikTokSafariExtension](https://github.com/BillyCurtis/OpenTikTokSafariExtension) for jailed users.
