### ISSUE TITLE
multiple features within the latest regram update have stopped working 

### ISSUE THREAD

**Issue by 001bl33d** [swaggyP36000/TrollStore-IPAs#763]
profile analyzer stopped working stating “please be logged in with the account” when i am and unsent messages aren’t being saved anymore havent tested anything else so i’ll update if theres more 
![C2DF71FF-5F88-4D41-945D-5478332705B0](https://github.com/user-attachments/assets/dbe7d54f-35a8-4265-a9bc-5ce523e99c7b)

https://github.com/user-attachments/assets/9048c9d7-27f5-4fc3-9a24-b7393bc9ecb8

**Comment by ArianaMinajj** [comment]
Hello,

This is a known issue and probably won't be fixed unless the original tweak maintainer decides otherwise..
