### ISSUE TITLE
[App Tweak Request] Hevy workout Tracker Pro

### ISSUE THREAD

**Issue by Troopica1** [swaggyP36000/TrollStore-IPAs#777]
Pretty much just need a source for this **pro version** cuz I've got a 5 day split and I don't want another subscription :|

Hevy app:
https://apps.apple.com/us/app/hevy-workout-tracker-gym-log/id1458862350

P.S. Sorry if this post goes against the reporting issues, instructions are pretty unclear on wether requesting an app is allowed. Nonetheless would be great if u considered making this _mod_

**Comment by Renoria** [comment]
would the Apple Watch app install if you install this IPA?
