### ISSUE TITLE
Instagram Regram

### ISSUE THREAD

**Issue by WhySooooFurious** [swaggyP36000/TrollStore-IPAs#778]
Found a way to get profile analyser working!

got contacts or do I have to msg here?

**Comment by ArianaMinajj** [comment]
Hello,

Please share the instructions here, I'll update the description if they work for me. Thanks in advance!

**Comment by WhySooooFurious** [comment]
Working on iOS 18.1 iPhone 15 Pro Max using E-Sign

1. Uninstall any other version of ig you might have with the same bundle id.
2. Reinstall Instagram Regram from the swaggy repo
3. Find the account and license feature in regram settings
4. Logout of the 'cracked' account
5. Sign up for your own account and login using those credentials!
6. You should have no premium features now
7. Reinstall instagram regard from the swaggy repo again
8. You should now have the profile analyser features with your own account being logged in!

Sorry Fouad

**Comment by ArianaMinajj** [comment]
Which version de we have to reinstall?

**Comment by WhySooooFurious** [comment]
Latest one ig

**Comment by WhySooooFurious** [comment]
I installed 347.2.5 with 1.0b10 of regard if it matters

**Comment by ArianaMinajj** [comment]
Not working for me *(on TS)* from the 5th step because the account automatically gets cracked. 

I'm not mentioning your "fix" since it seems unrelated to TS but thanks anyway!

**Comment by WhySooooFurious** [comment]
Welp, works for me though, TS should do the same thing.

I guess not based on your exp.
