### ISSUE TITLE
[Request] Reeder Classic

### ISSUE THREAD

**Issue by shy-tangerine** [swaggyP36000/TrollStore-IPAs#785]
### App Store Link

https://apps.apple.com/us/app/reeder-classic/id1529445840

### Feature to Unlock

All of them

### Acknowledgment

- [X] I am using TrollStore and requesting an app that I will install with TrollStore.
- [X] This request is not a duplicate and is unique.
- [X] I am aware and agree with my request being closed for one or multiple reasons explained either by labels or a comment.
- [X] I have requested an app that hasn’t been taken down due to takedown removal or DMCA claims.
- [X] I understand that if any of the above conditions are not respected, and this occurs twice in the same month, I will be permanently banned from interacting with the repository.

**Comment by ArianaMinajj** [comment]
Hello,

I'll upload it tomorrow! You can download it **[here](https://gofile.io/d/AxvYgr)** if you prefer not to wait.
