### ISSUE TITLE
[Request] TwitchPlus files

### ISSUE THREAD

**Issue by korboybeats** [swaggyP36000/TrollStore-IPAs#79]
Is it possible you can upload the TwitchPlus files so I can compile the Twitch IPAs myself?

**Comment by ArianaMinajj** [comment]
Hi there,

Unfortunately, I do not have access to the TwitchPlus files that you are looking for. However, you may want to check out the [TwitchAdBlock](https://github.com/level3tjg/TwitchAdBlock) repo. I hope this helps!

**Comment by korboybeats** [comment]
> Hi there,
> 
> Unfortunately, I do not have access to the TwitchPlus files that you are looking for. However, you may want to check out the [TwitchAdBlock](https://github.com/level3tjg/TwitchAdBlock) repo. I hope this helps!

How do you compile the Twitch IPAs? Or are the IPA's from a different source?

**Comment by ArianaMinajj** [comment]
As I've already mentioned in the repo, I simply gather the IPAs from various sources. I don't personally compile the Twitch IPAs.
