### ISSUE TITLE
[App Tweak Request] Hevy

### ISSUE THREAD

**Issue by Troopica1** [swaggyP36000/TrollStore-IPAs#790]
### App Store Link

https://apps.apple.com/us/app/hevy-workout-tracker-gym-log/id1458862350

### Feature to Unlock (if they exist)

Pro / Premium

### App Description (Optional but recommended)

Progressive overload tracker. Pro feature is used to create unlimited routines, track advanced measurements, get unlimited access to graph history / data, & create custom excersises. 

### Acknowledgment

- [X] I am using TrollStore and requesting an app that I will install with TrollStore.
- [X] This request is not a duplicate and is unique.
- [X] I am aware and agree with my request being closed for one or multiple reasons explained either by labels or a comment.
- [X] I have requested an app that hasn’t been taken down due to takedown removal or DMCA claims.
- [X] I understand that if any of the above conditions are not respected, and this occurs twice in the same month, I will be permanently banned from interacting with the repository.

**Comment by ArianaMinajj** [comment]
Hello,

You used the incorrect template; it should have been **App Tweak Request**. 


Note: Do not recreate this request as there is currently no tweak available for this app. *(yet)*
