### ISSUE TITLE
[App Issue] InstaRocketCracked - Auto log out on app close, re-login required upon app re-opening

### ISSUE THREAD

**Issue by TheAKurtzman3** [swaggyP36000/TrollStore-IPAs#791]
### App Name

InstaRocketCracked

### Issue Description

App logs out automatically when closed, requires re-login when app re-opened.

### Steps to Reproduce

1. Open app
2. Sign in to Insta account
3. After using app, close up by killing it in app switcher
4. Re-open app
5. Prompt to re-sign back into Insta account

Happens every time after InstaRocketCracked v344.0.9-3.8.27, which is the last version that didn't prompt for sign in every time.
Have been using InstagramRocket v.346.0.7-3.8.29 in the interim. For some reason, this one doesn't prompt for sign in each time, but would prefer the cracked version as it's more up to date.

### Device Information

iPhone 15 Pro Max, iOS 17.6.1

### Acknowledgment

- [X] I’ve checked if this issue is known but haven’t found anything mentioning it yet.
- [X] I am using the latest version of TrollStore and having an issue with an app I installed with it.
- [X] This is not a duplicate; this issue is unique or has arisen again.
- [X] I understand that if I have an issue with an app that has its own dedicated/original repository, I should open the issue there instead of here.
- [X] I am aware and agree with my issue being closed for one or multiple reasons explained either by labels or a comment.
- [X] If the assignee cannot reproduce the issue, I am okay with it being closed and will have to figure out the issue on my end.

**Comment by ArianaMinajj** [comment]
Hello, 

You're permanently banned from the repository for the following reason: **False information on the second acknowledgment**. *Please note that any issues you open will be closed as completed and labeled as spam.*
