### ISSUE TITLE
[App Tweak Request] Hurricane Outbreak

### ISSUE THREAD

**Issue by TungyHundra** [swaggyP36000/TrollStore-IPAs#793]
### App Store Link

https://apps.apple.com/us/app/hurricane-outbreak/id1492545081

### Feature to Unlock

- Feature 1: Global Warming Scenario (a special mode/scenario where hurricanes are deadlier)
- Feature 2: Premium (removes ads, unlock time dialation)

### App Description (Optional but recommended)

Game in which you control a hurricane, causing as much damage as possible.

### Acknowledgment

- [X] I am using TrollStore and requesting an app that I will install with TrollStore.
- [X] This request is not a duplicate and is unique.
- [X] I am aware and agree with my request being closed for one or multiple reasons explained either by labels or a comment.
- [X] I have requested an app that hasn’t been taken down due to takedown removal or DMCA claims.
- [X] I understand that if any of the above conditions are not respected, and this occurs twice in the same month, I will be permanently banned from interacting with the repository.

**Comment by ArianaMinajj** [comment]
Hello,

Please be aware that games are not allowed on this repository and I’ll be mentioning that shortly!

*Note: If your next issue is also found to be invalid, you’ll be permanently banned.*
