### ISSUE TITLE
[Paid App Request] BimmerLink

### ISSUE THREAD

**Issue by Roylax1337** [swaggyP36000/TrollStore-IPAs#794]
### App Store Link

https://apps.apple.com/us/app/bimmerlink-for-bmw-and-mini/id1065360416

### Feature to Unlock (if they exist)

All

### App Description (Optional but recommended)

Popular app for BMW/MINI car diagnostics

### Acknowledgment

- [X] I am using TrollStore and requesting an app that I will install with TrollStore.
- [X] This request is not a duplicate and is unique.
- [X] I am aware and agree with my request being closed for one or multiple reasons explained either by labels or a comment.
- [X] I have requested an app that hasn’t been taken down due to takedown removal or DMCA claims.
- [X] I am not requesting for an app update nor a game, as both are NOT ALLOWED in this repository.
- [X] I understand that if any of the above conditions are not respected, and this occurs twice, I will be permanently banned from interacting with the repository.

**Comment by ArianaMinajj** [comment]
Hello, 

This app is available but it's an extremely outdated version. 

*Note: I can still send the ipa if needed but it won't be uploaded here.*
