### ISSUE TITLE
[Paid App Request] ToneStack Pro

### ISSUE THREAD

**Issue by Aethereux** [swaggyP36000/TrollStore-IPAs#795]
### App Store Link

https://apps.apple.com/ph/app/tonestack-pro-guitar-amps-fx/id1529842791

### Feature to Unlock (if they exist)

- Unlock All

### App Description (Optional but recommended)

<details>
  <summary>Extra Request (if you don’t mind)</summary>
I’d like to know how you get the ipa of the app or the decrypted version (especially this). So in the near future I could do it myself. contact me via discord: euxx.
  
</details>

### Acknowledgment

- [X] I am using TrollStore and requesting an app that I will install with TrollStore.
- [X] This request is not a duplicate and is unique.
- [X] I am aware and agree with my request being closed for one or multiple reasons explained either by labels or a comment.
- [X] I have requested an app that hasn’t been taken down due to takedown removal or DMCA claims.
- [X] I am not requesting for an app update nor a game, as both are NOT ALLOWED in this repository.
- [X] I understand that if any of the above conditions are not respected, and this occurs twice, I will be permanently banned from interacting with the repository.

**Comment by ArianaMinajj** [comment]
Hello,

You have previously requested that app [here](https://github.com/swaggyP36000/TrollStore-IPAs/issues/697) and I have already explained that it will not be added to the repository.

*Note: If your next issue is also found to be invalid, you’ll be permanently banned.*

**Comment by Aethereux** [comment]
Apparently, that link no longer has the ipa file or it is removed.
