### ISSUE TITLE
[App Issue] Transit Royale

### ISSUE THREAD

**Issue by 1vvyyy** [swaggyP36000/TrollStore-IPAs#797]
### App Name

Transit

### Issue Description

App crashes on start up (won’t load at all)

### Steps to Reproduce

1. Attempt to Open app
2. App crashes immediately 

### Device Information

iphone 13 IOS 17.6

### Acknowledgment

- [X] I’ve checked if this issue is known but haven’t found anything mentioning it yet.
- [X] I am using the latest version of TrollStore and having an issue with an app I installed with it.
- [X] This is not a duplicate; this issue is unique or has arisen again.
- [X] I understand that if I have an issue with an app that has its own dedicated/original repository, I should open the issue there instead of here.
- [X] I am aware and agree with my issue being closed for one or multiple reasons explained either by labels or a comment.
- [X] If the assignee cannot reproduce the issue, I am okay with it being closed and will have to figure out the issue on my end.
- [X] I acknowledge that if I fail to respect any of the acknowledgments, I will be permanently banned from the repository. Any future issues I open will be closed and marked as SPAM.

**Comment by ArianaMinajj** [comment]
Hello, 

You're permanently banned from the repository for the following reason: **False information on the second acknowledgment**. *Please note that any issues you open will be closed as completed and labeled as spam.*
