### ISSUE TITLE
OnSkin – AI Product Scanner

### ISSUE THREAD

**Issue by ibrokethelaw** [swaggyP36000/TrollStore-IPAs#798]
### App Store Link

https://apps.apple.com/gr/app/onskin-ai-product-scanner/id1630768985?ppid=4a9e69d8-384b-4050-8342-a158495b6025

### Feature to Unlock

- OnSkin PRO Subcription (Yearly Access)

### App Description (Optional but recommended)

Avoiding skin treatments that carry potential risks with duentiningredients
—
Utilization of the application for only personal purposes
—
_PS.  Nice job with the new format of the request issues. 
Maybe you could think about adding a disclaimer saying ‘for personal use only’ (feel free to reach out to me for more details)._

### Acknowledgment

- [X] I am using TrollStore and requesting an app that I will install with TrollStore.
- [X] This request is not a duplicate and is unique.
- [X] I am aware and agree with my request being closed for one or multiple reasons explained either by labels or a comment.
- [X] I have requested an app that hasn’t been taken down due to takedown removal or DMCA claims.
- [X] I am not requesting for an app update nor a game, as both are NOT ALLOWED in this repository.
- [X] I understand that if any of the above conditions are not respected, and this occurs twice, I will be permanently banned from interacting with the repository.

**Comment by ArianaMinajj** [comment]
Hello,

Currently, there isn't a tweak available for this app. While your request is denied for now, it will be reconsidered once a future tweak becomes available!

*Note: Seems like you have a question about this template, feel free to open a separate question or contact me elsewhere if preferred!*
