### ISSUE TITLE
[App Tweak Request] Taio

### ISSUE THREAD

**Issue by shy-tangerine** [swaggyP36000/TrollStore-IPAs#799]
### App Store Link

https://apps.apple.com/app/id1527036273

### Feature to Unlock

All the Pro features, specially the Actions and Source Code Editing

### Acknowledgment

- [X] I am using TrollStore and requesting an app that I will install with TrollStore.
- [X] This request is not a duplicate and is unique.
- [X] I am aware and agree with my request being closed for one or multiple reasons explained either by labels or a comment.
- [X] I have requested an app that hasn’t been taken down due to takedown removal or DMCA claims.
- [X] I am not requesting for an app update nor a game, as both are NOT ALLOWED in this repository.
- [X] I understand that if any of the above conditions are not respected, and this occurs twice, I will be permanently banned from interacting with the repository.

**Comment by ArianaMinajj** [comment]
Hello, 

I just uploaded it!
