### ISSUE TITLE
New Game Cracked: Resident Evil Village

### ISSUE THREAD

**Issue by lilnext01** [swaggyP36000/TrollStore-IPAs#80]
(Full game for Free) iOS/iPadOS

**Comment by ArianaMinajj** [comment]
Hi there,

Given that "Resident Evil Village" is designed to run exclusively on the latest iOS 17 and iPhone 15, both of which are not readily available to all users, there are already several reliable sources, such as trusted websites and Telegram channels, where this game can be found. As a result, I do not offer it through this repository.

Thank you for your understanding!
