### ISSUE TITLE
[App Tweak Request] MyWhoosh: Indoor Cycling App

### ISSUE THREAD

**Issue by NicolasBse** [swaggyP36000/TrollStore-IPAs#803]
### App Store Link

https://apps.apple.com/us/app/mywhoosh-indoor-cycling-app/id1498889644

### Feature to Unlock

- Gem Vault : $79.99

### App Description (Optional but recommended)

I think the in-app purchases can be cracked by LocaliAppStore since the system is new, but you need to create an account to use the app.

### Acknowledgment

- [X] I am using TrollStore and requesting an app that I will install with TrollStore.
- [X] This request is not a duplicate and is unique.
- [X] I am aware and agree with my request being closed for one or multiple reasons explained either by labels or a comment.
- [X] I have requested an app that hasn’t been taken down due to takedown removal or DMCA claims.
- [X] I am not requesting for an app update nor a game, as both are NOT ALLOWED in this repository.
- [X] I understand that if any of the above conditions are not respected, and this occurs twice, I will be permanently banned from interacting with the repository.

**Comment by ArianaMinajj** [comment]
Hello,

I won't take that request because it seems to be a game. *(despite being categorized as an app on the App Store)*

Sorry about that!
