### ISSUE TITLE
[App Tweak Request] Outplayet Advanced 

### ISSUE THREAD

**Issue by SuperWp20** [swaggyP36000/TrollStore-IPAs#805]
### App Store Link

https://apps.apple.com/br/app/outplayer/id1449923287

### Feature to Unlock

Unlock the "Outplayer Premium" features for free.
Unlock without always having to go into the settings and "simulate" the "purchase" every time you reopen the app.

### App Description (Optional but recommended)

It would be good because it's the best player for ios, the only one based on MPV.
Everything is reproduced more accurately than the other options.
Without "Premium" it's not even possible to use subtitle delay and a few other things that are obviously necessary in a player. Thanks to "Premium" you open up options for improving the video, modifying subtitles, etc...
There is a mod in "IOS CODEVN", but it's not the best possible, as it forces you to "simulate" the "purchase" every time you reopen the app. I don't know if there's a better mod, so I've come to you, who I imagine have more "information" on the subject because you're more "in the know".

### Acknowledgment

- [X] I am using TrollStore and requesting an app that I will install with TrollStore.
- [X] This request is not a duplicate and is unique.
- [X] I am aware and agree with my request being closed for one or multiple reasons explained either by labels or a comment.
- [X] I have requested an app that hasn’t been taken down due to takedown removal or DMCA claims.
- [X] I am not requesting for an app update nor a game, as both are NOT ALLOWED in this repository.
- [X] I understand that if any of the above conditions are not respected, and this occurs twice, I will be permanently banned from interacting with the repository.

**Comment by ArianaMinajj** [comment]
Hello,

I won't take that request because each tweak *(on this app)* requires reopening and repurchasing it every time. Sorry about that!
