### ISSUE TITLE
BHX - Sideload Release Request

### ISSUE THREAD

**Issue by Infinitay** [swaggyP36000/TrollStore-IPAs#81]
According to the README entry for BHX,

> Twitter, with added features such as custom fonts, video saving, no ads, tabs customization, and more! **For people who aren't using TrollStore, use the non-TS IPA from BandarHL's GitHub**

The sideload-compiled ipa seems to be outdated as the last release was back in August 28th. Would you mind uploading the the sideload capable ipa for this respect modified ipa with Bandar's Twitter tweak? Also, if it's not too much to ask could you do the same for any other ipa whose trollstore version is not compatible with just a sideload? Thank you

**Comment by ArianaMinajj** [comment]
Hi there,

I apologize for any confusion the README may have caused. All versions of BHX work even when sideloaded. I will be updating the README to clarify this point and prevent further misunderstandings. 

Please don't hesitate to raise any other concerns or issues you may have.

**Comment by Infinitay** [comment]
Thanks for the clarification.
