### ISSUE TITLE
uYouPlusExtra-18.44.3-3.0.1-F2 Bug |

### ISSUE THREAD

**Issue by TronziaHQ** [swaggyP36000/TrollStore-IPAs#82]
Alright so basically, I recently updated my uYouPlusExtra to “uYouPlusExtra-18.44.3-3.0.1-F2” and now when I press on a video to play it as soon as it loads the app crashes.

**Comment by TronziaHQ** [comment]
“Wontfix”? What does that mean?

**Comment by ArianaMinajj** [comment]
Hi there,

Thank you for reporting this issue. However, it's worth noting that this is a known issue from this telegram [channel](https://t.me/zxcvbn_tweaked) that isn't universally experienced. In fact, I haven't been able to reproduce the problem on my end, so it's challenging for me to pinpoint why this might be happening to you.

As a possible workaround, I recommend downloading the latest IPA from the original [source](https://github.com/arichorn/uYouPlusExtra/releases) which will be re-uploaded here. Alternatively, you could consider reverting back to a previous version.

I apologize for the inconvenience and appreciate your patience.

**Comment by TronziaHQ** [comment]
I don’t know if it’s important information but I installed the app using TrollStore. @ArianaMinajj

**Comment by ArianaMinajj** [comment]
Could you kindly consult **[#174](https://github.com/arichorn/uYouPlusExtra/issues/174#issuecomment-1807077606)** and replicate the outlined steps?

**Comment by TronziaHQ** [comment]
> Could you kindly consult **[#174](https://github.com/arichorn/uYouPlusExtra/issues/174#issuecomment-1807077606)** and replicate the outlined steps?

I updated to the latest UYouPlusExtra version a while ago from here and it’s been working fine. Still the issue exists in other versions. I’ll report to you if anything changes with newer releases.

**Comment by ArianaMinajj** [comment]
Hello! 

First off, thank you for your relentless effort and dedication in providing us with the best YouTube experience possible. I will definitely mention that in the app's description. (for the benefit of users who might be encountering the same problem)

Honestly, I never saw any reason to hate/dislike the old tweak name; it was just a name to me? However, as the name has been updated I must follow it.

Once again, your hard work is greatly appreciated. Thank you for everything you're doing for us!
