### ISSUE TITLE
Error adding TrollStore IPA Source to Altstore

### ISSUE THREAD

**Issue by garshmo** [swaggyP36000/TrollStore-IPAs#84]
adding this json https://raw.githubusercontent.com/swaggyP36000/TrollStore-IPAs/main/apps.json)  as a source in Altstore brings back this error :

The source "swaggyP36000 IPA Library" contains multiple apps with the bundle identifier com.burbin.instagram. 

![image](https://github.com/swaggyP36000/TrollStore-IPAs/assets/109909393/08c10a43-ca06-4ddb-9b04-2fcaea466d1b)

**Comment by ArianaMinajj** [comment]
Duplicate of **#32**. Kindly review all issues before creating duplicates.
