### ISSUE TITLE
Swift Playgrounds

### ISSUE THREAD

**Issue by EncryptionEnjoyer** [swaggyP36000/TrollStore-IPAs#9]
Hey there,
could you get Apple‘s Swift Playgrounds from the AppStore by any chance? Tried getting it with Bundlr & AppStore++ but it won‘t find the bundleId. I don’t really know why i want that, i guess just to test it, but like upgrading iPadOS to 16.0+ isn’t an option..
Thanks if you are able to get it!

**Comment by swaggyP36000** [comment]
From what I am seeing, this is not available for iPhone, which means I won't be able to decrypt and upload it myself. The iOS 16+ requirement means that it likely requires frameworks that aren't available for any TrollStore-compatible iOS versions. Sorry about that
