### ISSUE TITLE
[Request] Filza with no url scheme

### ISSUE THREAD

**Issue by Ephaltes** [swaggyP36000/TrollStore-IPAs#90]
Hallo,

can you upload a filza version without the url scheme because some apps use the url scheme (filza://) to 
detect wheter a jailbreak is installed or not

kind regards

**Comment by ArianaMinajj** [comment]
Hello,

Absolutely, I will re-upload that version as soon as possible. Meanwhile, you can use this link to download the latest version without the URL scheme: [tigisoftware](https://tigisoftware.com/download/Filza_NoURLScheme_4.0.0.ipa).
