### ISSUE TITLE
No Premium on GoodNotes 6 for iPadOS

### ISSUE THREAD

**Issue by Janisbtw** [swaggyP36000/TrollStore-IPAs#93]
It still asks you to upgrade if you want more than 3 notebooks.
Using TrollStore 2.0.8

**Comment by ArianaMinajj** [comment]
Hello,

To better assist you, could you please specify the iOS version you're currently using? Please remember to include all necessary details **as outlined in the reporting rules**.

Thank you!

**Comment by ArianaMinajj** [comment]
To know if the issue lies in Goodnotes or your OS environment, you can try installing another app from the same repository that also has a premium tweak *(Carrot Weather for example)*. If that app works fine, then the problem could be specific to the Goodnotes app.

While I'm not using an iPad (even though the app is primarily designed for it), I found the application is working on my end with iOS 15.5. Therefore, I might consider revising its description.

**Comment by Janisbtw** [comment]
Thank you, will try that later and update you

**Comment by Janisbtw** [comment]
![10C23F50-2EF3-4616-AAA1-AB6B539533A8](https://github.com/swaggyP36000/TrollStore-IPAs/assets/35228757/76764070-93c9-4d8f-8e38-398a669006cb)
Carrot Weather works as expected with Ultra status

**Comment by ArianaMinajj** [comment]
Could you give [this version](https://gofile.io/d/ri33hx) of the IPA file a shot? It seems to be functioning for some iPadOS users, although I'm not sure which version they're using. You can find the file on [Dpixel's Telegram channel](https://t.me/dpixel).

*I manually decrypted Goodnotes 6 from the App Store using AppsDump2 and injected the tweak myself via Sideloadly. So, there may potentially be an issue stemming from this process I guess?*

**Comment by Janisbtw** [comment]
Just installed it again without iCloud sync and it‘s working too

**Comment by Janisbtw** [comment]
Sorry, should've clarified that I meant Goodnotes. The only thing I noticed is that the AI math converter fails every time I tried, but I guess that's not in your power to fix

**Comment by ArianaMinajj** [comment]
Was the iCloud sync causing issues with the tweak itself? Can you clarify which IPA version is functional? Is it the one from the repository or the one I linked earlier today? 

Any features necessitating a download or AI are both server-sided. This is something I can confirm, and unfortunately, as of now, there's nothing that can be done about it to make them work. Sorry about that I forgot to mention it.

**Comment by Janisbtw** [comment]
I don't know if iCloud sync has anything to do with the tweak working or not. I just disabled it because I didn't want to wait for the download as I was in school at the time so my connection was slow.
I used the ipa from your repo and changed the app name, app package name (.app directory) and the app bundle using ModMyIPA to install it alongside my regular Goodnotes 5 app.
If you want, I can check if it works with iCloud Sync tomorrow

**Comment by 0xModded** [comment]
Hey there. having the same issue. installed the version of goodnotes you provided earlier i the thread but no luck. ive tried via sidestore and nothing. ive logged out of my apple id so im going to uninstall and try again

**Comment by ArianaMinajj** [comment]
It seems to be specifically affecting iPads.. Given these circumstances, I may need to modify its description or even remove it entirely from the repository (as Goodnotes was intended for iPad use). I apologize for the false hopes the tweak may have given you. I don't have an iPad to test and initially assumed it would work on iPads as well..

**Comment by 0xModded** [comment]
Dont worry thanks anyways :) is there a chance you could replace it with a app called Notability? Thank you so much!

**Comment by ArianaMinajj** [comment]
Absolutely! I'll upload a version of Notability in this thread for your review before adding it to the repository.

Also, I just noticed you mentioned installing Goodnotes on iPadOS 17.1.2, I'm unsure this version is TrollStore compatible..

**Comment by 0xModded** [comment]
Yeah trollstore isn’t compatible, i used side store to install and even
took the ipa directly from the repo and sideloaded it with sideloadly
(windows)

**Comment by ArianaMinajj** [comment]
This info would have been useful if included in your initial message, as it provides clarity now.

I should have written in the description that this version of Goodnotes is exclusive to TrollStore so any other method of installation will fail resulting in a crash upon startup.

Meanwhile, I'll send a download link of Notability shortly!

**Comment by 0xModded** [comment]
Ahhh i see im super sorry! Also if the notability verson is the
Notability++_14.2.1_LeTi(1) filename, it doesn't work (as in no premium.)

**Comment by ArianaMinajj** [comment]
Here's the latest version of Notability with "Plus": (injected with Satella)

[NotabilityPlusTS-14.5](https://gofile.io/d/ofFOhB)

It might just crash for you because based on my tests it seems to only be compatible with TrollStore..

**Comment by 0xModded** [comment]
thank you! if anything is there a way i could downgrade my ios version? i
was on 16.1 and wanted a nicer home screen 😓

**Comment by ArianaMinajj** [comment]
You still have time to DelayOTA the iPadOS to 17.0! Be aware tho, this profile will expire on the morning of December 20.

**Comment by 0xModded** [comment]
Thanks! I tried to lookup how to use delayota to do this but no luck. do you have a guide i could follow? and theres no way to downgrade my ipados correct? also i get this error when using the ipa sent
![image](https://github.com/swaggyP36000/TrollStore-IPAs/assets/73260774/d04a6cc6-5fcd-4d0c-a4b5-63bd161e9cbd)

**Comment by ArianaMinajj** [comment]
Apologies for my delayed response. While I can provide you with a comprehensive guide on how to delayOTA, it might not directly address the original issue at hand.

Additionally, it appears that the app I uploaded is only compatible with iOS / TrollStore but strangely not for iPadOS. This is quite unexpected to me and something has to do with the version I uploaded..
