### ISSUE TITLE
Duolingo can't start lesson

### ISSUE THREAD

**Issue by 3rdQuasar** [swaggyP36000/TrollStore-IPAs#94]
Duolingo 7.2.0 it has super Duolingo but it can't start any lessons I'm using xs max on ios 16.2 any solution?

**Comment by ArianaMinajj** [comment]
Hi there,

Could you please explain the process you followed to install Duolingo?

**Comment by ArianaMinajj** [comment]
Please take the time to thoroughly review Duolingo's repository description before opening issues..

**Given that you've already opened two unnecessary issues within a single week, I will not prioritize closing your next issue immediately if it happens to be invalid for a third time.**

**Comment by 3rdQuasar** [comment]
Sorry my bad I thought it was a different version from iOSgods cause after install it doesn't have iOSgods logo, I will pay more attention next time

**Comment by ArianaMinajj** [comment]
I have personally removed iOSGod login and iGameGod from this version due to their redundancy and disturbance on the UI. Regardless, if you wish to install Duolingo, Sideloadly remains your only option as other will fail. Its status and description clearly indicate this with a "🚫", signifying its incompatibility with TrollStore.

**Comment by 3rdQuasar** [comment]
yeah look much better without it, only sideloadly nor altsotre?

**Comment by ArianaMinajj** [comment]
Sideloadly only, which necessitates the use of a computer. If you're unsure about its installation process on your PC, I'm here to guide you through it if you want.

**Comment by 3rdQuasar** [comment]
Thank you I know how does it work

**Comment by DimaSheiko** [comment]
Can it be used with eSign? I have installed it using esign and I cannot start a lesson.

**Comment by ArianaMinajj** [comment]
This is exclusively compatible with TrollStore just like the majority of apps on the repo. *(May also be compatible with Sideloadly)*

**Comment by DimaSheiko** [comment]
> This is exclusively compatible with TrollStore just like the majority of apps on the repo. _(May also be compatible with Sideloadly)_

Oh, I see. Thanks for the clarification. Do you have a repo you could share where most apps are compatible with eSign?

**Comment by ArianaMinajj** [comment]
You might want to have a look at **[this](https://repo.apptesters.org)**

**Comment by DimaSheiko** [comment]
> You might want to have a look at **[this](https://repo.apptesters.org)** (add this link into ESign)

I already had it, but thank you very much for sharing, greetings!
