### ISSUE TITLE
Adding mention of TrollApps request / Versions: []

### ISSUE THREAD

**Issue by Cleover** [swaggyP36000/TrollStore-IPAs#96]
Heyo, I'm a developer for the TrollApps project, a repo manager/app installer designed for TrollStore users. (It operates using AltStore repos).

I'm wondering if it would be possible to include a mention of TrollApps in your readme and provide a link to add this repo to TrollApps.

You can find us here: [https://github.com/TheResonanceTeam/TrollApps](https://github.com/TheResonanceTeam/TrollApps)

It's entirely understandable if not, but I thought it best to reach out and try.

It's possible to add an "Add Repo To TrollApps" button in your readme by using something like this:

`[![TrollStore-IPAs](https://img.shields.io/badge/Add%20repo%20to%20TrollApps%20-%20red?style=for-the-badge&color=dae6eb)](https://fwuf.in/#/trollapps://add?url=https://raw.githubusercontent.com/swaggyP36000/TrollStore-IPAs/main/apps.json)`

(The fwuf.in part is just a project of mine to allow embedding links that open in apps in GitHub markdown files, as normally it only allows https links).

Cheers!

Also, I noticed y'all are not using the `versions: []`, array for apps, to have one main app with multiple versions. Is there a reason for creating a new app entry with each version? There is info about it here, https://faq.altstore.io/distribute-your-apps/make-a-source#app-versions.

**Comment by ArianaMinajj** [comment]
Hello,

Thanks for reaching out and for your interest in the repository. I was a bit confused initially as TrollApps was already mentioned in the repo, but it seems like the one you're referring to is an upgraded version of the old one. This makes sense given that adding the repo to the old TrollApps resulted in instant crashes. 

I appreciate your suggestion and the straightforward code you've provided to add the "Add repo to TrollApps" button. It's a more efficient solution compared to ESign as a store and I'm grateful for the ease it provides!

As for the "versions: []" you're mentioning, I must admit, I'm not entirely sure how that works. I primarily focus on uploading new apps daily, so I might not be the best person to address this aspect..

Thank you once again for your helpful insights and for enhancing the utility of the repository. I'll add the button as soon as possible!

**Comment by Cleover** [comment]
Thanks!~

As for the version: [] part I mentioned, I'm currently creating a python script to convert the generated apps.json to a version which uses the correct AltStore versions syntax, however I'm unsure about one thing, why does the version key on some of the apps have a dash in between them?

Ie: `3.8.7-279.0`

It seem like some apps do this, and some don't, however I'm unsure what the dash between the two versions means.

As well, if you have a GitHub would it be possible to add me to talk back and forth a bit faster, no worries if not however I can continue to use this issue thread if that's easier for you.

My discord username is just `cleo`, you should be able to add me by sending as friend request to that without any numbers after it.

Cheers'
