### ISSUE TITLE
Altstore repo duplicates 

### ISSUE THREAD

**Issue by Vikram1807** [swaggyP36000/TrollStore-IPAs#97]
So many duplicates when i open in troll apps

**Comment by Vikram1807** [comment]
![image](https://github.com/swaggyP36000/TrollStore-IPAs/assets/44153720/43409cbe-7186-4d21-b7ad-a97e8f2cda9b)

**Comment by ArianaMinajj** [comment]
Hello,

Please review the 'Version Column' in the repository's description.
