### ISSUE TITLE
[Request] Consider Adding Additional Trollstore Apps

### ISSUE THREAD

**Issue by stuffed18** [swaggyP36000/TrollStore-IPAs#98]
I didn't include emulators, or games ported to iOS, but I can provide the list of them if you want. 
I used ctrl-f to check if they were in the list
1. Cardio - change apple pay card images https://github.com/cisc0disco/Cardio/releases 
2. Legizmo - you need to pay for this so idk if it should be on the list https://www.patreon.com/lunotech11 
3. Trolldecrypt - decrypt any installed app. https://github.com/donato-fiore/TrollDecrypt/releases/tag/v1.1   as well as this there is also an app called trolldecryptor but I haven't used it since this one works. 
4. Cocoatop - ios task manager https://raw.githubusercontent.com/baziex/TrollStoreApps/main/TrollStoreApps/CocoaTopTS_BZ.ipa 
5. Jitterbug - JIT with most TrollStore apps https://github.com/osy/Jitterbug/releases 
6. Ignited - I noticed delta was on the list, this is a fork with a lot more features https://github.com/Lit-Development/Ignited 
7. Trollspeed - Displays upload and download usage (like in mbps or kbps) in the status bar. I've tested it on ios 14 and it works. https://github.com/Lessica/TrollSpeed 
8. ScreenshotX - https://junesiphone.com/screenshotapp/SSApp4.zip 
9. Soundcloud scmusicplus https://github.com/Rov3r/scmusicplus 
10. TheChan - 4Chan client for ios https://github.com/TheChanDev/TheChan
11. Wifilist - See list of the passwords for wifi you have connected to in the past. https://www.reddit.com/r/jailbreak/comments/x7imd1/free_release_wifilist_for_trollstore_users/ 
12. Wifi Scanner - Gives you information (not the password) such as the seller, the location and many other information. https://www.dropbox.com/s/f2a50ac06miy490/Wi-Fi%20Scanner.ipa?dl=0 
13. Appdb - client for appdb https://github.com/n3d1117/appdb 

ok I have more but I am tired so cya.

**Comment by ArianaMinajj** [comment]
Hi there!

The word "missing" might not be the most fitting description here. I am aware of these apps and have intentionally not added them (yet). Some of them are new to me, while others don't have a clear utility for being in the repo.

I will add these apps only if they seem useful in the context of the repo. However, if you strongly feel that these apps should be included m for any reason, please tell me which one and I'd be more than happy to consider adding them!

**Comment by stuffed18** [comment]
Most of these apps are trollstore specific, and won't work sideloaded which is why I feel they would enhance this list. 
That includes trolldecrypt, trollspeed, wifilist, cardio, jitterbug, cocoatop, etc.

**Comment by ArianaMinajj** [comment]
I appreciate your suggestions and will gladly add these apps to the repo. If actually do have more apps that you think would enhance the list, feel free to send them way!

**Comment by PBF-TECHIE** [comment]
Wifi scanner is 1.0 and not working with ios17.

**Comment by PBF-TECHIE** [comment]
> Hi there,
> 
> "..not working" does not provide enough specifics, but I'm assuming you're referring to the app crashing upon launch. I'm also not sure why you've mentioned its version??
> 
> Remember, Wifi scanner is TS only and is significantly outdated. Tested and appears to be working fine on my end _(iOS 15.5, TrollStore 2.0.8)_.

yes app is crashing. yes it works fine ios 15 but not on ios 17. it is a nice app, version mentioned cuz if any update available after it??
