### ISSUE TITLE
Trying to update TikTokLRDCracked on TikTokLRD

### ISSUE THREAD

**Issue by upup666** [swaggyP36000/TrollStore-IPAs#99]
Trying to update from 31.9 to 32.5 via Sideloadly having this problem

There was an issue during installation: 3892346881: ApplicationVerificationFailed (Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.MYsB8g/extracted/Payload/TikTok.app/Extensions/TikTokBackgroundAssetExtension.appex : 0xe8008001 (An unknown error has occurred.))

What I need to change or just delete old one and install new one?

**Comment by ArianaMinajj** [comment]
I upgraded from version 31.9.0 to 32.5.0 to check if I would encounter the same problem as you, but my update process was smooth. So even if the installation had been successful, it's impossible to update a cracked version to the most recent one while maintaining the crack. 

You're basically replacing the existing cracked tiktokLRD with an uncracked version and this will simply prompt you to provide a license.. I'm not sure why you're doing this in the first place?

**Comment by upup666** [comment]
> I upgraded from version 31.9.0 to 32.5.0 to check if I would encounter the same problem as you, but my update process was smooth. So even if the installation had been successful, it's impossible to update a cracked version to the most recent one while maintaining the crack.
> 
> You're basically replacing the existing cracked tiktokLRD with an uncracked version and this will simply prompt you to provide a license.. I'm not sure why you're doing this in the first place?

I understand, so do you know this version already Cracked or I need code from LRD?

**Comment by ArianaMinajj** [comment]
As far as I know the most recent cracked version of TikTokLRD is 2.5 so if you wish to use the latest, licence is required from **[lazyshop](https://lazyshop.app)**.

**Comment by upup666** [comment]
> As far as I know the most recent cracked version of TikTokLRD is 2.5 so if you wish to use the latest, licence is required from **[lazyshop](https://lazyshop.app)**.

So are there new version of TikTok vs CrakedLrD version?

**Comment by ArianaMinajj** [comment]
No? I just told you
